### ISSUE TITLE
Understanding readme

### ISSUE THREAD

**Issue by tedbmoss** [pascallanger/DIY-Multiprotocol-TX-Module#1]
I would like to clarify the readme a little. 
particularly the reference to using the bind button and the unique ID.
The bind button is used only in the PPM mode of operation, otherwise bind is selected in the menus on the protocol page. The unique ID is applicable to all protocols, not one ID for each protocol.
It should be stated that the serial mode of operation is the preferred mode with ersky9x.

**Comment by pascallanger** [comment]
Actually the bind button does also work on serial but only at boot time.
I've done some modifications to the readme. Let me know if this is better now.
