### ISSUE TITLE
Irangex nano pl18 edgetx 2.10.3

### ISSUE THREAD

**Issue by swemiklan** [pascallanger/DIY-Multiprotocol-TX-Module#1002]
Flasht edgetx  to pl18  ( no hardware mod ) installd new nano module and tryed to bind. no luck.
Edgetx show ( no multi telemetry detected ) in model page and radio information.
Flash module wiht 1.3.3.33 managede after some trubble dfu mode/ usb i can read firmware of module trou flashmulti 6,1
still no luck binding, sam text in edgetx.  Now i am not able to read module wiht flashmulti, module led are solid green and red slow blink.   Elrs module works fine.
Can i erase module in flashmulti when its not responding/ able to read module.  Other suggestions. 
Bangood Note:
"The STM32 MCU have change to ARM, fireware is ARM CORTEX-M
The new stock will be ARM, Existing inventory is not affected"
Mikael

**Comment by pascallanger** [comment]
Which module is it?

**Comment by swemiklan** [comment]
IRangeX IRX4 LITE CC2500 NRF24L01+ A7105 CYRF6936 4 I 1 Multiprotokoll TX-modul för Frsky X-lite  from  bangood.

**Comment by swemiklan** [comment]
Now module is back in order Thank to Benlye.
Module is not recogniced by tx  ( no multi telemetry detected ).
How do i continue troubleshoot multimodule  (serial conection ) ?
Elrs module is working in same adaptor.

**Comment by swemiklan** [comment]
![20240823_183844](https://github.com/user-attachments/assets/3ebfd317-8765-478b-abc8-44d3e5d5a54b)

![20240823_183902](https://github.com/user-attachments/assets/acc47165-16af-4816-ade4-ed9015da8742)
![20240823_184059](https://github.com/user-attachments/assets/b6cb2ea1-49d2-4826-a556-8472d4ca324c)

**Comment by pascallanger** [comment]
What's the module LEDs doing ?

**Comment by swemiklan** [comment]
Solid green and red blink.

**Comment by swemiklan** [comment]
Does multimodule need more or other placement of serialport?
Nano adaptor has 3 wires and i have done conectivity test trou adaptor to inside module all good.
Nano adaptor works in radio wiht elrs module and radio works wiht jr adaptor and irangex plus module.

**Comment by pascallanger** [comment]
You are not saying how the module blinks...
The module needs 4 wires to work: Ppm, telem, gnd, batt.

**Comment by swemiklan** [comment]
Its green solid and red blink.
Ok now we getting som where, schematic on nano  and jr adapters i see 3 connections serialport to the right in adaptor where do fourth (ppm) go?
How can i compere jr bay pinout and nano pinout?
I need to trace out connetion to pl18.
I will start to google  Pinout,   THANKS ALOT  Mikael

**Comment by swemiklan** [comment]
PPM from pl18  = found    ( compared wiht fjr2 )
Now where to put it in MPM lite pinout ?
https://www.rcgroups.com/forums/attachmentNew.php?attachmentid=11016912  is all i found, In jr its equivalent toNr5 Pxx out on Nano/lite pinout?    Shoud i solder wire to pin nr 5 in nano adapter to try out?

**Comment by swemiklan** [comment]
So i tryed soldering wire from pin ppm/ RX in tx to pin 5  Pxx out in MPM and no difference.
![20240824_150437](https://github.com/user-attachments/assets/03dfc82b-6513-4def-881e-3ddbcac676a8) This is Frm301 Connection to Pl18
Adaptor has 3 wires from sport, gnd and +5v to serialport, gnd and vcc in Mpm originaly and now + my wire now.
Is there a need for more wires in adaptor maybe between Head/tx to Pxx in also ?

**Comment by swemiklan** [comment]
![20240824_175227](https://github.com/user-attachments/assets/f46ecc39-b697-4abe-bf18-d8251ce4d493)
Found this at last.
point 1  Is  rouled out.
point 2 FW on radio and module seems correct , inverson setting in use probleby not different mpm works.
point 3 Foulty module hmmm how do i solve that issue?
