### ISSUE TITLE
KYOSHO3 ASF is missing

### ISSUE THREAD

**Issue by mizuta1951** [pascallanger/DIY-Multiprotocol-TX-Module#1003]
STM32 surface, dose not show KYOSHO3 ASF.

**Comment by pascallanger** [comment]
Update your module?

**Comment by mizuta1951** [comment]
mm-stm-serial-aetr-sfc-v1.3.4.0.bin
dose not show up KYOSHO3 ASF.

**Comment by pascallanger** [comment]
Then use mm-stm-serial-aetr-sfc-v1.3.4.11.bin https://nightly.link/pascallanger/DIY-Multiprotocol-TX-Module/workflows/main/master/multi-test-build.zip

**Comment by mizuta1951** [comment]
Thank you !
Now I can drive my old Mini-Z.

**Comment by azilRC** [comment]
hi ! i just install the mm-stm-serial-aetr-sfc-v1.3.4.0 on my MT12 updated to EdgeTX "Centurion" v2.10.5 and koysho 3 / ASF is missing too :/
do you plan to fix that ? thanks

**Comment by pascallanger** [comment]
Just install the test version

**Comment by azilRC** [comment]
It works. Thanks
