### ISSUE TITLE
Protocols scanner

### ISSUE THREAD

**Issue by jacobbloy** [pascallanger/DIY-Multiprotocol-TX-Module#101]
With so many toys coming out is there a feature to scan a protocol. Let’s say you know the chip that is used, nrf24lo1 then the toy is in auto bind mode. Can we can through protocoles until we get a successful bind? Or is it all manual?

**Comment by Dutchy-79** [comment]
You can use a logical analyzer, there's a YouTube video about it.

**Comment by pascallanger** [comment]
If you are using serial mode you can just try all the nrf24l01 protocols and subprotocols.
