### ISSUE TITLE
New Protocol - WLToys W915 

### ISSUE THREAD

**Issue by inventor7777** [pascallanger/DIY-Multiprotocol-TX-Module#1012]
Hi! 

I have been trying to bind my RadioMaster MT12 4-in-1 to my WLToys W915 R/C boat and I cannot get it to bind under the WLToys protocol. The boat has an all-in-one ESC/RX combo which automatically binds to the TX upon startup. I’ve tried every combination of binding and can’t get it to work. Any idea why? Any possibility of support for this?

Thanks!

**Comment by pascallanger** [comment]
Without access to the TX & RX I can't do much...

**Comment by inventor7777** [comment]
@pascallanger thats what I figured. I just wanted to make sure! Thanks you!
