### ISSUE TITLE
Help adding new protocols 

### ISSUE THREAD

**Issue by jacobbloy** [pascallanger/DIY-Multiprotocol-TX-Module#102]
Is there any way that support could be added for an electric skateboard? The evolve gt uses nrf24lo1+ and seems to operate the same as an RC transmitter, it even has telemetry.
Because of the cheap way it was made I wouldn't be supprised if It is using an existing protocol.

Would you need both the board and transmitter to reverse engineer or could you do with just the transmitter? The transmitter has a cheap stc15w4k32s4 chip on it which I think I have seen on some china transmitters. Jacob.bloy@gmail.com

**Comment by jacobbloy** [comment]
![6ed649d9-f9de-470f-8663-e42504c3679d](https://user-images.githubusercontent.com/7373557/30508174-a5432b02-9acf-11e7-898e-d03d36c31098.jpeg)
![4e50f624-68a7-437b-a65e-7485040b6b65](https://user-images.githubusercontent.com/7373557/30508173-a52ec7ac-9acf-11e7-823f-1960de5f816e.jpeg)

**Comment by pascallanger** [comment]
We need dumps of what the protocol looks like. You could attach a logic analyzer to the SPI port of the nrf board that I can see on the top left of the 1st picture.
Protocols using the NRF are usually not having telemetry. So I'm thinking it's not a known protocol.
