### ISSUE TITLE
Binding but not receiving 

### ISSUE THREAD

**Issue by tommygunn212** [pascallanger/DIY-Multiprotocol-TX-Module#103]
I got an irangerx I seem to be able to bind dsm2 and dsmx I think because I get a solid red light after I hint the bind in er9x -r805 in my 9xr. 
But i get no movement on my test setup which is battery esc receiver and esc. 
I checked my mixers they seem to be correct.
I did try both sub setting on the multi. 

Any ideas?

**Comment by pascallanger** [comment]
No ideas. DSM has been stable for a long time.
Have you updated your module with the latest version?
