### ISSUE TITLE
Qidi 560 protocol

### ISSUE THREAD

**Issue by Solman79** [pascallanger/DIY-Multiprotocol-TX-Module#1039]
Has anyone managed to bind a Qidi 560 to a Jumper T-Lite with the 4in1 module? I saw an issue addressed by someone a few months but I can't find the Q560 protocol.

**Comment by pascallanger** [comment]
Install the test version: https://downloads.multi-module.org/latest-test/

**Comment by Solman79** [comment]
Ah, excellent. I downloaded the latest version but not the test one. I take it that is safe to use with my previously saved models. It's just the big warning on the page regarding not using the test build for flying
