### ISSUE TITLE
Hitec AFHSS

### ISSUE THREAD

**Issue by Ze-baloo** [pascallanger/DIY-Multiprotocol-TX-Module#104]
Hi all!

I've installed the multiprotocol module in my Taranis, and i love all its features.

I'm wondering if it'll be possibe to add th Hitec AFHSS protocol as Frsky's producing compatibe receivers for this brand.

Thank in advance for any reply.

Laurent

**Comment by schwabe** [comment]
Yes that would be possible if someone reverse engineers the protocol

**Comment by Ze-baloo** [comment]
Thanks for the reply 😉

I'd like to do it myself, but I must say that i will have a huge lack of knowledge.

By the way, I'm curious to know the reverse engineering process, to see if I could find the ressources to do it.

Laurent

**Comment by pascallanger** [comment]
It should be a quote easy protocol to reverse. But the problem is to have access to a transmitter and receiver...Le 2 nov. 2017 8:39 PM, Ze-baloo <notifications@github.com> a écrit :Thanks for the reply 😉
I'd like to do it myself, but I must say that i will have a huge lack of knowledge.
By the way, I'm curious to know the reverse engineering process, to see if I could find the ressources to do it.
Laurent

**Comment by tipouic** [comment]
If you want to know how the protocols are added, here is a link that explains how to do for the HUBSAN protocol
[http://www.jimhung.co.uk/?p=1349](url)
I wanted to do it for L939 WLTOYS car but the problem is the chip (a KN) and the lack of equipment.

**Comment by Ze-baloo** [comment]
In fact, I'm selling my Horus to one of my best friends who also owns the Aurora 9 and some hitec receivers. 😉

**Comment by Ze-baloo** [comment]
Tipouic, I am not able to open your link...

**Comment by tipouic** [comment]
Sorry typing error. Correction made
[http://www.jimhung.co.uk/?p=1349](http://www.jimhung.co.uk/?p=1349)

**Comment by pascallanger** [comment]
@Ze-baloo I'm ok to reverse engineer the Hitec protocol but you need to send me a TX and a RX to test on. Feel free to contact me on rcgroups by PM if this is something you are ok with. I'll return the hardware when I'm done with it.

**Comment by Ze-baloo** [comment]
@pascallanger Thanks for the proposal. As the radio gear isn't mine, I have to check with my friend. Were are you located?

**Comment by pascallanger** [comment]
Near Paris.

**Comment by Ze-baloo** [comment]
Fine, I'm in Normandy 60km south from Caen.
Not too far away 😉
How long will you need to do the reverse engineering?

**Comment by pascallanger** [comment]
It depends how well it goes... Let's say 2 weeks depending how busy I am. If I'm not done at this point I would only need to keep one RX a little longer to do my tests. I'll be at Courseulles-sur-mer the week of Christmas if that helps.

**Comment by pascallanger** [comment]
Any news?

**Comment by Ze-baloo** [comment]
Ooops. Sorry for the delay ;-)
A bit busy with my job and preparing christmas.

My friend is OK with the idea, He just need a bit time to program on the Horus the models already programmed on the Aurora.

By the way, i haven't found the way on github to send you a private message.

**Comment by pascallanger** [comment]
You can reach me on RCGroups pseudo hpnuts : https://www.rcgroups.com/forums/showthread.php?2165676-DIY-Multiprotocol-TX-Module/page704

**Comment by pascallanger** [comment]
What's the deal with this Hitec transmitter/receiver?

**Comment by Ze-baloo** [comment]
Send me a mail on my private address please 😉l(dot)bassaler(at)free(dot)frLe 19 déc. 2017 14:54, pascallanger <notifications@github.com> a écrit :What's the deal with this Hitec transmitter/receiver?

**Comment by TheRealMoeder** [comment]
Pascal, any progress on this issue?

**Comment by pascallanger** [comment]
Nobody ever sent me a TX and RX to do the reverse engineering....

**Comment by TheRealMoeder** [comment]
OK, thanks for the update!
