### ISSUE TITLE
Assan protocol

### ISSUE THREAD

**Issue by JivaroFAD** [pascallanger/DIY-Multiprotocol-TX-Module#11]
Hi Pascal,

Very very nice work :+1: 
It will a great addition to the DIY OpenTX NextStepRC project (here : https://github.com/Ingwie/NextStepRc-2.18), will you be ok allow me to use your code ?

Another question : as Assan use NFR24L01 chip, is it possible to add this protocol to your firmware ?
There is wome information about this here : http://tomsik.eu/assan_firmware

Best regards,
Franck

**Comment by pascallanger** [comment]
Hi Franck,
I'm fine for you to reuse any code you like. If you need details please contact me directly.

There are not enough information on this article to build an Assan transmitter. The bind part is missing and this is one of the most important thing with the channel hopping algo. I would need at least a few dumps of the spi communication between the µC and the NRF while binding and normal operation. And may be the same on another transmitter (or a few of them) to find out how to match the ID and channel hopping depending on how complex it is.
- Pascal
