### ISSUE TITLE
Typo: 

### ISSUE THREAD

**Issue by DrStein99** [pascallanger/DIY-Multiprotocol-TX-Module#122]
https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/5c568da1253644a52da0be04ad2f114609b826f9/Multiprotocol/Multi.txt#L28

Should read "AFHDS2A" not "AFHD2SA".  

Critical / optional / trivial ?

**Comment by pascallanger** [comment]
It has no consequences apart from the fact that on ersky9x radios the menu will display this typo...I've corrected it.Pascal

      De : DrStein99 <notifications@github.com>
 À : pascallanger/DIY-Multiprotocol-TX-Module <DIY-Multiprotocol-TX-Module@noreply.github.com> 
Cc : Subscribed <subscribed@noreply.github.com>
 Envoyé le : Mardi 12 décembre 2017 7h25
 Objet : [pascallanger/DIY-Multiprotocol-TX-Module] Typo: (#122)
   
https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/5c568da1253644a52da0be04ad2f114609b826f9/Multiprotocol/Multi.txt#L28Should read "AFHDS2A" not "AFHD2SA".Critical / optional / trivial ?—
