### ISSUE TITLE
Frsky EU LBT support for STM32

### ISSUE THREAD

**Issue by uragano47812** [pascallanger/DIY-Multiprotocol-TX-Module#134]
Hello is it possible to implement also the Frsky EU LBT protocol for STM32 module (like iRangeX) on next release? 
It would be wonderful thanks

**Comment by schwabe** [comment]
It is already implemented

**Comment by uragano47812** [comment]
Sorry i didn't see it. My apologize.

**Comment by uragano47812** [comment]
My fault
