### ISSUE TITLE
Port DeviationTX Cflie protocol to this project

### ISSUE THREAD

**Issue by JamesHagerman** [pascallanger/DIY-Multiprotocol-TX-Module#153]
Hello,

I realize the Crazyflie mini quads aren't as common as some of the others already in this project, but I've got one, there are a number of people that would still enjoy being able to breath new life into their Crazyflies and Crazyflie 2s...

And the protocol is already supported by DeviationTX using the following code:

https://github.com/DeviationTX/deviation/blob/4bd9c4bf0222fd8bb23ee8e224afba5fbcb02d26/src/protocol/cflie_nrf24l01.c

I'd be willing to port it (even if it's just in a fork) but I'm not sure how much that module would have to be modified to get things working.

Would it be possible for someone with some familiarity with these two projects (DIY-Muiltiprotocol-TX-Module and DeviationTX) to take a glance at this module and see if such a task is a fools errand?

Thanks,
James

**Comment by pascallanger** [comment]
It's around a 1 day work to get a protocol implemented from Deviation into Multi. Not difficult just taking time. The biggest thing is that someone has to be willing to test the code and provide fast feedback to new builds/tests. I can do it but not now as I'm already overloaded until end of April.
Pascal

**Comment by JamesHagerman** [comment]
@pascallanger Thanks for the reply!

I'll spend some time trying to get the protocol implemented and see how far I get. It doesn't seem that difficult after taking a closer look at the code.

I'll let you know if I get stuck on something.

**Comment by JamesHagerman** [comment]
Okay, I started porting the protocol in my fork:
https://github.com/JamesHagerman/DIY-Multiprotocol-TX-Module/commit/919cae26ebef34065f0d8d1db7c9bec96e7b5344

After selecting custom protocol 38 from inside OpenTX, attempting to bind the transmitter to the Crazyflie absolutely causes the Crazyflie's LEDs to change... but no other response occurs.

I'll have to dig deeper, but at least I have the development tool chain working!

I'll dig into this more and see if I can at least get a motor to spin...

**Comment by tipouic** [comment]
Hi, the CFLIE protocol has already been done by someone in his fork if you want to go faster.
Fork link : https://github.com/theseankelly/DIY-Multiprotocol-TX-Module/commit/89598937734a3c9101045b1c20acca753c9c881e

**Comment by JamesHagerman** [comment]
Oh wow! Thanks!

Digging through 100 forks was a bit daunting...

Any chance of a PR to pull this into master?

**Comment by tipouic** [comment]
No I did not test because I have no hardware but as I have been watching the project for a long time (almost from the beginning), I had the memory of having seen it pass in fork.
I'm not surprised to know that there is a lack of code because there has been a lot of modification on DeviationTx since the code was made.

Good luck for the prortage.

**Comment by JamesHagerman** [comment]
Okay! My Crazyflie 1.0 is flying as expected with my fork! That was fun!

There are still a fairly large number of untested configuration options not exposed via OpenTX's Model configuration pages. Telemetry, alternate modes (X-mode), some other alternate protocols, and some protocol details such as "port" and data rate.

Besides the Telemetry and X-mode, I'm not sure what else is really too useful. I'll have to dig a lot deeper to figure out exactly how those parts of the protocol work.

That said, I have tried to leave TODO comments in the places where I commented out stuff I didn't think I needed quite yet.

Considering my only real goal was to get the CFlie protocol mostly working to fly my existing hardware, I'm happy!

I'll clean up what I have and open a PR.

**Comment by pascallanger** [comment]
PR or not?

**Comment by JamesHagerman** [comment]
Yes! Sorry. I'll submit it today. I've gotta clean up the docs.

**Comment by OpenUAS** [comment]
Thx, appreciated. Any development on clean up, for whatever it would mean ;) ? Have CF2's, multiple different TX's multiple 4in1modules. Any testing config possible. Programming due to too many tasks not so much.

If not one could close this issue?
