### ISSUE TITLE
AFHDS 2A not binding V1.20

### ISSUE THREAD

**Issue by derdoktor667** [pascallanger/DIY-Multiprotocol-TX-Module#162]
....due to some changes to the AFHDS 2A protocol using the A7105 / A7106 chipset I´m not able to bind to my receiver as IBUS-PPM or IBUS-PWM. Didn´t try the SBUS option or direct PPM. The Receiver is a IA6B clone ...just a quick note ...now I will see what´s different with it since last version

.....by the way, I´m making some progress in binding my Hubsan H122D using the Hubsan H107 Option ...by "default" the quad will start "beeping" for a bind to a TX ....with some adaptions it will not start beeping but it never completes a bind

....best regards

derdoktor667

**Comment by snaewe** [comment]
Any more news on the AFHDS 2A problem? I'm trying to bind to a Turnigy ia10 receiver with no luck.

**Comment by pascallanger** [comment]
Is it only an issue with the latest version? Have you tested to roll back a couple of commits to see if it works?

**Comment by snaewe** [comment]
I did a quick test by checking out version 1.2.0 (git tag). That used once...but then again it didn't.
I'll try that again and will try other/newer versions.

FWIW: I use the IRangeX IRX4+ in a Taranis X9d+ (latest OpenTX)

**Comment by pascallanger** [comment]
A lot of people have been using this protocol succesfully. So if you can't get it to work with any version then you have an issue on your side.
The only thing I'm wondering is if I've broken it during the last merge (or 2), I can't remember really when but afhsd2a has been touched in the last few updates.

**Comment by thjubeck** [comment]
Having the same issue with the new version. I reverted to an older known working version and everything bound correctly so there is something up in the new version.

**Comment by snaewe** [comment]
News!
After checking some commits between v1.2.0 (f3838ae ("Prepare for release of a stable version", 2017-12-20)) and master (07adeaf ("Adding CFlie protocol (#159)", 2018-05-04)) I would say that commit 8906c85 ("Few modifications", 2018-05-04) is the culprit.
If I checkout master and do 'git revert 8906c85' (+ compile and upload) I can bind to my Turnigy ia10 receiver.
Unfortunately I'm not capable of fixing (or even understanding...) the problem that the mentioned commit introduces. Maybe someone else can.

**Comment by komar007** [comment]
I am experiencing a similar issue.
I was trying to bind my Taranis Q X7 with OpenTX 2.21 (cca71808) to the Eachine AIOF3_BRUSHED FC (FlySky version) using iRangeX IRX4 Plus (from Banggood) with firmware version v1.2.0-82-g07adeaf.

The receiver stopped blinking fast and started blinking slowly when I entered bind mode on the Taranis, as expected. But then after radio restart, it continued blinking instead of going into continuous which would signify signal reception. The settings on the TX were:
Mode: MULT FS 2A
Subtype: PPM,IBUS.

I confirm that reverting 8906c85 fixes the issue for me. After reflashing, the RX LED is continuously on and the model works correctly.

**Comment by thjubeck** [comment]
Any updates on this issue? I would like to go the new version but currently it is not possible because of the issue.

**Comment by jchris001** [comment]
Hi, I confirm too, revert  8906c85 fixes the issue.

But i dont know why...

**Comment by pascallanger** [comment]
I'll work on it next week

**Comment by hayataro** [comment]
I have similar issue. I have 1.2.0.18 on HORUS X12S and works great, but 1.2.0.20 on MPM Lite and XLite cannot bind to FS-iA6B AFHDS 2A.
Aant to try patched version but how to compile?

**Comment by fabioeh** [comment]
I got a similar issue. Have 1.2.0.20 on MPM Lite and XLite cannot bind to FS-iA6B AFHDS 2A.
Bind mode continuously beeps. Have to turn off the transmitter to recover.

**Comment by pascallanger** [comment]
Fixed in last commit.

**Comment by jchris001** [comment]
Thanks a lot

**Comment by derdoktor667** [comment]
...sorry, but for me it is still not fixed in 1.22 ....I have to say, I´m using a DIY module with some harvested TX chips, an Arduino Nano (Clone CH340) on a redisigned PCB ...and I can´t figure out why the AFHDS 2A not binding by inspecting the code

....and since the "Nano" changed the bootloader (328P/OldBootloader) I can´t be sure there are no issues caused by my redesign or foo

...and thank you for your hard work ...I never understood, why there´s no "one to rule them all" ;)

...best regards

derdoktor667

**Comment by pascallanger** [comment]
What I can tell you is that I'be tested the latest version and it works fine.
So I would assume this is your module.

**Comment by derdoktor667** [comment]
...so, one or two questions left: ...what AVR based module are you using for development at the moment??? ...and what module to buy if I want to use a "supported" version?
