### ISSUE TITLE
AFHDS 2A problem

### ISSUE THREAD

**Issue by jeanbat2** [pascallanger/DIY-Multiprotocol-TX-Module#167]
Hello, 

I'm using a iA6 receiver (AFHDS 2A) and it worked before, I did several flights with, but now I tried to bind a second receiver, and now neither of them work, the receiver led from a fast blink to a slow blink, but do not bind... Is it a rx_num issue?

Thank you for any help

**Comment by pascallanger** [comment]
You need to affect a different rx_num per receiver otherwise you will loose the bind each time.
Have you done any upgrade to the latest code in the middle?

**Comment by pascallanger** [comment]
Please try the latest version.
