### ISSUE TITLE
Bootloader Flash Fails

### ISSUE THREAD

**Issue by thjubeck** [pascallanger/DIY-Multiprotocol-TX-Module#168]
Hey, 

I think the structure for the bootloader is wrong. On the latest version of arduino it cannot find the bootloader files. 

Used the stm flasher program to get around this issue for now.

**Comment by benlye** [comment]
Did you choose either Flash via USB or Flash from TX before trying to burn the bootloader? If you had flash via serial selected you cannot flash the bootloader.

**Comment by thjubeck** [comment]
Thanks that was the problem. I still had that selected because I was flashing with the FTDI. On a side note if you flash with the stm flasher you have to manually power it on just as it starts to flash in order to get the dfu mode to reset.
