### ISSUE TITLE
Bug telemetry in FrSkyX_cc2500.ino

### ISSUE THREAD

**Issue by tipouic** [pascallanger/DIY-Multiprotocol-TX-Module#17]
Il manque une vérification de présence de la télémétrie dans le protocole FrSkyX car si on compile sans la télémétrie, la variable "telemetry_lost" (ligne 296) n'est pas connue.
Il faudrait transformer cette ligne en "
#if defined TELEMETRY
	telemetry_lost=1;
#endif
"

**Comment by pascallanger** [comment]
This is fixed.
Pascal

**Comment by tipouic** [comment]
Il y a toujours le problème de déclaration pour la variable. Il suffirai juste de sortir la déclaration du teste de présence de la télémètrie (ligne 153 multiprotocol.ino).
