### ISSUE TITLE
align trex100 and quadcopter

### ISSUE THREAD

**Issue by FXDUTRUCROSSET** [pascallanger/DIY-Multiprotocol-TX-Module#178]
does anyone know which protocol is used by Align radios?
i have a trex100 and align quadcopter which has a cheap transmitter that should be replaced by one of our regular programmable transmitters but need protocol to select or identified and duplicated

**Comment by pascallanger** [comment]
The TREX 100 is using the FLYSKY protocol. (it's a wltoys TX and wondering if the heli is not also a rebranded wtoys).
