### ISSUE TITLE
Can´t use CX-10 Blue PCB

### ISSUE THREAD

**Issue by FPV-Rover** [pascallanger/DIY-Multiprotocol-TX-Module#186]
Hey,

i tried to bind the X-Lite MPM Module with my CX-10 Blue PCB but it always stucks on V1.2.0.31 Binding. All the other PCB Versions are working (i click bind, it flashes Binding V1.2.0.31, and its prepared)

Taranis X-Lite is on the latest FW and the MPM Module is also flashed to the newest Frimware.

Has anyone the same problem and found a fix?

Thanks
Moe

**Comment by schwabe** [comment]
Do you really have cx10 blue? Binding on these only works if the quad responds. Otherwise it is stuck in binding as you observe.

**Comment by clementleger** [comment]
This can probably be related to the same problem as this one: https://github.com/goebish/nrf24_multipro/issues/40

ie: There is a new CX10 protocol in the wild !

**Comment by goebish** [comment]
There are several new CX10 protocols in the wild, looks like each new batch is using different hardware / protocol ;)

**Comment by Indygoman12** [comment]
Thank you very much for the response I will let the people whom are asking... Too bad I spent 50bucks on one and can't use it now.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Indygoman12** [comment]
I got it from banggood so who knows do you have any recomadation.. How do we know what is compatible to what?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
