### ISSUE TITLE
Update MPM Lite

### ISSUE THREAD

**Issue by amfiber** [pascallanger/DIY-Multiprotocol-TX-Module#187]
Can someone Please tell me A easy way to update this module. I read the general part but I worry to brick the module

**Comment by pascallanger** [comment]
First, you can't brick a module as there is always the option to start in Boot0.
Second, the MPM Lite module already comes with the bootloader installed so you just need to plug it and upload the new firmware. All this is explained in details here: https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/docs/Compiling_STM32.md#compiling-and-programming-stm32

**Comment by Dimonira** [comment]
You also need to flash the X-Lite transmitter firmware with multimodule build options.

**Comment by amfiber** [comment]
Will try thanks

**Comment by amfiber** [comment]
I cannot get it to pop-up by com port
Only com 6

**Comment by pascallanger** [comment]
Have you installed the drivers?

**Comment by amfiber** [comment]
Yes

**Comment by pascallanger** [comment]
So what do you see in the device manager when you plug the module?

**Comment by amfiber** [comment]
Sorry Windows was restarting
Serial USB com 6

**Comment by pascallanger** [comment]
So you are all good just upload.

**Comment by amfiber** [comment]
Error you must select One of these boards

**Comment by pascallanger** [comment]
The one given in the documentation: https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/docs/Arduino_IDE_Boards.md

**Comment by amfiber** [comment]
Now I see com
Com 6 multi 4-1 stm32..... 👍🏻

**Comment by pascallanger** [comment]
Please follow the doc line by line and you will see that it works easily:
https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/docs/Compiling_STM32.md#compiling-and-programming-stm32

**Comment by amfiber** [comment]
Yessss. Missed a step😬😗
But it works now 👍🏻
Can I make a small donation with Paypal?

**Comment by pascallanger** [comment]
Always welcome :-)
https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/docs/Donations.md

**Comment by amfiber** [comment]
Keep up the good work and many thanks for helping me out
