### ISSUE TITLE
Wrong value in comment or in code

### ISSUE THREAD

**Issue by Spider84** [pascallanger/DIY-Multiprotocol-TX-Module#190]
https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/51ba7cf75cf0a932d558510b6ff0d1dde11cccab/Multiprotocol/Telemetry.ino#L789
Realy?
20230f00  is 0x20 0x23 0x0F but in code **0x02** 0x23 0x0F

**Comment by pascallanger** [comment]
Yes really... The dummy number was seen as too big so it has been decreased. It's dummy so it can be anything...
