### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by Super-Tom** [pascallanger/DIY-Multiprotocol-TX-Module#194]
I'm trying to compile using the Arduino IDE and upload to a Vantac MPM Lite via USB.

I've followed the Compiling & Programming Guide (STM32) but i'm getting compile errors...

> Arduino: 1.8.7 (Windows 10), Board: "Multi 4-in-1 (STM32F103CB), Auto Detect (USB or Serial)"
> 
> In file included from sketch\Multiprotocol.ino.cpp:1:0:
> 
> C:\Users\Toms\AppData\Local\Arduino15\packages\multi4in1\hardware\STM32F1\1.0.9\cores\maple/Arduino.h:32:6: error: previous declaration of 'void setup()' with 'C++' linkage
> 
>  void setup();
> 
>       ^
> 
> Multiprotocol:220:12: error: conflicts with new declaration with 'C' linkage
> 
>  void setup()
> 
>             ^
> 
> In file included from sketch\Multiprotocol.ino.cpp:1:0:
> 
> C:\Users\Toms\AppData\Local\Arduino15\packages\multi4in1\hardware\STM32F1\1.0.9\cores\maple/Arduino.h:33:6: error: previous declaration of 'void loop()' with 'C++' linkage
> 
>  void loop();
> 
>       ^
> 
> Multiprotocol:495:11: error: conflicts with new declaration with 'C' linkage
> 
>  void loop()
> 
>            ^
> 
> exit status 1
> conflicts with new declaration with 'C' linkage
> 
> This report would have more information with
> "Show verbose output during compilation"
> option enabled in File -> Preferences.

**Comment by pascallanger** [comment]
You need to use the recommended Arduino version 1.8.5 not 1.8.7 as indicated in the doc you outlined: https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/docs/Compiling_STM32.md#install-the-arduino-ide
