### ISSUE TITLE
Add pinout for FRsky DHT module (stm32f1)

### ISSUE THREAD

**Issue by DEvil0000** [pascallanger/DIY-Multiprotocol-TX-Module#195]
The FRsky DHT module is using a STM32f1 and a cc2500 so the current code should run on the hardware and would allow FRskyX on it. It may also increase the range since the transmitter is sending with low power.
The only missing pice of the puzzle is the pin assignment

**Comment by pascallanger** [comment]
I'm not sure what you are looking after here... I don't have a FrSky DHT module to look at for the pinout.
If you have one then help yourself isn't it?

**Comment by DEvil0000** [comment]
I am more a software guy so figuring out the pin assignment is trouble for me but I will try. I just opened the issue here in case someone did that already.

**Comment by pascallanger** [comment]
No news...
