### ISSUE TITLE
support for the VISUO XS809HW ?

### ISSUE THREAD

**Issue by manotroll** [pascallanger/DIY-Multiprotocol-TX-Module#202]
would it be possible to add support for the VISUO XS809HW?

**Comment by pascallanger** [comment]
Double post with rcgroups...

**Comment by manotroll** [comment]
how to make a test image available?

**Comment by pascallanger** [comment]
You haven't answered any questions I've asked on rcgroups... Start from there may be?

**Comment by manotroll** [comment]
I was not notified by the forum I'm sorry for this
https://www.deviationtx.com/forum/protocol-development/7404-visuo-xs809h-w-hd-g-bayang-x16-ah-capture?start=20#71864
