### ISSUE TITLE
Devo Protocol always auto-binding.

### ISSUE THREAD

**Issue by sloped-soarer** [pascallanger/DIY-Multiprotocol-TX-Module#208]
Hey Guys.
I have an OrangeRX module with the green PCB. When i select Devo as the protocol, regardless of the bind and auto-bind flags sent via the serial protocol, a bind is always initiated.
The Devo protocol code itself seems like it has the ability to not auto-bind based on a variable named "option". 

Should an "option" be sent in the serial protocol even though we already have the auto-bind flag ?.

Please advise an amend as necessary.

Seasons Greetings.

**Comment by pascallanger** [comment]
The autobind flag main function is to launch a bind each time you either power up the TX or if enable_bind_channel is on, it waits for the channel 16 by default to launch a bind. This is not what you are looking for.
As mentionned in the documentation: https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/Protocols_Details.md#devo---7 you must follow a bind process which involves changing the option value from 0 to 1. Option is available through the radio GUI on ersky9X and OpenTX but can have different names based on what the devs have choosed to implement but you should be able to pinpoint it quite easily...
Pascal
