### ISSUE TITLE
JJRC H31

### ISSUE THREAD

**Issue by 500mania** [pascallanger/DIY-Multiprotocol-TX-Module#214]
Witch protocol may be used for jjrc h311
![672a417c-9970-42bd-b215-974f58c130bc](https://user-images.githubusercontent.com/35607970/53572900-9becb980-3b6c-11e9-8d30-cec83b82f6d6.jpg)

**Comment by pascallanger** [comment]
Is it H311(text) or H31 (title)?
If H31, it's not supported since we never had a good SPI dump: https://www.deviationtx.com/forum/protocol-development/6663-protocol-for-jjrc-h31?start=40
Pascal

**Comment by pascallanger** [comment]
People are changing the board on this quad: https://youtu.be/-OuLu8bkGkQ
https://www.amazon.com/gp/product/B07BBN1S62/ref=as_li_qf_asin_il_tl?ie=UTF8&tag=jasonboyle-20&creative=9325&linkCode=as2&creativeASIN=B07BBN1S62&linkId=1d634bfb6f5642bbd7df19780463d244
Pascal
