### ISSUE TITLE
Sub protocol E016H doesn't work

### ISSUE THREAD

**Issue by goebish** [pascallanger/DIY-Multiprotocol-TX-Module#217]
https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/ae4ee9061d06b733e6acbfd595c2b2c3d81d0fb7/Multiprotocol/E01X_nrf24l01.ino#L229
it should be XN297_WritePayload for E016H
Also, Aileron & Rudder need to be reversed

**Comment by pascallanger** [comment]
Done.
