### ISSUE TITLE
No telemetry bugs 3 mini

### ISSUE THREAD

**Issue by MileHighFly2506** [pascallanger/DIY-Multiprotocol-TX-Module#222]
Hello. I'm using a Jumper t12 and my bugs 3 mini flies great except that I get no telemetry data on the tx. RSSI value is 0. I'm running multi version 1.2.1.29 and JumperTx version 2.2.3. When I look at the model stats page I see Tlm RX err 2. Any help would be appreciated. Thank you!

**Comment by pascallanger** [comment]
Telemetry is working if you update the module to the latest version 1.2.1.38.
PAscal

**Comment by MileHighFly2506** [comment]
Working on that now. I'll let you know if I get it going. It's snowing here
so probably tomorrow. Thank you for your time.

**Comment by MileHighFly2506** [comment]
All working now! Thanks again!

**Comment by pascallanger** [comment]
Great!
