### ISSUE TITLE
Able to bind with Flysky fsi6-rx but with only 4 channels working

### ISSUE THREAD

**Issue by transmech** [pascallanger/DIY-Multiprotocol-TX-Module#24]
Hello,
I currently have installed the latest and greatest firmware on a DIY multiprotocol board inside a taranis running Opentx Taranis plus  V 2.1.9 and I am able to bind to the above receiver but only get 4 channels but   no aux channels. Verified the channels were on in the Taranis setttings and double checked the Config file and didn't see anything out of place. Any ideas?

**Comment by pascallanger** [comment]
I'm not able to reproduce the issue. Please ask on the forum so Taranis users can help you: https://www.rcgroups.com/forums/showthread.php?2165676-DIY-Multiprotocol-TX-Module/page435
Pascal
