### ISSUE TITLE
NRF24L01 Receiver

### ISSUE THREAD

**Issue by fbiego** [pascallanger/DIY-Multiprotocol-TX-Module#241]
Is it possible to decode and receive signals from the transmitter to Arduino using the nrf24l01 module so that I can control projects with one transmitter?

The transmitter I have is based on XNS1042CV
![txd-3s_tx](https://user-images.githubusercontent.com/45796740/60142180-5f9b3400-97c1-11e9-8cf3-b97dad7ed725.png)

**Comment by pascallanger** [comment]
If you have a STM32 4in1 module then yes you can use the protocol X297DUMP to see what your radio/model is sending over the air and try to decode here.
Pascal
