### ISSUE TITLE
Function convert_channel_16b_nolimit()

### ISSUE THREAD

**Issue by splotz90** [pascallanger/DIY-Multiprotocol-TX-Module#242]
The function `convert_channel_16b_nolimit()` is implemented as follows:

```
int16_t convert_channel_16b_nolimit(uint8_t num, int16_t min, int16_t max)
{
	int32_t val=Channel_data[num];				// 0<->2047
	val=(val-CHANNEL_MIN_100)*(max-min)/(CHANNEL_MAX_100-CHANNEL_MIN_100)+min;
	return (uint16_t)val;
}
```

Since `Channel_data[num]` can take values from 0 - 2047, isn't it better to use `CHANNEL_MIN_125` instead of `CHANNEL_MIN_100` and `CHANNEL_MAX_125` instead of `CHANNEL_MAX_100`?

Fixed version:

```
int16_t convert_channel_16b_nolimit(uint8_t num, int16_t min, int16_t max)
{
	int32_t val=Channel_data[num];				// 0<->2047
	val=(val-CHANNEL_MIN_125)*(max-min)/(CHANNEL_MAX_125-CHANNEL_MIN_125)+min;
	return (uint16_t)val;
}
```

**Comment by pascallanger** [comment]
100 is correct here since min and max are related to 100%. If you set extended limits on the radio, you will go over 100 and therefore the output as well.
