### ISSUE TITLE
Cannot turn off green LED for Jumper 4n1 Module

### ISSUE THREAD

**Issue by ErikEdwards01** [pascallanger/DIY-Multiprotocol-TX-Module#248]
I recently got a Jumper 4n1 with the dial (0-8) on the back. Documentation says hold bind on 0 when turned on to swap from 9-15 (Green LED on) to 0-8 (Green LED off) however that doesn't work. It only makes the transmitter go into bind mode (Red LED blinking). 
The documentation on GH says green led is power on, nothing about the swapping number sets as I'm guessing the stock one is a 16 position. Is this a per module setting or is it universal across all modules that do not have the 16 position switch and only the 8? The banks work fine on channel 7/15 (whichever one it is) and I can select the variants, I just cant select the main brands like Frsky and FlySky.
![IMG_20190729_104051623](https://user-images.githubusercontent.com/42040478/62144241-769cdc80-b2bf-11e9-90d1-fb2b0c8a6aff.jpg)
![IMG_20190729_122227634](https://user-images.githubusercontent.com/42040478/62144242-769cdc80-b2bf-11e9-92d6-b12f4ceeaf08.jpg)

**Comment by pascallanger** [comment]
The dial has 16 positions (0..15) and not only 8.
Whatever the Jumper doc says, it's not how the module operates...
The bank switching is explained here: https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/Protocols_Details.md#protocol-selection-in-ppm-mode
The LEDs are explained here: https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/docs/Troubleshooting.md#led-status
You should update the firmware of your module and select the protocols you want to access (including banks if you need them) in the _config.h file as explained here: https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/docs/Compiling_STM32.md
