### ISSUE TITLE
Prot. Invalid. on Open TX Nightly Build N63

### ISSUE THREAD

**Issue by Talha909** [pascallanger/DIY-Multiprotocol-TX-Module#251]
I have xlite Pro. I have installed the Open TX N62. In N62 version my multi module works good and come online but when I updated the Open Tx N63. My Multi Module goes offline and and in setup screen it gave me the fallowing status  Prot. invalid.  I do this 4 times. And result was always same

**Comment by pascallanger** [comment]
Please open the case with the OpenTX team.
