### ISSUE TITLE
Module continues to transmit when no PPM signal

### ISSUE THREAD

**Issue by soligen2010** [pascallanger/DIY-Multiprotocol-TX-Module#26]
Looks to me like the module continues to transmit even if there is not PPM (or serial) signal coming it.  I think it would be good to stop transmitting in this case so that a model will Failsafe, or if the TX internal protocol is being used and the TX is not outputting anything to the module, then the module is not using up bandwidth.

 I can't figure out how to submit a pull request for just one commit in my fork, so here is a link to Multiprotocol.ino that I made.

[https://github.com/soligen2010/DIY-Multiprotocol-TX-Module/commit/86017439cade967a0acba45dc1d57e5c0c07f055](https://github.com/soligen2010/DIY-Multiprotocol-TX-Module/commit/86017439cade967a0acba45dc1d57e5c0c07f055)

**Comment by pascallanger** [comment]
Yep I've introduced lately the information that there is no incoming signal with the end game to stop transmitting but I got side tracked.
You should use the existing test IS_INPUT_SIGNAL_on.
Anyaway I've implemented it now in my new version but not pushed yet.
Thanks, Pascal
