### ISSUE TITLE
I think SerialControl should be volatile

### ISSUE THREAD

**Issue by soligen2010** [pascallanger/DIY-Multiprotocol-TX-Module#27]
I was just loking through the code, learning, and I noticed that SerialControl was used while in interrupts, but was not volatile.  I have not experienced and issue, but my understanding is that to be safe, global variables used in interrupts should be volatile

I can't figure out how to submit a pull request for just one commit in my fork, so here is a link to Telemetry.ino changes that I made.

[https://github.com/soligen2010/DIY-Multiprotocol-TX-Module/commit/88cb063647935f35428c126f275653aabbdebc5b](https://github.com/soligen2010/DIY-Multiprotocol-TX-Module/commit/88cb063647935f35428c126f275653aabbdebc5b)

**Comment by pascallanger** [comment]
Ok changed to volatile but for the full structure instead. Available in next push.
Pascal
