### ISSUE TITLE
Create Support for Spektrum DSMR protocol 

### ISSUE THREAD

**Issue by shorty707** [pascallanger/DIY-Multiprotocol-TX-Module#277]
Spektrum surface receivers use DSMR Variant of DSM protocol and cannot bind with 4in1 atm

**Comment by pascallanger** [comment]
Are you able to provide on the TX SPI dumps or mail a TX+RX so I can have a look?

**Comment by shorty707** [comment]
Don't really know how to do that.
Any guide how to do that?

Here is a Spektrum person telling a little about the background with 5.5ms resolution etc
https://www.rcgroups.com/forums/showthread.php?3003835-Spektrum-air-and-surface-compatibility

**Comment by pascallanger** [comment]
Your RCG link is not helping as there is no technical details about the protocol.
You need to solder a couple of wires (6 or so) in your DSMR transmitter and connect to it a logic anlyzer like this one https://www.ebay.fr/itm/USB-Logic-Analyzer-Device-Set-USB-Cable-24MHz-8-Channel-24MHz-for-Saleae-ARM/132431128540?hash=item1ed582a7dc:g:aqcAAOSwywRaLo3e.
Then from your PC you need to do a bunch of dumps to see if we can figure out how the protocol works.
You'll surely have to do the same on the RX side (soldering wires) so we can see the hopping frequencies based on the TX ID.

**Comment by sangyue** [comment]
You can have a try with below aftermarket DSMR receivers develop by DasMikro. It works smoothly with Spektrum latest transmitters in DSMR and SLT protocol. It is a 5 channel version and function is similar to SR515.
[https://dasmikro.com/product/spektrum-compatible-product-dsk-515n-5ch-dsmr-and-slt-dual-protocol-antenna-free-receiver/](url)
