### ISSUE TITLE
internal module T16 no more sub protocols fr corona such as v1 v2 or fd3  

### ISSUE THREAD

**Issue by FXDUTRUCROSSET** [pascallanger/DIY-Multiprotocol-TX-Module#294]
multi-stm-opentx-taer-inv-1.3.0.44.bin
no way to bind internal module of t16 under opentx 2.3 nighlies  with this version
the 3 sub protocols disepeared from model menu  and no way to bin with corona DSSSV2 on internal module
same revision of multistm on the external modules allows to bind corona v2 and appears in the menu

**Comment by 3djc** [comment]
Not happening here

![image](https://user-images.githubusercontent.com/5167938/69482422-6505b480-0e1b-11ea-9c79-2612da8e289a.png)

**Comment by FXDUTRUCROSSET** [comment]
On opentx 48 it was not active, since I've downloaded nightlife 52 it came back
