### ISSUE TITLE
enhacement request : memorize fine frequency tuning for each protocol

### ISSUE THREAD

**Issue by FXDUTRUCROSSET** [pascallanger/DIY-Multiprotocol-TX-Module#295]
i know we can set up by arduino ide multiprotocol for each protocol that needs to, the fine frequency once for all protocol but would it be possible directly on the radio to set up one for all for each protocol, for instance for all frsky models, for all corona, all ...uzw?

wonderfull job, i'm impressed every week
i succeded to link as a slave my mega2560 based radios, sky9x, frskyxlite to T16 master, no need to install the bluetooth on t16 for that purpose
just a big drift in channels centers and full course between slave and master but very promising.
thanks Pascal and the team.

**Comment by pascallanger** [comment]
I feel this is a request for OpenTX...
