### ISSUE TITLE
NRF_CE pin

### ISSUE THREAD

**Issue by BenjaminRenz** [pascallanger/DIY-Multiprotocol-TX-Module#298]
Hi,

I'm trying to use the module with an walkera devo 12s and want to use the stm32 only to switch the antenna select pins PE1,PE2 according to the last active xx_CS for the corresponding module.
I have soldered wires to the modules four xxx_CS pins, the CYRF_RST pin.

But the module seems to have an extra pin called "NRF_CE" which is connected to PA_13 on the stm32. Is this pin used or can I leave it floating? I could not find any definition of PA_13 in the [pins.h file](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/Multiprotocol/Pins.h) and the only thing related I was able to find are the [following lines](	https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/Multiprotocol/Pins.h#L252) in pins.h:
```
	#define NRF_CE_on
	#define NRF_CE_off
```

So I would guess that that pin is on high impedance?

Greetings
Benjamin

**Comment by pascallanger** [comment]
NRF_CE has a pull up resistance. So you either don't touch it or set it to high.
Pascal
