### ISSUE TITLE
Optimisation du code PPM

### ISSUE THREAD

**Issue by tipouic** [pascallanger/DIY-Multiprotocol-TX-Module#3]
Bonjours, bon travail que je suis pour ma TARANIS.
J'ai juste remarqué un petit défaut dans la boucle loop lors de la copie des valeurs de servos, tu refait à chaque fois une update des flags (ligne210).
Pour info, tu as des erreurs dans le fichier "telemetry.h" quand on déactive le protocole FRSKY ou HUBSAN; il te manque juste une détection pour savoir si les personnes veulent le protocole ou pas.

**Comment by pascallanger** [comment]
Bonjour Tipiouc,
Merci pour ta remarque sur l'update des flags, je suis passé à côté... C'est corrigé.
Je vais regarder pour que l'on puisse commenter FRSKY/FRSKYX/HUBSAN sans qu'il y ait d'erreurs de compilation.
Merci, Pascal
