### ISSUE TITLE
Adjust or increase the transmitting power for HoTT

### ISSUE THREAD

**Issue by Flying-Bolt** [pascallanger/DIY-Multiprotocol-TX-Module#302]
Is it possible to increase or adjust the transmitting power of 1mW for HoTT

**Comment by pascallanger** [comment]
You can change the power settings but at a global level per RF component in multiprotocol.h:
https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/0008633d6ef844a1bec424c62ba4e7ed2f956207/Multiprotocol/Multiprotocol.h#L537
```
#define CC2500_HIGH_POWER	CC2500_POWER_17
#define CC2500_LOW_POWER	CC2500_POWER_13
```
