### ISSUE TITLE
P_LOW, P_HIGH

### ISSUE THREAD

**Issue by robthomson** [pascallanger/DIY-Multiprotocol-TX-Module#309]
Hello

I was wondering.. is there any option to go lower the P_LOW in PPM mode?

In-fact.. what mw output is being used for P_LOW?

Essentially.. I only need 1-2m range as the tx will be strapped to my head for a wireless head tracker.

How can I get this as low as possible?

Rob

**Comment by robthomson** [comment]
Actually.. think I can just change to value I need here:

#define NRF_HIGH_POWER		NRF_POWER_3
#define	NRF_LOW_POWER		NRF_POWER_1
#define	NRF_RANGE_POWER		NRF_POWER_0
#define	NRF_BIND_POWER		NRF_POWER_0

**Comment by pascallanger** [comment]
Yes that's where you change the power levels which needs to be done for each RF component.
