### ISSUE TITLE
Binding WLTOYS V119S heli

### ISSUE THREAD

**Issue by grumbles1957** [pascallanger/DIY-Multiprotocol-TX-Module#310]
I have tried to bind my V119s heli to my Taranis tried the fine tuning but no avail any ideas

**Comment by pascallanger** [comment]
I assume you are taking about a v911s and not v119s...
There is already an issue #301 open with a work around: https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/issues/301

**Comment by grumbles1957** [comment]
Thank you
