### ISSUE TITLE
Taranis x9 Lite SD card seems to cause iR4X to crash

### ISSUE THREAD

**Issue by Sn0wmonkey** [pascallanger/DIY-Multiprotocol-TX-Module#313]
Hi again, amazing software thank you. I upgraded my iR4X lite to the latest firmware and am having issues where the module will just crash and lose all power I've noticed that if I take the SD card out of my Taranis X9 it sometimes works fine.

I've added the multi.txt to the root of the sd card but no joy and tried to comment out all the protocols I'm not using but no joy.

Open TX 2.3.4
Multiprotocol 1.3.0.44

**Comment by pascallanger** [comment]
It's a known issue where the bootloader which is being shipped is either really old or has been modified: https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/issues/237
At the bottom of the page above you'll find a document on how to do the upgrade which I'm linking here: https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/files/3594850/Vantac.MPM.Lite.Red.LED.Issue.docx.
Pascal
