### ISSUE TITLE
E010 does not work after flashing

### ISSUE THREAD

**Issue by Tlapoun** [pascallanger/DIY-Multiprotocol-TX-Module#318]
Hi, my Eachine E010 (MJXq, subtype E010) stop working after I flashed MPM from 1.3.0.47 to 1.3.0.53. Reflash back works correctly. Something bad in new version

**Comment by benlye** [comment]
There were changes to E010 in the latest version.  You need to use the Option Value (RF Fine Tuning).

https://www.multi-module.org/using-the-module/protocol-details/mjxq#4-e010
