### ISSUE TITLE
Is FHSS Axion will be added?

### ISSUE THREAD

**Issue by Cedric-Lag** [pascallanger/DIY-Multiprotocol-TX-Module#325]
Is FHSS Axion will be added? for example can we replace transmitter  AX-4CT 2,4Ghz FHSS Axion Link by radio with multi-protocol. Thank you so much.

**Comment by pascallanger** [comment]
This protocol could be supported if you are ready to do some SPI dumps and spend a couple of days/weeks on it or send me the hardware (TX+RX).

**Comment by pascallanger** [comment]
No answer. Closing this request.

**Comment by dmrlawson** [comment]
If anyone else ends up here: the standard FlySky protocol works for me with [this](https://www.1001modelkits.co.uk/rc-planes/132178-axion-rc-0900ax-00130-02-at-6-texan-nfl-2-4g--5413911146371.html) and presumably other Axion-rc receivers
