### ISSUE TITLE
Dsm2 rx mode 

### ISSUE THREAD

**Issue by robthomson** [pascallanger/DIY-Multiprotocol-TX-Module#327]
Hey..

Are there any plans to make a dsm2 receiver mode?

Rob

**Comment by pascallanger** [comment]
Hi,
Yes but not in the near future.
Pascal

**Comment by pascallanger** [comment]
Implemented in Multi v1.3.0.99

**Comment by robthomson** [comment]
OMG! You have made me so happy!

This now means I can shrink my wireless head tracker by about 80% in size!!!
