### ISSUE TITLE
rx_tx_addr array not set in PPM mode

### ISSUE THREAD

**Issue by soligen2010** [pascallanger/DIY-Multiprotocol-TX-Module#33]
Serial is setting this, but there isnt a call to set_rx_tx_addr in the PPM initialization.  The MProtocol_id is getting set, but not the rx_tx_addr.  

BTW, are you OK with me opening an issue when what I have is most likely just questions/clarification, or is there another place you would like to use for communication when it isn't an issue?

Thanks

Dennis

**Comment by pascallanger** [comment]
I've corrected the PPM ID bug. Thanks for finding it and letting me know.

Yes it's fine to open issues. It's just that the serial conversation was completed at least I thought.

Pascal
