### ISSUE TITLE
Range check in PPM mode

### ISSUE THREAD

**Issue by Eurylokhos** [pascallanger/DIY-Multiprotocol-TX-Module#330]
There doesn’t seem to be a way to do a range check when operating in PPM mode. I’ve searched the documentation and can only see how in serial mode. Can this be implemented? Maybe pressing the bind button when powered on will activate a range test mode?

**Comment by pascallanger** [comment]
The bind button is already used multiple times so I can't do that...
What I can do is to add a flag for range check in the PPM table so that you can create an entry in the ppm table with it activated that you can access through a position on the dial.
PAscal

**Comment by Eurylokhos** [comment]
Thank you, that would work well.
