### ISSUE TITLE
invalid protocol on X12S (dev. edition) OpenTX 2.3.5

### ISSUE THREAD

**Issue by X12S** [pascallanger/DIY-Multiprotocol-TX-Module#335]
Hi I need help in Troubleshooting the following Issue:
Config:
X12S developer Edition with OpenTX 2.3.5 (opentx-x12s-eu-lua-pcbdev-ppmus-de-2.3.5)
IPX 4 with LEDs retrofited running"multi-stm-opentx-aetr-inv-v1.3.0.53" or V1.3.0.47 for serial debug)

The Multimodul does not work and reports "Protocol invalid"  Same modul works in my Taranis Plus (2.3.5) while in the X12S my R9 module works just fine. I have a second multi modue that shows exactly the same behaviour in both transmitters.

Serial debug shows in the X12S:
Multiprotocol version: 1.3.0.47
Protocol selection switch reads as 0
Using bank 0
Read ID from EEPROM
Module Id: 715afc5d
Init complete

My Taranis shows after this more debug info on the selcted protocol e.g.:
Multiprotocol version: 1.3.0.47
Protocol selection switch reads as 0
Using bank 0
Read ID from EEPROM
Module Id: 715afc5d
Init complete
Protocol selected: 1, sub proto 0, rxnum 0, option 0
Proto=FlySky, nbr_sub=5, Sub=Std, Opt=0

I assume there is some kind of communication problem between the transmitter and the module.

**Comment by pascallanger** [comment]
I don't have the hardware to troubleshoot. It looks like to be a X12S issue only. Please open an OpenTX issue to get their assistance.
