### ISSUE TITLE
do_version.exe non Win32

### ISSUE THREAD

**Issue by BukmopJL** [pascallanger/DIY-Multiprotocol-TX-Module#337]
do_version.exe not start in Win XP

**Comment by benlye** [comment]
Are you using the latest version of the Multi board?  I'm not currently able to test WinXP, but my expectation is that it *should* work.

**Comment by BukmopJL** [comment]
stm32 v1.1.7

**Comment by pascallanger** [comment]
No more comments, considering diced.
