### ISSUE TITLE
FHSS-1 protocol

### ISSUE THREAD

**Issue by michalelektryk** [pascallanger/DIY-Multiprotocol-TX-Module#338]
I don't see a way to bind to this receiver:

http://www.dsaw-hobbies.com/index.php?dispatch=products.view&product_id=725

After opening tx i see it's based on a7105 so in theory should be compatible

**Comment by pascallanger** [comment]
Unless you provide SPI dumps or ship the hardware (TX+RX), there is little chance it will be supported...

**Comment by pascallanger** [comment]
No proposition to do dumps or send the hardware... Closing the issue.
