### ISSUE TITLE
The 1.3.0.76~1.3.0.81 Can't binding with FRSKY V8 protocol receiver(V8FR-II HV)

### ISSUE THREAD

**Issue by cqmiao** [pascallanger/DIY-Multiprotocol-TX-Module#344]
multi 4in1 TX module to bind with FRSKY V8 protocol receiver(V8FR-II HV) ,
The 1.3.0.53 is OK，but 1.3.0.76~~1.3.0.81 doesn't work~

**Comment by pascallanger** [comment]
Are you sure?
I can't find any change in the code that would explain this...
I don't have a V8 receiver so I can't test myself but I'll ask someone to check.
Pascal

**Comment by MikeBland** [comment]
Just tested a V8FR HV (not-II), and three V4FR receivers. All bound and worked. I had the "Freq" (option) value set to -25, the value I've found works well most of the time. However, only one of the V4FR receivers bound, I changed the Freq value to -45, then they both bound.

Mike

**Comment by pascallanger** [comment]
@MikeBland Could you confirm which version you have been using? I imagine 1.3.0.87.

**Comment by MikeBland** [comment]
1.3.0.86, as that was the version I had on the module.

Mike

**Comment by cqmiao** [comment]
Thanks,I will try again.
