### ISSUE TITLE
redpine protocol can't use 3-pos switch

### ISSUE THREAD

**Issue by kimman1** [pascallanger/DIY-Multiprotocol-TX-Module#346]
I'm compiling and testing redpine. 
It's working perfect but 3 position switch don't work, it just use 2 position in 3 positition switch 
Like postion A, position B, position C it's can use position A and C but position B can't use 
Tested 3-pos with frsky protocol - it's working perfectly 
My module is STM 32 DIY from scratch

**Comment by pascallanger** [comment]
That's how the Redpine protocol works... It sends 4 proportional channels and all the channels from 5 to 16 are on/off. If you need 3 positions you need to combine 2 channels.
