### ISSUE TITLE
turnigy receiver 3860b

### ISSUE THREAD

**Issue by Basti77** [pascallanger/DIY-Multiprotocol-TX-Module#349]
Hello Does anyone know which protocol this receiver uses and if I could use it with the Multi Module? 
that would be great because it's a 3 channel receiver and the broken original control would only have 2 channels.
https://www.worthpoint.com/worthopedia/quanum-vandal-10-4wd-4ghz-turnigy-1799975745
the receiver is still available under other brands.

https://www.ebay.com/itm/2-4GHz-2-Channel-RC-Radio-Transmitter-Receiver-For-Radio-RC-Car-Boat-T3923A-/183702615132

unfortunately I cannot find a data sheet

**Comment by pascallanger** [comment]
That looks lile a Flysky RX.
