### ISSUE TITLE
Support for the FeiYue Eagle FY-RX02 receiver (red board)

### ISSUE THREAD

**Issue by gbraad** [pascallanger/DIY-Multiprotocol-TX-Module#350]
I got hold of a feiyue 4channel receiver (fy-rx02),  which is supposed to be used with the feiyue brushless eagle 3 kit. I do not have a transmitter ATM, but seems to work with the one for FY-06 and FY-07.

I am unable to use it with MPM, but it seems to use bk2451 rfu+mcu

![20200507_231950](https://user-images.githubusercontent.com/1894/81312527-4f2e3800-90b9-11ea-9fe7-289d4c92efff.jpg)
![20200507_231936](https://user-images.githubusercontent.com/1894/81312548-581f0980-90b9-11ea-9a2e-e4bb836864a2.jpg)

**Comment by gbraad** [comment]
It should should work with the FY-TX01 transmitter from the FY03 Eagle3

**Comment by pascallanger** [comment]
Without a TX and RX in my hands there is nothing I can do...
Pascal

**Comment by gbraad** [comment]
A TX is on it's way. What can I do to sniff the signals? I have access to a logic analyzer, but since this is a RF+MCU I think the 'magic' happens inside the 8051 core. Would it be possible to listen in on the signals using a nRF24L01 for instance?

**Comment by pascallanger** [comment]
You can use try to follow this article: http://travisgoodspeed.blogspot.com/2011/02/promiscuity-is-nrf24l01s-duty.html

**Comment by gbraad** [comment]
Transmitter arrived yesterday and works like a treat, and got some additional receivers just in case I fry one (at is seems some can't handle a BEC with 6V as Tamiya ESC do). Anyway, will try to see what i can find over the weekend. Any code that I can run from an Arduino or STM32 would be appreciate as I haven't used the nRF24's low-level that much yet (only did a makecode extension to support them and send some packets back-and-forth).

**Comment by pascallanger** [comment]
You can always start from the XN297Dump protocol.

**Comment by pascallanger** [comment]
Any progress? Should I keep this issue open?

**Comment by gbraad** [comment]
haven't found the time to look into this yet. all the equipment and
tools I have, and assistance from Goebish, ... just some distractions
aren't easy to control.

On Wed, Jun 3, 2020 at 8:24 PM pascallanger <notifications@github.com> wrote:
>
> Any progress? Should I keep this issue open?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 

   Gerard Braad | http://gbraad.nl

   STEM is the source, but BUILD is how you develop!
   [ Better Understanding Involves Learning and Doing ]

**Comment by pascallanger** [comment]
No progress closing this issue...

**Comment by knoopx** [comment]
Hey @pascallanger I'm actually revisiting this, I've got the v1 board and I'm trying to sniff packets using an nrf24. So far I'm struggling with the setup. Anyway if i make some progress I'll let you know.

**Comment by gbraad** [comment]
@knoopx due to the situation I still got the radio here, so if you can share what you have tried it might be possible help can be offered.

**Comment by knoopx** [comment]
@gbraad I've got a logitech unifying dongle and flashed https://github.com/marcnewlin/presentation-clickers firmware. So far I have not been able to identify the TX packets as I did not figure out the rate/channels yet.

**Comment by benlye** [comment]
> @gbraad I've got a logitech unifying dongle and flashed https://github.com/marcnewlin/presentation-clickers firmware. So far I have not been able to identify the TX packets as I did not figure out the rate/channels yet.

Following.  I have a few Logitech unifying receivers laying around and never knew this was something that could be done with them.

**Comment by pascallanger** [comment]
> @gbraad I've got a logitech unifying dongle and flashed https://github.com/marcnewlin/presentation-clickers firmware. So far I have not been able to identify the TX packets as I did not figure out the rate/channels yet.

To find at least one channel, use the multi scanner. You should see a couple of spikes. Take the value of one of them.

**Comment by pascallanger** [comment]
Any progress? may be condiser sending me the hardware...

**Comment by gbraad** [comment]
> Any progress? may be condiser sending me the hardware...

That was the idea. Wanted to give Goebish, but the pandemic prevented
me from traveling to Europe.

**Comment by knoopx** [comment]
![image](https://user-images.githubusercontent.com/100993/111783697-c37d5e80-88ba-11eb-9776-37b791b1355e.png)


![image](https://user-images.githubusercontent.com/100993/111783519-9630b080-88ba-11eb-8a14-5b79b4e458c2.png)

**Comment by pascallanger** [comment]
Have you decoded one packet yet?

**Comment by knoopx** [comment]
Not yet, im still learning how this whole thing works. So far I'm using universal radio hacker with a known protocol. I've been able to capture and demodulate but i have no idea how to make sense of the bitstream. I need to learn about how to decode the bit stream in order to match actual packet bytes. I guess each transceiver has its own way of encoding and modulating data and needs to be figured out? What are your tools of trade?

**Comment by pascallanger** [comment]
> What are your tools of trade?

I'm using MATLAB to receive and decode the signal at a really low level by looking at the phase. Changes in the phase indicates the change from 1<->0, time between two changes gives the bitrate, then using these phase changes I decode the bit stream and rebuild in a table what could be the message. The table contains all variations MSB first, LSB first, inverted and not inverted as well as 7 bit shifts. From all these variations you need to find out which one contains most probably the message. Some stuff guide you through that and usually with 2/3 captures you have a pretty good idea.

If you do a capture on one of the RF freq using GNU radio I can easily look at it and give you the end table.
