### ISSUE TITLE
Flysky RSSI

### ISSUE THREAD

**Issue by pan-sattan** [pascallanger/DIY-Multiprotocol-TX-Module#351]
hi,
on my IRX4 with fw 1.3.0.91 is not possible to see any sensors from flysky X6b reciever... 

am i doing wrong something?? 

![20200509_103237](https://user-images.githubusercontent.com/59567959/81468757-cf4fbd00-91e1-11ea-9b10-1295e13ba112.jpg)
![20200509_103254](https://user-images.githubusercontent.com/59567959/81468760-d70f6180-91e1-11ea-977f-c50eb014afe5.jpg)
![20200509_103629](https://user-images.githubusercontent.com/59567959/81468766-dd9dd900-91e1-11ea-9940-436b617b8e5a.jpg)

**Comment by pascallanger** [comment]
Too close from the receiver may be...

**Comment by pan-sattan** [comment]
now i tried through some walls from oposite rooms and still the same...

**Comment by pascallanger** [comment]
Is it the only AFHDS2A RX that you have?
The only solution would be to go in debug mode and see if the module receives anything from the RX.
Since you have an external iRangeX debug is quite simple, I suggest that you learn how to compile a debug firmware  and launch a debug session. From there, I can guide on some firmware modifications to see what might happen.
Links:
- https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/docs/Compiling_STM32.md#option-3---compiling-and-updating-firmware
- https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/docs/Advanced_Debug.md

**Comment by MRC3742** [comment]
Observation on above pics.
No Multi Sub Protocol is shown for FSky 2A?
Possible version of OpenTX mismatch?

**Comment by pan-sattan** [comment]
i have the latest fw for my taranis from companion software

later i will try debug mode, i have other recievers from fkysky, no one works... it shows me the rssi with flysky i6 radio, so i am sure, that its working

**Comment by pan-sattan** [comment]
![20200509_161541](https://user-images.githubusercontent.com/59567959/81476170-a135a180-9210-11ea-9088-52de685d3847.jpg)

**Comment by pascallanger** [comment]
Really strange this missing line...
Could you try one of the latest 2.3.8 nightly to see if you have the same issue?

**Comment by pan-sattan** [comment]
maybe... which firmware should i use? radio: opentx or ersky? and inverted or not? 
![Screenshot_20200509-162848_Samsung Internet](https://user-images.githubusercontent.com/59567959/81476463-5e74c900-9212-11ea-8326-66d874f7ce65.jpg)

**Comment by pascallanger** [comment]
You are running OpenTX so OpenTX. For the inversion it should be inverted since it's an external module but the radio tells the module.
The problem of the line not showing up is not the module firmware but most likely the radio.
Can you test OpenTX 2.3.8 latet nightly?

**Comment by MRC3742** [comment]
Going with changelogs latest stable version to run on OTX v2.37 would be MPM v1.3.0.87

Starting with version 1.3.0.91 "Protocols appearing in alphabetic order, only available in the latest OpenTX 2.3.8 nightlies (not published yet)" Maybe this is causing the problem?

Using the simulator in 2.3.8 nightlies adds a line "Type" below the "Mode" 
![screenshot_x9d+_20-05-09_11-20-05](https://user-images.githubusercontent.com/26642502/81478309-6a4c9500-91ea-11ea-84e3-0e710aba8738.png)

Link to OTX Nightlies is https://downloads.open-tx.org/2.3/nightlies/companion/ 
Then pick your OS, Install Companion nightly, Redownload firmware and flash to TX.

**Comment by pascallanger** [comment]
@MRC3742 Thanks for helping out ;-)
1.3.0.91 does not need to have 2.3.8, it's only required if you want the protocols in alpha order. But I'm fine to be proven wrong.

**Comment by pan-sattan** [comment]
now it works, looks like that was inverted/noninverted version problem...
thank you for advices, i very appreciate it

**Comment by pascallanger** [comment]
It's not the inversion but the fact that you have selected erskyTX instead of OpenTX...
Pascal

**Comment by pan-sattan** [comment]
yes, i choose wrong fw version, ersky

https://downloads.multi-module.org
