### ISSUE TITLE
FrSky D16 latest firmware support

### ISSUE THREAD

**Issue by avivyam** [pascallanger/DIY-Multiprotocol-TX-Module#352]
Hi, 
Jumper internal module , latest firmware (0.95 )  , cant bind to Frsky D16 RX  , running latest Frsky FCC firmware ( 2.1.0 ) tested on RXSR , and X8R. 

same module no problem in binding to D8 capable RX.

 tnx

**Comment by pascallanger** [comment]
You need to use the protocol FrSkyX2 to bind v2.1.
