### ISSUE TITLE
Module unresponsive 50% of the time

### ISSUE THREAD

**Issue by glitch666** [pascallanger/DIY-Multiprotocol-TX-Module#353]
I have a mpm vantac lite on my xlite s pro. It is firmware 1.3.0.95 and my opentx is 2.3.7. when I turn my tx on about 50% of the time the module has a solid red and green light and will not bind, also doesn't show the firmware version in the model menu. I have to power off and on my tx multiple times before it will have a solid green light and bind. Or I can put the module back off and on multiple times and then it will work. I've tried different fw versions on the module and it does the same thing.

**Comment by pascallanger** [comment]
There is a known bug on this Vantac(=FrSky) module. The problem is the bootloader they are using. You need to upgrade it: https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/files/3594850/Vantac.MPM.Lite.Red.LED.Issue.docx

**Comment by glitch666** [comment]
Perfect 👍 thanks kindly.
