### ISSUE TITLE
T-FHSS protocol

### ISSUE THREAD

**Issue by nicolas81** [pascallanger/DIY-Multiprotocol-TX-Module#366]
I 'm not sure if it 's an issue but I can't bind multiprotocol module to futaba r3006SB T-FHSS receiver.
Is it normal?

**Comment by andika207** [comment]
@pascallanger TFHSS is the same protocol with telemetry enabled. only telemetry capable receivers (FASSTest or TFHSS) are supported by Futaba radios. (14SG, 16/18SZ, 18/32MZ) @nicolas81

**Comment by pascallanger** [comment]
It doesn't change that unless I have access to the hardware (TX and RX) there is nothing I can do.

**Comment by andika207** [comment]
@pascallanger TFHSS compatible receivers don't exist because the chinese have not been able to couple them to genuine Futaba radios so I don't think you can achieve this for MTM @benlye 
https://youtu.be/6e54T5AD6N8

**Comment by kilrah** [comment]
Of course it's possible, but again someone needs both a genuine transmitter and receiver to analyze the protocol.

**Comment by Saikiran-dev-art** [comment]
Hiii,
I am unable to find any resource on the Futaba T-FHSS protocol frame packet structure. Please anyone help me with this.

**Comment by tegots123** [comment]
it took a while for me to receive the usb logic analyzer but it finally arrived... @pascallanger  can you guide me on which traces should i solder/connect it and how to extract the logic?

![Image](https://github.com/user-attachments/assets/d12a3607-c0af-44a9-98fb-fc4062d237ef)
