### ISSUE TITLE
Support for Microzone reciver

### ISSUE THREAD

**Issue by ss8688** [pascallanger/DIY-Multiprotocol-TX-Module#367]
Microzone products sell well in here China,and they are cheap.It would be great if DIY-Multiprotocol-TX-Module can support  Microzone reciver. They may have 3  sub Protocol.

**Comment by pascallanger** [comment]
Which RF component is in use?
Can you dump the SPI bus on the TX?

**Comment by ss8688** [comment]
It use A7105

**Comment by ss8688** [comment]
but what is ‘dump the SPI bus on the TX’？Do you mean Hardware Hacking？

**Comment by ss8688** [comment]
@pascallanger I don't have one.but Iplan to buy one

**Comment by pascallanger** [comment]
@ss8688 You can buy a cheap 8CH analyzer and connect on the A7105 SPI bus.
FYI, this is a long process to reverse a protocol with many trials. Before investing the time, I need to make sure that you are ready to do so.

**Comment by ss8688** [comment]
@pascallanger [https://item.taobao.com/item.htm?spm=a230r.1.14.1.55c97f6aHAlACA&id=620031032239&ns=1&abbucket=12#detail](url)  Is this one work？

**Comment by ss8688** [comment]
But they have 6 and 10 ch TX ，I only have a 8ch one，6 and 10 ch reciver not work with 8ch tx，They may use different protocol.

**Comment by pascallanger** [comment]
@ss8688 Yes that's the logic analyzer I was refering too.

**Comment by ss8688** [comment]
I find it really hard to weld the line on the pin，I should improve my welding skill。so，I will try it later

**Comment by pascallanger** [comment]
No progress closing this issue...
