### ISSUE TITLE
Serial protocol question

### ISSUE THREAD

**Issue by dthakur** [pascallanger/DIY-Multiprotocol-TX-Module#37]
Question rather than an issue. Sorry for this is not the correct place, happy to post elsewhere.

Regarding the serial protocol that is used to talk to `erSky9X`, is that documented anywhere? I would be okay with some pointers to sources if there are no written docs. I'm attempting to interact with the module directly from a UART.

**Comment by pascallanger** [comment]
The protocol is detailed/documented in the sources. Look at the file Multiprotocol.h starting at line 417.
Let me know if you need more details.
