### ISSUE TITLE
Frsky R9 868MHz loosing connection

### ISSUE THREAD

**Issue by mszulen** [pascallanger/DIY-Multiprotocol-TX-Module#377]
Pascal, as per my message on rcgroups, where you've confirmed it's broken.
Latest FLEX firmware in R9MM receiver and latest multimodule firmware in T18
915MHz works ok, but when switching over to 868MHz, connection drops every few secconds (red led start blinking) .

**Comment by pascallanger** [comment]
Yes this is a known problem. Working on it

**Comment by mszulen** [comment]
Thanks! Let me know if some testing it needed.

**Comment by pascallanger** [comment]
868 is nearly fixed. I need to work on it a bit more but I have a stable link now.

**Comment by mszulen** [comment]
Wow! That's an express fix! :) Thanks for working on it! :)

**Comment by pascallanger** [comment]
I've pushed the 868 fix on github. If you compile by yourself you can test it.
On my side it works great.
Note that any previously bound RX needs to be rebinded for either 915 or 868.

**Comment by pascallanger** [comment]
I've added but not available yet in OpenTX the bind options to output CH1-8 or CH9-16 on the RX. It also has the telemetry on/off option at bind but the telemetry is not supported (yet).

**Comment by mszulen** [comment]
Perfect! Thanks a lot, Pascal!

**Comment by pascallanger** [comment]
I've also added telemetry now.
Closing the issue as for me it's working.
