### ISSUE TITLE
Config .h

### ISSUE THREAD

**Issue by alant101** [pascallanger/DIY-Multiprotocol-TX-Module#378]
Trying to locate config.h for preset fine tune frequencies for DIY-Multiprotocol-TX-Module. Information on how to or an example would be appreciated   

/*******************************/
/*** CC2500 FREQUENCY TUNING ***/
/*******************************/
//For optimal performance the CC2500 RF module used by the FrSkyD, FrSkyV, FrSkyX, SFHSS, CORONA and Hitec protocols needs to be tuned for each protocol.
//Initial tuning should be done via the radio menu with a genuine FrSky/Futaba/CORONA/Hitec receiver.  
//Once a good tuning value is found it can be set here and will override the radio's 'option' setting for all existing and new models which use that protocol.
//Valid range is -127 to +127
//Uncomment the lines below (remove the "//") and set an appropriate value (replace the "0") to enable.
//#define FORCE_FRSKYD_TUNING 0
//#define FORCE_FRSKYV_TUNING 0
//#define FORCE_FRSKYX_TUNING 0
//#define FORCE_SFHSS_TUNING  0
//#define FORCE_CORONA_TUNING 0
//#define FORCE_HITEC_TUNING  0
//#define FORCE_HOTT_TUNING   0

**Comment by pascallanger** [comment]
The file is named _config.h and is located in the Multiprotocol folder.
The text is quite explicative. There is no example... If you know the value you want just put it.

**Comment by alant101** [comment]
Thank you for your reply, but still unable to locate the Multiprotocal
folder. Where should I look please

**Comment by pascallanger** [comment]
https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/Multiprotocol/_Config.h
