### ISSUE TITLE
T18 Pro can't detect telemetry from R9MM

### ISSUE THREAD

**Issue by Jeerui** [pascallanger/DIY-Multiprotocol-TX-Module#383]
T18 Pro have bind with R9MM.Perfect Control the drone but no telemetry
opentx: T18 2.3.8
multi-t18int-opentx-aetr-noinv-v1.3.1.36.bin
serialrx-protocol:Fport
F4 FC

**Comment by pascallanger** [comment]
Which sub protocol?
Have you upgraded your RX to the latest version?
Which way RX to TX or TX to RX?

**Comment by pascallanger** [comment]
No news... From all reports and all tests it works fine but you must upgrade the RXs to the latest fw.
