### ISSUE TITLE
Hott Channel Mapping Request

### ISSUE THREAD

**Issue by bswoolf** [pascallanger/DIY-Multiprotocol-TX-Module#389]
Hi,

will it be possible to make a Channelmapping for Hott? I tried to work with an Alpha 110 Graupner Quad, but it seems, that needs Channelmapping. Or is there another workaround?

Regards
Wolfgang

**Comment by pascallanger** [comment]
Which radio do you have?

**Comment by bswoolf** [comment]
Radiomaster TX16S

**Comment by pascallanger** [comment]
Then do the channel mapping in the radio mixers...

**Comment by HazzaHFPV** [comment]
You can chose channel maps when flashing openTX and the Multi-Firmware when using or creating the needed .hex file can't you?
In companion I can set the channel mapping (TAER) as well as for the firmware for the multi-module firmware.
Or as Pascal said using the radio mixers.
