### ISSUE TITLE
4in1 module from bg. 

### ISSUE THREAD

**Issue by dperry20** [pascallanger/DIY-Multiprotocol-TX-Module#39]
I just purchase the 4in1 from bg. They shipped rev 1.2. Do I need to install the resistors or just bridge the connections for serial mode. Your picture of revision 1 is very different than the one I received. What is the function of the resistors?
Thank you for your help
Danny

**Comment by Dutchy-79** [comment]
Here's 498 off pages with information 
https://www.rcgroups.com/forums/showthread.php?2165676-DIY-Multiprotocol-TX-Module

Short version, v1.2 needs soldering the pads and no resistors. And and usbasp to update the firmware.

**Comment by dperry20** [comment]
Thank you

**Comment by pascallanger** [comment]
Documentation updated.
