### ISSUE TITLE
Unable to bind the X8R without telemetry

### ISSUE THREAD

**Issue by Salto42** [pascallanger/DIY-Multiprotocol-TX-Module#392]
Unable to bind the second receiver without telemetry.
Configuration:
      Jumper T16   2.3.9 otx  
       Internal MPM   V1.3.1.36   FrSkyX2  LBT(UE)

       Two   X8R

Works with MPM V1.3.1.24

**Comment by pascallanger** [comment]
Can you confirm that you are getting the popup menu with channels selection and telemetry?

**Comment by pascallanger** [comment]
I think I've found the issue...

**Comment by pascallanger** [comment]
I've just pushed a fix in master v1.3.1.41. If you compile by yourself the code it should work. Please report.

**Comment by Salto42** [comment]
Bonjour Pascal
Tout fonctionne correctement avec la dernière édition.
Un grand merci à vous pour votre promptitude, votre travail et votre patience...
 
 
 
 
> Message du 16/07/20 10:30> De : "pascallanger" > A : "pascallanger/DIY-Multiprotocol-TX-Module" > Copie à : "Salto42" , "Author" > Objet : Re: [pascallanger/DIY-Multiprotocol-TX-Module] Unable to bind the X8R without telemetry (#392)> >
>
> I've just pushed a fix in master v1.3.1.41. If you compile by yourself the code it should work. Please report.
—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/issues/392#issuecomment-659248676", "url": "https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/issues/392#issuecomment-659248676", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]
