### ISSUE TITLE
'rom' overflow when I define DEBUG_SERIAL

### ISSUE THREAD

**Issue by JPdeRie** [pascallanger/DIY-Multiprotocol-TX-Module#394]
Hi,
I've been wanting to read out the battery voltage over the serial port.
I am using the iRX4 multimodule and I switched to the latest software.
Now I want to do some testing with the debug lines but I get the error:

/home/jp/.arduino15/packages/arduino/tools/arm-none-eabi-gcc/4.8.3-2014q1/bin/../lib/gcc/arm-none-eabi/4.8.3/../../../../arm-none-eabi/bin/ld: Multiprotocol.ino.elf section `.text' will not fit in region `rom'
/home/jp/.arduino15/packages/arduino/tools/arm-none-eabi-gcc/4.8.3-2014q1/bin/../lib/gcc/arm-none-eabi/4.8.3/../../../../arm-none-eabi/bin/ld: region `rom' overflowed by 23120 bytes

Now I know there is the comment that says:
// Only for STM32_BOARD, compiled with Upload method "Serial"->usart1, "STM32duino bootloader"->USB serial

but on the arduino ide I dont see these options

My board setting is:
Multi 4-in-1 (STM32F103CB)

So ive got 3 possible solutions
- get the right upload method "serial"->usart1 ( but i dont understand how )
- change board so it compiles (but i dont know which one)
- remove 23120 bytes of unnecessary code

I hope that explains my situation a bit.
If anyone can give me some information about the subject, would be greatly appreciated
Thanks in regards!

**Comment by pascallanger** [comment]
This is expected. To enable debug mode you must comment a large number of protocols in _config.h .
Pascal
