### ISSUE TITLE
I powered up JP4IN1 module with antenna unconnected for a while. will there be any damage?

### ISSUE THREAD

**Issue by longxk** [pascallanger/DIY-Multiprotocol-TX-Module#397]
Do these multi-protocol module have any kind of protections for this problem?

**Comment by kimman1** [comment]
I think it will be weak but just a little bit, don't worry about that,  How long do you power 4in1 module without antenna ?

**Comment by longxk** [comment]
> I think it will be weak but just a little bit, don't worry about that, How long do you power 4in1 module without antenna ?

just several minutes

**Comment by pascallanger** [comment]
I think it is ok.
