### ISSUE TITLE
Add raw telemetry forwarding from internal module to external pins

### ISSUE THREAD

**Issue by ragelancer** [pascallanger/DIY-Multiprotocol-TX-Module#399]
Add a function that will grab all telemetry coming from internal multiprotocol module, an forward it to SPort pin in a module bay. This will be very useful for example when using external antenna tracker.

**Comment by pascallanger** [comment]
This is not something for Multi but OpenTX. Please open a case on their GitHub: https://github.com/opentx/opentx
