### ISSUE TITLE
Radiomaster TS16X & FrSky G-RX6 receiver

### ISSUE THREAD

**Issue by JCOFlyer** [pascallanger/DIY-Multiprotocol-TX-Module#405]
I am fairly new at this Open TX stuff but I can follow along and have used some youtube videos to help. I cant get the Radiomaster to bind with Frsky G-RX6. So i tried updating the receiver to the latest only to find that may have "broken" it. Frsky says to go under "downloads to get the old firmaware. So i did but it still doesnt work. Im running Open TX 2.3.9. Multiprotocol firmware was updated to 1.3.1.36 AETR no inv. stable and flashed to internal. Receiver was updated using external port (from botom up; signal, power, ground) ACCST D16 2.1.2 dated 07-14-2020 (NOT ACCESS) but later reverted (I think) to whatever 181025 is under their "history firmware download".

**Comment by kilrah** [comment]
From the bottom the module slot pinout is signal, ground, power. Needs a cable with swapped leads. If you put a straight cable you reversed polarity to the receiver.

**Comment by JCOFlyer** [comment]
I spoke from memory. But yes you are correct. I had to swap the pens around and it is signal ground and power. Also the lights start flashing the reciever. It seems to be writing firmware to it. It finishes up in about a minute and a half or so. Either way it doesn’t seem to work with either firmware.

Sent from my iPhone

On Jul 29, 2020, at 1:58 PM, Andre Bernet <notifications@github.com<mailto:notifications@github.com>> wrote:


From the bottom the module slot pinout is signal, ground, power. Needs a cable with swapped leads. If you put a straight cable you reversed polarity to the receiver.

**Comment by zendes** [comment]
Can you post the exact file name you downloaded from FrSky (.zip) and the
file you're flashing (.frk)? That should help identify which version &
flavor of ACCST you have on the receiver.

**Comment by JCOFlyer** [comment]
The first one is G-RX6_ACCST_2.1.2_FCC.frk. The one I tried reverting it to is G-RX6_FCC_181025.frk. I finally found a friend who has a QX7. We were able to bind to it. I will add that although we did bind it I did not have any movements in the servos.  I'll give the RadioMaster another chance when I get home if I can.

**Comment by zendes** [comment]
ok, so these are both FCC flavors, but different versions of ACCST. For G-RX6_FCC_181025.frk you need to bind with FrskyX, sub CH_16 or CH_8 and for G-RX6_ACCST_2.1.2_FCC.frk you need FrskyX2, same sub protocols

**Comment by JCOFlyer** [comment]
All right so I tried the 1.8X but I noticed that there was no FrSkyX only FrSky and FrskyX2. I tried them out either way. I updated the firmware to 2.1.2 for the FrSkyX2 D16 telemetry on 1-8 still was unable to bind. I was really hopeful that this was it. Please help. Not sure what else to do.

Sent from my iPhone

On Jul 30, 2020, at 1:00 PM, Dennis Marinus <notifications@github.com<mailto:notifications@github.com>> wrote:


ok, so these are both FCC flavors, but different versions of ACCST. For G-RX6_FCC_181025.frk you need to bind with FrskyX, sub CH_16 or CH_8 and for G-RX6_ACCST_2.1.2_FCC.frk you need FrskyX2, same sub protocols

**Comment by pascallanger** [comment]
Binding a RX is really easy. I'm wondering what you are doing wrong...
Here are the steps:
1. Power on the RX while pushing the bind button, wait 1-2 sec then release the button -> the RX's LED should act differently while in bind mode
2. Power on the TX
3. Create a new model
4. Select Multi FrSkyX2 D16
5. Press the bind button on the same page
6. Wait for the RX LED pattern to change
7. Power off the RX
8. Power on the RX
9. Done

**Comment by JCOFlyer** [comment]
YES!!!!!!! Thank you. So the telemetry light going off really threw me off. Feel stupid now. Spektrum to Frsky transition has been weird. Although I wouldn’t have guessed the protocols anyways. Very much appreciate all you guys and your help. I’ll be donating to the project for sure!!

Sent from my iPhone

On Aug 1, 2020, at 1:15 AM, pascallanger <notifications@github.com<mailto:notifications@github.com>> wrote:


Binding a RX is really easy. I'm wondering what you are doing wrong...
Here are the steps:

  1.  Power on the RX while pushing the bind button, wait 1-2 sec then release the button -> the RX's LED should act differently while in bind mode
  2.  Power on the TX
  3.  Create a new model
  4.  Select Multi FrSkyX2 D16
  5.  Press the bind button on the same page
  6.  Wait for the RX LED pattern to change
  7.  Power off the RX
  8.  Power on the RX
  9.  Done

**Comment by pascallanger** [comment]
With multi the bind process is the same whatever protocol you use.
