### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by sany198424** [pascallanger/DIY-Multiprotocol-TX-Module#409]
need help I can't link rsdiomaster TX16S with the radiolink r7fg receiver , I saw that yesterday you already worked on this Protocol but I don't see where I can skip the file bin ready, in the download branch hangs the file without changes Multiprotocol multi-stm-opentx-AETR-noinv-v1.3.1.36.bin , could you ( pascallanger ) update it with changes for radiolink. I'm a newbie just 2 days ago I bought radio control equipment

**Comment by sany198424** [comment]
when you release the Multi V1.3.1.48 update

**Comment by pascallanger** [comment]
Soon...

**Comment by pascallanger** [comment]
Multi V1.3.1.49 released

**Comment by sany198424** [comment]
thank you very much
