### ISSUE TITLE
Range ??? DIY Multiprocol Banggood v2

### ISSUE THREAD

**Issue by andremelin** [pascallanger/DIY-Multiprotocol-TX-Module#42]
we tried it today with latest release on both sides rx and tx opentx2-2-362 with DMS X and telemetry with the Spektrum T1000 hub on the Diy Multiprotocol of Banggood with . Yet I have some questions. I measured the RF output power of 22DBm. On the Taranis Plus the telemetry recognised the Alt and Vspd and some other "F de A...b...c and so on". Range mode test was about 80meters. In flight we got RF signal critical message at 100m hight and 60m horizontal distance so around distance real of 128m only. Is this normal ?How comes we get the RF Critical message, is it to do with the opentx RSSI value ? How did you get to define this value and where ? Thanks for explanation in advance because with 22DBm rf signal output power which is largely above the 20DBm max power range of normal emitters we can consider being long range and over that???

**Comment by pascallanger** [comment]
A DSM RX does not send back the RSSI information part of the telemetry (like a FrSky RX does).
The only thing I've been able to do is to read the RSSI of the incoming telemetry packet therefore from a TX perspective.
So in short the TX_RSSI displayed on the radio does not mean that the RX is loosing connectivity but instead that the TX is loosing the telemetry signal.
From the alert perspective, I don't know and you have to ask the OpenTX guys. But for sure the value coming from DSM which is based on the Cyrf6936 is going to be different from the FrSky value on the CC2500.
You should do a test on ground with a servo sweep and move away from the radio with the RX. Joao has done this test lately with the FrSkyD protocol and reached 1.5km while keeping full control and telemetry. But again this is a different protocol and RF chip.

Pascal
