### ISSUE TITLE
A support for FMS receivers possible?

### ISSUE THREAD

**Issue by evildronepilot** [pascallanger/DIY-Multiprotocol-TX-Module#423]
There's a wide range of FMS models that come with the receivers... 
Does the support for those exist or can it be implemented please?
Happy to offer testing.

**Comment by pascallanger** [comment]
Which RF component in the TX/RX?
Are you able to do SPI dumps? If not will you send me a TX and RX?

**Comment by pascallanger** [comment]
No answer?

**Comment by pascallanger** [comment]
The FMS Ranger 850mm aircraft is using the FrSky D8 protocol.
Could it be that this is what you are looking for?

**Comment by evildronepilot** [comment]
Hi guys sorry for leaving you hanging for so long.
I ordered the FMS P51D 1.4m  and it's supposed to come with a receiver... unfortunately this is not longer the case so can't really help with testing it :( 
I still believe this might become useful future for someone who is using FMS receivers ?

**Comment by pascallanger** [comment]
I'm closing this issue, since without a TX and RX to work on there is nothing to be done...
