### ISSUE TITLE
Support of TraSped Protocoll

### ISSUE THREAD

**Issue by wimalopaan** [pascallanger/DIY-Multiprotocol-TX-Module#433]
This is more a question than a request for a new protocol.

Is the "TracSped" protocol supported? Or, what protocol do they use. Somewhere I read to be AFHDS/AFHDS2A, bus that did not work for my.

In the protocol list I can't find any clue about this.

So, If this is devices is definetly not supported by any known protocoll, this issue may by immediately closed.

**Comment by pascallanger** [comment]
Never heard of it before, sorry...
