### ISSUE TITLE
Display DSM RSSI value

### ISSUE THREAD

**Issue by TedAus** [pascallanger/DIY-Multiprotocol-TX-Module#440]
Is it possible to get/display RSSI value with DSM receiver? I can only get the RSSI value on the screen when doing a range check. RSSI does not seem to be available as one of the telemetry sensors. Thanks.

**Comment by kilrah** [comment]
DSM doesn't do RSSI at all, what you see when doing range check is the strength of the received telemetry.

**Comment by pascallanger** [comment]
Which is called TRSSI if you look for the sensor.

**Comment by TedAus** [comment]
Ok, thanks guys!
