### ISSUE TITLE
Supported with OpenTX V2.3.9?

### ISSUE THREAD

**Issue by teozfrank** [pascallanger/DIY-Multiprotocol-TX-Module#441]
Hi,

I am trying to get the multimodule setup with my QX7. I have flashed the module according to the instructions with multi-stm-opentx-taer-inv-v1.3.1.69.bin.

But on OpenTX companion 2.3.9 there is no multi option in build options, nor does it display "multi" in external module. Is there something I am doing wrong?

![image](https://user-images.githubusercontent.com/3265598/95023307-46478f80-0674-11eb-9a65-c586ef60b8b4.png)

All the videos I find on YouTube are over 3 years old so appriciate any help here.

Frank.

**Comment by kilrah** [comment]
It's always there, no option needed.

**Comment by teozfrank** [comment]
> 
> 
> It's always there, no option needed.

Oh ok, what about multi then in external module. If I try and select DSM2 -> DSMX and try and bind with rx 00 it wont bind. I am using a dsmx bind and fly inductrix FPV +

**Comment by pascallanger** [comment]
You must select multi then the protocol and not dsm2.

**Comment by teozfrank** [comment]
> 
> 
> You must select multi then the protocol and not dsm2.

Options I get on External RF is OFF, PPM, XJT, DSM2, R9M and SBUS. I dont seem to have MULTI ?

**Comment by pascallanger** [comment]
@3djc @kilrah any ideas?
@teozfrank This is OpenTX related. You might have more chance to find help if you open an issue on the OpenTX github.

**Comment by bbc25185** [comment]
> > You must select multi then the protocol and not dsm2.
> 
> Options I get on External RF is OFF, PPM, XJT, DSM2, R9M and SBUS. I dont seem to have MULTI ?

Can you check the OpenTx version installed on your radio? (you also dont have the CRSF protocol)
(Long press menu, go to page 7 and read the version of OpenTx)

**Comment by teozfrank** [comment]
> 
> 
> > > You must select multi then the protocol and not dsm2.
> > 
> > 
> > Options I get on External RF is OFF, PPM, XJT, DSM2, R9M and SBUS. I dont seem to have MULTI ?
> 
> Can you check the OpenTx version installed on your radio? (you also dont have the CRSF protocol)
> (Long press menu, go to page 7 and read the version of OpenTx)

opentx - x7 2.3.9-frsky (e4336857)

**Comment by bbc25185** [comment]
You get the firmware from companion or downloaded from Frsky Site?

**Comment by teozfrank** [comment]
> 
> 
> You get the firmware from companion or downloaded from Frsky Site?

Frsky site.

**Comment by bbc25185** [comment]
Get the firmware from companion and reflash with it! XD

**Comment by pascallanger** [comment]
Wow good finding!!!
He showed a Companion screenshot earlier so I assumed he was using Companion to download and install it...

**Comment by teozfrank** [comment]
> 
> 
> Wow good finding!!!
> He showed a Companion screenshot earlier so I assumed he was using Companion to download and install it...

I used the companion to flash it yes.

**Comment by bbc25185** [comment]
DOWNLOAD and flash... DONT use the file downloaded from frsky site! XD

**Comment by teozfrank** [comment]
> 
> 
> DOWNLOAD and flash... DONT use the file downloaded from frsky site! XD

Yes that was it!! Thank you!!!

version is now 2.3.9-otx 60e1edc1

:)

**Comment by bbc25185** [comment]
You connect the radio to PC WITHOUT turning on the radio????
if you connect it off, it connects to the PC in DFU mode which is what we are interested in (in DFU it is possible to flash bootloader and firmware, in the other ways only the firmware) ...
All the other ways only work if you don't touch the bootloader and, at least the first time, regardless if it works or not, it's best to get it complete.
