### ISSUE TITLE
Can AFHDS 2a be emulated with any other chip than A7105/6

### ISSUE THREAD

**Issue by diego0815** [pascallanger/DIY-Multiprotocol-TX-Module#449]
As it's quite hard getting good quality long range A7105 modules for DIY module building is it in theory possible emulating this protocol on any other HW (also new one not currently in use with the 4in1 module)? Except of course the SDR approach.
I would love being able to do most protocols on an NRF52840 or so :-)

**Comment by pascallanger** [comment]
Sure you can do anything but you need to reverse the RF hardware implementation of the A7105.

**Comment by diego0815** [comment]
Hmm sounds more complicated than I hoped for, when reading about emulation of xn297 with cc or nrf sounds alot easier ;-)

**Comment by pascallanger** [comment]
It's easy because you have the solution in front of your eyes...
If it was that easy to emulate a component from another there won't be 4 RF component...

**Comment by diego0815** [comment]
Valid point, very true, thanks!
