### ISSUE TITLE
Eachine E016H with different Protokoll

### ISSUE THREAD

**Issue by hpoorthuis** [pascallanger/DIY-Multiprotocol-TX-Module#452]
Before write the Ticket i did research about the E016H
found at "goebish" Eachine E016H support #46 witch seems to be base for the EO16H Protokoll.
[https://github.com/goebish/nrf24_multipro/issues/46](url) (chip The chip: XNS1042CV)
today i open my Transmitter and found :HW217BP4SD so eachine did change the Protokoll.
any idea to find the right Protokol.
![IMG_20201011_183858](https://user-images.githubusercontent.com/20501574/95684855-94b8d900-0bf4-11eb-89ba-9531ea02ce6f.jpg)

**Comment by pascallanger** [comment]
No... Unless you have a SDR to do a capture over the air we won't know if we can reverse the protocol.

**Comment by pascallanger** [comment]
I'm going to close this issue since there is no way to move forward with the given information...
