### ISSUE TITLE
Question: Multiprotocol Module + Raspberry pi

### ISSUE THREAD

**Issue by wx4cb** [pascallanger/DIY-Multiprotocol-TX-Module#458]
had a look through the issues, but couldn't find one.

Is it possible to connect a multiprotocol module using the JR bay ins (or another method) to the gpio of a raspberry pi that can output either serial or a ppm stream on the GPIO.

I'm looking to emulate an FRSkY transmitter to do some receiver testing with known, controllable values. The current module that I have at hand is the one that came with the T16 (unmodified/updated as of yet - it's been sitting in a drawer as i'm a crossfire user)

Charlie

**Comment by pascallanger** [comment]
The serial protocol used by multi is described here: https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/5ed61f30e12a9bf91055ad0ebfad38151538f42a/Multiprotocol/Multiprotocol.h#L729
If you follow the description then it can be connected with whatever you want.
