### ISSUE TITLE
1.3.1.75

### ISSUE THREAD

**Issue by SPCORRIV** [pascallanger/DIY-Multiprotocol-TX-Module#459]
Hey just bootloaded irangex 4in1 with option 3 and when I was done it was version 1.3.1.75 I thought the latest was .69 ? Any issue with this or do I need to back up to .69.

Thanks

**Comment by benlye** [comment]
1.3.1.69 is the latest pre-compiled firmware, but the head of the repository is at 1.3.1.75.  As you downloaded and compiled, you got the head of the repo.  You can go back if you want to (just download the source from the tagged release) but there is really no need.

**Comment by SPCORRIV** [comment]
Hey Ben

   Thank you , I'm new at this side of this. Just trying to make sense of
it , you work is greatly appreciated and Pasals too.

Thanks
