### ISSUE TITLE
XK 450 Servos Motor are jumping

### ISSUE THREAD

**Issue by Githubbachelor** [pascallanger/DIY-Multiprotocol-TX-Module#467]
I connect with XK450 new protocol best -60 Fine Tuning in Multimodul Jumper with Horus 12s. Everything seems to be OK but the motor servos are jumping in both directions on channel 4 for Ruder? Seems a problem with throttle and Rudder. There must be a mistake in the protocol? This happen alway, when the stick from rudder is at 0% and you want to try left or right direction, when throttle is over 50%. Servos from motors are jumping from one side to the other side uncontrolled. Not stable. In the monitor from TX you cannot see this reaction. Best situation was minimal reducing that phenomen with FInetuning from -40 to -60 - Best results but still there the problem. All thingswith latest firmware and software.Open Tx. Same problem much intensiver with Radiomaster

**Comment by pascallanger** [comment]
Duplicated with issue https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/issues/347.
