### ISSUE TITLE
Document the protocol betwen the Radio the Multimodule

### ISSUE THREAD

**Issue by wucke13** [pascallanger/DIY-Multiprotocol-TX-Module#471]
Hi, I would like to implement a library for talking to this module. My understanding is that there must be some protocol over which I can talk to the module via serial port. One byproduct of doing so would be some documentation about the protocol as well, which seems to be missing ATM (at least I did not find it).

Where can I find some information (documentation, or at least the datatypes and memory layouts of them) which are transmitted over the serial port?

**Comment by pascallanger** [comment]
The serial protocol documentation is here: https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/832a331437d7b8d0bf9844f770d540929e6f2f97/Multiprotocol/Multiprotocol.h#L744
