### ISSUE TITLE
low power mode option

### ISSUE THREAD

**Issue by ranger2012** [pascallanger/DIY-Multiprotocol-TX-Module#472]
xk a180 stock transmitter goes up to 100 meters,  my  jumper t12 with JP4in1 goes up to 50 meters,  is there a way to select  low power mode to say 25%  or 50%  ?, 10% is way too low...

**Comment by pascallanger** [comment]
Power levels are defined in this file: https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/e53f723fdb7c2e50eb2015137cdc10cf00192da3/Multiprotocol/Multiprotocol.h#L638
Change the value to whatever you want and compile your own version.
