### ISSUE TITLE
XK450 Motor schaltet nach Landung nicht ab

### ISSUE THREAD

**Issue by Githubbachelor** [pascallanger/DIY-Multiprotocol-TX-Module#476]
XK450 Motor schaltet nach Landung nicht automatisch ab. Alles ist soweit OK. Motor schaltet nach etlichen Versuchen nun mit Ch7 ab. Die original Anlage von dem XK450 macht das automatisch nach Landung.
Die Bindung muss vor jeder Nutzung erneut vorgenommen werden, Feintuning wurde komplett durchgescheckt.
Over ChANNEL Binding wurde gesetzt - Auch bindet oder Aktiviert er nicht über den Throttle/Gas Knüppel, wie original Anlage macht. Also Binden jedes mal neu.

Das Problem mit den Motoren auf CH4 hast du ja grandios erledigt. Vielleicht hast du eine Idee warum der Motor nicht automatisch ausgeht nach Landung. 
Trotzdem vielen Dank Pascal, dass man das Ding schon mal fliegen kann. Vielleicht hast du eine Chance die restlichen Dinge zu erledigen, das wäre suuuupeerr aber MUSS NICHT UNBEDINGT.
Gruß Michael

**Comment by pascallanger** [comment]
Please use English to describe your issue.
I don't have this model so I need a good description of what's happening. Without this there is no way I can help....
One thing which puzzles me is that I have 2 persons that have done test flights and have reported that everything was fine.

**Comment by pascallanger** [comment]
The bind is not done through throttle like most of the Multi protocols but through the use of "Bind".
To use bind on channel, check the documentation: https://www.multi-module.org/using-the-module/binding#bind-on-channel

Emergency stop of the motors is done through CH7 as explained in the doc: https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/Protocols_Details.md#xk---62

**Comment by Githubbachelor** [comment]
Than you for your help pascal

 

Von: pascallanger <notifications@github.com> 
Gesendet: Samstag, 5. Dezember 2020 16:36
An: pascallanger/DIY-Multiprotocol-TX-Module <DIY-Multiprotocol-TX-Module@noreply.github.com>
Cc: Githubbachelor <rcbachelor@t-online.de>; Author <author@noreply.github.com>
Betreff: Re: [pascallanger/DIY-Multiprotocol-TX-Module] XK450 Motor schaltet nach Landung nicht ab (#476)

 

The bind is not done through throttle like most of the Multi protocols but through the use of "Bind".
To use bind on channel, check the documentation: https://www.multi-module.org/using-the-module/binding#bind-on-channel

Emergency stop of the motors is done through CH7 as explained in the doc: https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/Protocols_Details.md#xk---62
