### ISSUE TITLE
F.PORT Multiprotocol

### ISSUE THREAD

**Issue by seventhplug** [pascallanger/DIY-Multiprotocol-TX-Module#483]
Hello, Sorry I'm a bit noob. I have Jumper T12 (Opentx 2.3.10) with 4in1 MPM (v1.3.1.78). Ive been trying to make FPort work with my 3" Quad.

Frsky XSR (FPORT_NonEU_171114.frk Firmware)  with Inverted Mod https://blck.mn/2016/12/smartport-frsky-xsr-and-betaflight-part-2/ HakRC mini F4 with the Latest Inav.. i set the univerted (inverted) to TX 6 and set the Serial Receiver to FPort.  The RX is bound to TX but i get no response in the Receiver Tab in Inav Configurator.. I tried every possible tutorials online.. but my question is.. does MPM support FPort? Thank You

**Comment by pascallanger** [comment]
FPort is a presentation of the data from the RX. It has nothing to do with the TX...
You should go on RCGroups and ask your question there as I can't help you since I'm not using this kind of receivers.
