### ISSUE TITLE
The spectrum analyzer will not start on external iRangeX module.

### ISSUE THREAD

**Issue by prikrylm** [pascallanger/DIY-Multiprotocol-TX-Module#489]
Since version 1.3.1.69 (approximately) I have not been able to run the spectrum analyzer on the iRange external module. On the internal module of the TX16S the spektrum analyzer starts normally.
My problem with the external module still remains in version 1.3.1.92.

Tested on Taranis plus (before 2019), X-lite and TX16S on OTX 2.3.10, MPM iRangeX Plus and iRange IRX4 + and IRX4 Lite.

Is this an external module problem? Or am I doing something wrong?

**Comment by benlye** [comment]
OpenTX issue, already fixed in the 2.3.11 nightly builds.

https://github.com/opentx/opentx/issues/7997
