### ISSUE TITLE
FrSky X9Lite with TBS MPM Module - No Telemetry

### ISSUE THREAD

**Issue by mikeller** [pascallanger/DIY-Multiprotocol-TX-Module#491]
### Setup:
- UPDATED: FrSky X9 Lite with vanilla OpenTX 2.3.10 (7ac1ecb6);
- TBS MPM module with `multi-stm-serial-aetr-v1.3.1.92.bin` vanilla multiprotocol firmware.

### Reproduction:
- select 'MULTI' for 'External RF' in OpenTX.

### Expected Behaviour:
- 'Status' shows the module status.

### Actual Behaviour:
- 'Status' shows 'No Telemetry'

**Comment by pascallanger** [comment]
I don't know this TBS module. Was it working with the original firmware it came with?
Can you do pictures of the inside?

**Comment by mikeller** [comment]
@pascallanger: It is this one: https://www.team-blacksheep.com/products/prod:tbs_mpm

The pre-installed firmware reported as 1.3.1.92 as well, and it had the same problem (RC working, but 'No telemetry') - I then did some tests with custom firmware with telemetry inversion / telemetry inversion switching disabled, without success, and flashed back to vanilla.

![IMG_0909](https://user-images.githubusercontent.com/4742747/103036839-7ea19e80-45cf-11eb-9fab-9b7d197445d8.jpg)
![IMG_0908](https://user-images.githubusercontent.com/4742747/103036841-7fd2cb80-45cf-11eb-9771-4d8a74fcdea6.jpg)

**Comment by kilrah** [comment]
So it never worked even with the original firmware? Seems hardware related then...
Did you try stock OpenTX?

**Comment by mikeller** [comment]
@kilrah: Yes, it never worked with the original firmware that the MPM came with. I did try stock OpenTX, but this does not support 'MULTI' as an option for 'External RF', so that wasn't going to work (unless I am misunderstanding something).

**Comment by kilrah** [comment]
OpenTX distributed by FrSky doesn't include multi, but all downloads from OpenTX Companion do. I just meant "not compiled yourself".

**Comment by mikeller** [comment]
The vanilla version that I originally tested with was the 2.3.10 (7ac1ecb6) that companion23 downloads and installs (`opentx-x9lite-afhds3-faichoice-flexr9m-lua-en-2.3.10-otx.bin`) - I am assuming that this from OpenTX and not FrSky? Looks like this version is built without support for 'MULTI'.

**Comment by kilrah** [comment]
Just tried that some file and multi is here...
Have you turned off internal RF?

**Comment by mikeller** [comment]
@kilrah: Interesting. I flashed vanilla OpenTX again, and this time 'MULTI' is showing up - not sure what went wrong the last time round. And yes, I'd tried with 'Internal RF' disabled both times round.
But unfortunately, the end effect is the same - 'No Telemetry'. :disappointed:

**Comment by kilrah** [comment]
Telemetry will definitely not work if internal is on, but should be fine when off. Can check on my radio and a multi tomorrow but it really seems likely theres something wrong with the module...

**Comment by mikeller** [comment]
@kilrah: Internal was definitely off when testing. 

> it really seems likely theres something wrong with the module...

Do you mean as in 'DOA hardware'?

**Comment by kilrah** [comment]
Possibly...
2 more things to check, firstly an OpenTx build without faichoice (it's for disabling telemetry after all) and that you didn't check "disable telemetry" in the external RF settings

**Comment by mikeller** [comment]
@kilrah:

> an OpenTx build without faichoice

Didn't help.

> you didn't check "disable telemetry" in the external RF settings

'No Telem' was never checked for the external module.

**Comment by kilrah** [comment]
OK, so with an x9 lite with `opentx-x9lite-afhds3-faichoice-flexr9m-lua-en-2.3.10-otx.bin` and a irangex lite with `multi-stm-serial-aetr-v1.3.1.92.bin` everything is fine here, as expected no telem if internal is on and working when it's off... even when FAI mode is enabled.

![IMG_20201224_094429](https://user-images.githubusercontent.com/6065069/103076095-413c1180-45cd-11eb-8ee1-c2e698ab8527.png)

**Comment by mikeller** [comment]
@kilrah: Not entirely sure how your last comment relates to the problem described in this issue?
Is the 'irangex lite' the same hardware as the TBS MPM (maybe @tbs-trappy can confirm), and this is a case of DOA hardware?

**Comment by tbs-trappy** [comment]
the hardware is identical to RadioMaster protocol. I am not familiar with iRangeX lite hardware. certainly not ruling out DOA, if e.g. one pin would not connect then telemetry would not show up, correct? perhaps a quick test with multimeter to test the telemetry input pin passes all the way to the top board could rule out the most likely case of the wire being faulty?

**Comment by mikeller** [comment]
Thanks @tbs-trappy. Is this the correct pinout for the module port on the X9 Lite and the TBS MPM module:

![image](https://user-images.githubusercontent.com/4742747/103080100-07552480-463a-11eb-80c5-91f1678f3549.png)

Can you please let me know what pins the RC signal and telemetry are meant to be on on this connector?

**Comment by tbs-trappy** [comment]
yes, we do not have a connection for 6, 7 and 8 though.

**Comment by kilrah** [comment]
Telemetry comes on the S.Port pin

**Comment by mikeller** [comment]
Thanks @tbs-trappy and @kilrah, I will be doing some logic analysing then.

**Comment by mikeller** [comment]
Ok, this is what I get on startup:

![image](https://user-images.githubusercontent.com/4742747/103103843-c5070400-4688-11eb-9853-34c2f00f2721.png)

Looks like the module sends inverted data on the S.Port pin for about 1.3 seconds, and from then on only sends periodical spikes. This is how one of the spikes looks like:

![image](https://user-images.githubusercontent.com/4742747/103103915-3a72d480-4689-11eb-87bd-8b1e6fea93ba.png)

On closer look, the initial 'data' on S.Port also turns out to be only spikes:

![image](https://user-images.githubusercontent.com/4742747/103103969-83c32400-4689-11eb-9408-1835a917a91a.png)

Just for fun I uncommented `#define INVERT_TELEMETRY` in `_Config.h` and rebuilt, but even with this (resulting in uninverted telemetry) the output on the S.Port pin is just spikes:

![image](https://user-images.githubusercontent.com/4742747/103105133-9e4ccb80-4690-11eb-86a3-a539ec210fe0.png)

So to me it looks like (@tbs-trappy to confirm):
- the MPM module has an external inverter on the telemetry output / S.Port pin;
- this inverter seems to be garbling the telemetry output on my module - either due to a DOA module, or through a design fault.

**Comment by pascallanger** [comment]
You need to also comment this line to change the telemetry polarity otherwise OpenTX will switch it back:
https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/2098cdc5e04e22e84ceb8559ceb74b2dd5d83b48/Multiprotocol/_Config.h#L301
Not saying it will help but at least you will have control.

**Comment by mikeller** [comment]
@pascallanger: I have already tried that. But as the first three and the last screenshots above show, even with `INVERT_TELEMETRY_TX` the line level ends up being low in vanilla Multiprotocol, with `INVERT_TELEMETRY` not defined, or high when `INVERT_TELEMETRY` is defined.

**Comment by mikeller** [comment]
I did some more testing with different combinations of `TX_INV_on/off` and `RX_INV_on/off`, and tried setting the UART TX pin to OD, without success. Without getting access to schematics for the module from @tbs-trappy I don't think there is much more that can be done to debug this.

**Comment by pascallanger** [comment]
Check what you have at the input of the inverter (C86) and output.

**Comment by mikeller** [comment]
@pascallanger: Is this on the TBS MPM board? Mine does not have component numbers on the silk screen, do you have a picture / diagram?

**Comment by pascallanger** [comment]
This is the component marking, small chip right next to the STM 32

**Comment by mikeller** [comment]
@pascallanger: I suspected so. I am currently mobile and I don't think I'll be able to probe this one without shorting and breaking it - do you have an engineering sample of this module?

**Comment by pascallanger** [comment]
Like I've said at the beginning of this thread i've never seen this module... And I have no TX with this connector either...

**Comment by tbs-trappy** [comment]
please let me know if you need an engineering sample. I've asked RadioMaster (the designer and manufacturer) to look at this page however I have not yet received a response from them.

**Comment by pascallanger** [comment]
Engineering samples would be great in any case.
But I mean you must have tested this module type before selling it on a radio. Was it working? What was the setup?

**Comment by mikeller** [comment]
Happy to do some more testing with this, but I am currently traveling and have limited access to testing gear. I'll be able to do more in-depth testing after 18 Jan.
Probably a good question to ask RadioMaster is if they have specifically tested telemetry feedback (can be verified by getting the multiprotocol version to show under 'Status' in in the OpenTX module configuration), and what TX model(s) they have tested this with - one suspicion is that this could be caused by different electrical properties (pull up / down) on the SmartPort pin on the TX module.
Just to recap, what TX models is this module designed to work on:
- TBS Tango 2?
- FrSky XLite?
- FrSky X9 Lite
- ?

**Comment by tbs-trappy** [comment]
@mikeller @pascallanger please send me an email I will make sure to send you a unit each. 

We have verified telemetry working. I've personally flown a few packs with a whoop, tested the "feel" and checked the telemetry screen on the Tango 2. I don't own a X9/Xlite, but I don't see any reason why it shouldn't work there either. Although the module is predominantly for TBS Tango 2 customers, it's supposed to work with other remotes sporting the same connector.

I will push RM's engineers again to see if I can get a response, in the meantime thanks for looking at this and I'll wait for your email to send out a unit to you guys.

**Comment by kilrah** [comment]
The module only being tested on the Tango and there being a drive strength issue or such with the X-Lites was also my guess, AFAIK RM don't have a Lite module yet so nothing they could base themselves on that they know is OK with those.

**Comment by mikeller** [comment]
@kilrah: Thanks for the insight. With 'drive strength issue' do you mean that the pull ups / pull downs on the TX aren't strong enough? Also, to make my testing a bit less potshot-y, do you know if the X9 Lite expects the input on the S.Port pin to be inverted (low at rest) or uninverted (high at rest)?

**Comment by kilrah** [comment]
> Thanks for the insight. With 'drive strength issue' do you mean that the pull ups / pull downs on the TX aren't strong enough?

Possibly... Would be good to look at the signal with a scope to see how it looks like.
Polarity should be like any other frsky radio, so inverted TTL.

**Comment by mikeller** [comment]
Good point @kilrah. I currently only have a cheapo knock-off Saleae logic analyser with me, so I can not look at the signal form - but it is well possible that the form is right but the levels are off. And thanks for clarifying the polarity - this reduces one variable in the guesswork.

**Comment by pascallanger** [comment]
Short this diode and try again:
![image](https://user-images.githubusercontent.com/6367598/103784155-e5946e00-5039-11eb-9cc2-17a02d24d4ec.png)
That should do the trick. If it works as I assume, replace the diode by a small resistor like 470Ohm and you are good to go.

**Comment by mikeller** [comment]
@pascallanger: Did a quick test with the non-return diode shorted out, and with a 1k shunt over it. Unfortunately this did not change anything, which is what I'd expected, considering that the pull up on the S.Port pin also had not fixed it.

**Comment by pascallanger** [comment]
1K is going to be too much. Just shorten the diode has shown and use an official firmware so we know what you are running.

**Comment by mikeller** [comment]
@pascallanger: See my comments above.

**Comment by sfjuocekr** [comment]
Do you get the with FlySky only or also with others?

I get the same no telemetry status when I switch to my cheapo receiver and I have it turned off:

![IMG_20210116_003359](https://user-images.githubusercontent.com/398018/104788851-98c83a00-5793-11eb-9aa4-1e77627ff799.jpg)

Then when I connect it:

![IMG_20210116_003452](https://user-images.githubusercontent.com/398018/104788867-a4b3fc00-5793-11eb-9697-44af48ecc533.jpg)

This receiver doesn't even have telemetry, so I don't really care :D

**Comment by mikeller** [comment]
@sfjuocekr: This is about the telemetry between the multiprotocol module and the TX - this should be independent of the over the air RC protocol selection.

**Comment by sfjuocekr** [comment]
Ah, so "No telemetry" reflects TX <> MULTI and "No MULTI_TELEMETRY" reflects MULTI <> RX?

Mildly confusing as the wiki page on the X10 suggests they are the same.

**Comment by kilrah** [comment]
On the Module status line they both mean Multi->TX and nothing else.

**Comment by sfjuocekr** [comment]
Ok, then what @mikeller said was a wrong assumption. Yes, this receiver has no telemetry but it wasn't even bound so this status did reflect a lack of telemetry from the module.

I get the MULTI_TELEMETRY status on first boot up sporadically and only noticed it with FlySky2A selected.

**Comment by kilrah** [comment]
>  Yes, this receiver has no telemetry but it wasn't even bound so this status did reflect a lack of telemetry from the module.

That's exactly what he said...

**Comment by sfjuocekr** [comment]
I know, but I guess the "No MULTI_TELEMETRY detected" in my example is then just a freak coincidence if it has nothing to do with with telemetry to the RX?

It goes away if I switch protocols, most of the times it works it just shows "No MULTI_TELEMETRY detected" sporadically.

**Comment by kilrah** [comment]
It has nothing to do with telemetry to RX indeed and that's what we've all been saying.

**Comment by ryancummings** [comment]
Just dropping in to report I'm having the same "No Telemetry" error using the TBS MPM with my X9 Lite S. The message is present regardless of module protocol or rx bind.

**Comment by tbs-trappy** [comment]
we've just had a closer look into this. 

our test units are indeed working, however they are on firmware v1.3.1.59. It seems that the latest units are shipping with a more recent firmware which does not work.

**Comment by pascallanger** [comment]
> we've just had a closer look into this.
> 
> our test units are indeed working, however they are on firmware v1.3.1.59. It seems that the latest units are shipping with a more recent firmware which does not work. Do you see any changes that could be the cause? The latest firmware is also not working on Tango 2, btw.

That's more than surprising and hard to believe... There has been no change from the protocol side for at least a year and it was 1.3.0.44.
Since you are able to test, try all the releases and find out at which point it breaks. That's easy to do and will help to narrow it down.

**Comment by tbs-trappy** [comment]
@pascallanger I've noted above please dm me your address or send me an email (trappy & gmail) and I'll send you whatever you need. 

I'm not familiar with the details of the issues, I'm simply providing the information I've received: 
* Tango2, with version 1.3.1.59 or below, works
* Tango2, with version beyond 1.3.1.59, does not work

I'm waiting on a X-Lite and will provide the same data points. Also, this is not TBS "hardware" per se, it's RadioMaster hardware in a TBS enclosure, which makes this even more puzzling. I've tried contacting RadioMaster but I have not yet received a response.

**Comment by kilrah** [comment]
On the OpenTX side we've got Tangos but they're the old version without the module port.

**Comment by pascallanger** [comment]
@tbs-trappy I've sent you an email. I'll start to investigate what could be the problem with 1.3.1.59+

**Comment by mikeller** [comment]
Thanks guys for debugging this.
I did a quick check with the X9 lite, but 1.3.1.59 still gives me 'No Telemetry'. I tried both `multi-stm-opentx-aetr-inv-v1.3.1.59` and `multi-stm-opentx-aetr-noinv-v1.3.1.59`, with OpenTX 2.3.11.

I'll let you guys first work out what is wrong with newer versions on TBS hardware. Once this is sorted we can look into making non-TBS hardware work with the fixed version.

**Comment by ryancummings** [comment]
Likewise, 1.3.1.59 is still showing "No Telemetry" on my X9 Lite S.

**Comment by pascallanger** [comment]
@tbs-trappy
As you know the issue you raised was not a "real" issue since you were using a really old version of Flash Multi to update the firmware. As pointed out in the release notes of v1.3.1.65, in order to gain 5KB of flash space we have changed the tooling which means that you must use one of the most recent version of FlashMulti (v0.6.1 currently) to flash any v1.3.1.65+ firmwares.
To make it more obvious I've added the Flash Multi version to use in each release notes from v1.3.1.65 and up.

**Comment by pascallanger** [comment]
@mikeller
I do have a FrSky X9 Lite to test with a TBS module.
1. The TBS module due to the case does not fit in the X9 Lite... You have to open the module to connect it. For a proper usage you surely need to make/print some parts to get it to fit permanently on the radio. I think TBS should add a note/warning on their selling page.
2. The telemetry does not work right away due to a high load from the radio.
3. I confirm that my previous advice to short the output diode works:
  - ![20210131_183753](https://user-images.githubusercontent.com/6367598/106392865-1f1b8780-63f4-11eb-9808-16243a724d1e.jpg)
  - ![image](https://user-images.githubusercontent.com/6367598/106392684-3c9c2180-63f3-11eb-8ef1-fd0ab09ea7b3.png)
  - As you can see I've used a simple plier to do the short:
  - ![20210131_183822](https://user-images.githubusercontent.com/6367598/106392869-22167800-63f4-11eb-9ba9-3523e7ae3ace.jpg)
  - ![20210131_184039](https://user-images.githubusercontent.com/6367598/106392876-25116880-63f4-11eb-8e9e-dedeb8eace85.jpg)
4. Adding a 1K resistor in parallel of the diode makes the trick as suggested previously:
![20210131_185257 (1)](https://user-images.githubusercontent.com/6367598/106393162-d1078380-63f5-11eb-873f-9b0c42166aa5.jpg)

**Comment by ryancummings** [comment]
Confirmed working on x9 lite s with multiprotocol firmware 1.3.1.92 after adding a 1k resistor in parallel with the output diode as above. Thanks!

![16121301497871708854663743863121](https://user-images.githubusercontent.com/16618301/106399194-343cea00-63e5-11eb-8b3f-a598cbfa0b35.jpg)

**Comment by mikeller** [comment]
@pascallanger:

1. I think TBS is making it plenty clear that an adapter is needed:

![image](https://user-images.githubusercontent.com/4742747/106451733-df37cb80-64eb-11eb-924c-4d9606b9bb25.png)

2. Can you define what you mean by 'high load from the radio'?
3. it did not work for me when I tried it last time - but at that time I was using newer 1.3.1.92 multiprotocol firmware that still seems to not be working with this hardware (I used `flash-multi-0.6.0`, which was the latest version available when I downloaded the multiprotocol firmware). I will test again, but as said before, if this works with older firmware then the solution of adding an additional pull up that - unlike shorting out the diode - does not make it impossible to use the bidirectional capabilities of the S.Port pin should work as well, and will be preferrable as a permanent solution (could probably be included on the adapter board that comes with the X9 case for the TBS MPM).

**Comment by pascallanger** [comment]
I think you just haven't done the test correctly... The multi version has nothing to do with it since it's a hardware issue.

The end solution is to change the 10K resistor by a 1K:
![20210201_131005](https://user-images.githubusercontent.com/6367598/106457210-ebda0680-648e-11eb-8e98-88e897105922.jpg)

Which is why for the same radio other modules work and not the TBS which uses a different value. I've already informed the manufacturer which will correct the next batch.

**Comment by mikeller** [comment]
@pascallanger:

> I think you just haven't done the test correctly... The multi version has nothing to do with it since it's a hardware issue.

Yes, I tested with the wrong version of the firmware, as confirmed in https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/issues/491#issuecomment-765121754.

> The end solution is to change the 10K resistor by a 1K:

Yes, as I'd stated from the beginning, using a stronger pull-up is the correct fix.

**Comment by pascallanger** [comment]
@mikeller 
Should I even reply to this...
You are wrong from begining to end...
But since you are so great I would have expected you to solve this issue a lot faster! You have all the elements from at least Dec 23rd... I only purchased a X9 Lite to troubleshoot this issue and really disapointed that my first assumption was correct. You can't imagine the number of hours that hev been spent in the background due to this issue.
Anyway I'm closing here and won't respond anymore.

**Comment by mikeller** [comment]
@pascallanger: Saying 'you are wrong' without any explanation and at the same time refusing to comment any more just confirms that I was right.
But I don't see any need to be hostile about this.
