### ISSUE TITLE
Support Easycopter V4 COLIBRI

### ISSUE THREAD

**Issue by valfa14** [pascallanger/DIY-Multiprotocol-TX-Module#495]
Hey, I've tried to connect Easycopter V4 COLIBRI to J6pro but without success.
Receiver is NE260A RX-06, TXs TX16s/TX18s

![b_31](https://user-images.githubusercontent.com/11790557/103202891-f5060f80-48f3-11eb-9c83-0713eae62b74.jpg)

Any hints?

**Comment by pascallanger** [comment]
No idea... If you have tried all protocols and sub-protocols then the next step is to open the radio to see what's inside by taking good quality and close up pictures of where the antenna is connected.

**Comment by stanekTM** [comment]
I have an identical transmitter, it should contain CYRF6936 and DSM protocols.

**Comment by valfa14** [comment]
![Uploading Screenshot 2020-12-28 at 13.10.26.png…]()

**Comment by valfa14** [comment]
<img width="402" alt="Screenshot 2020-12-28 at 13 10 26" src="https://user-images.githubusercontent.com/11790557/103213498-1f64c680-490e-11eb-8abc-d4cdddeeae8e.png">

**Comment by stanekTM** [comment]
Oh, the same packaging and different electronics.

**Comment by pascallanger** [comment]
If you are willing to reverse this protocol, you can connect a SPI analyzer on the RF board and do some dumps.

**Comment by pascallanger** [comment]
@valfa14 Should I close this issue?

**Comment by valfa14** [comment]
@pascallanger Sorry, I didn't have time to provide you all information that you need. I will get back to this problem right after I will test all available sub-protocols.
