### ISSUE TITLE
Bind Flysky probleme

### ISSUE THREAD

**Issue by tipouic** [pascallanger/DIY-Multiprotocol-TX-Module#5]
Hi Pascal,
I use the last code and I don't bind, witch the protocol FLYSKY, on this platine [URL="http://www.banggood.com/WLtoys-F949-Airplane-Spare-Parts-Receiver-Board-p-959681.html"]http://www.banggood.com/WLtoys-F949-Airplane-Spare-Parts-Receiver-Board-p-959681.html[/URL].
Actualy, I use this old code [URL="https://github.com/shadow974/TxAdapter"]https://github.com/shadow974/TxAdapter[/URL]. I compared them but I can not find a difference. I have a friend that runs with one of your old code that works (before you start the github).
Is this an error in generating the id?

**Comment by pascallanger** [comment]
Hi Tipouic,
Like stated on RCGroups, I'm using these WLToys F939/F949 bricks as well. It works perfectly fine with the multi firmware on Flysky/Flysky. I'm flying them every WE indoor on home built models: a micro shock plane or micro wing.
I don't know the other code you are pointing out but there must be a difference... Multi is working perfectly fine.
- Pascal
