### ISSUE TITLE
HoTT protocol : binding process can not stop

### ISSUE THREAD

**Issue by TheIsotopes** [pascallanger/DIY-Multiprotocol-TX-Module#503]
since todays new release the bindprocess on my tx16s (opentx 2.3.11) are not stopping after binding or canceling the bind process.

**Comment by pascallanger** [comment]
Which protocol?

**Comment by TheIsotopes** [comment]
it affects the hott protocol, it gets stuck in the binding process.

**Comment by pascallanger** [comment]
In fact, it was never possible even in previous versions to end the bind unless there a RX responded to the bind.
This is fixed in v1.3.2.7, test version available here: https://downloads.multi-module.org/latest-test/
