### ISSUE TITLE
Mjx bugs 2 support? 

### ISSUE THREAD

**Issue by LastRizes** [pascallanger/DIY-Multiprotocol-TX-Module#509]
Hi, I found it a bit odd that only bugs 3 is supported and the second one is not.  I think it's a great idea if you can support him!

**Comment by pascallanger** [comment]
2 options to get this protocol added:
- do SPI captures on the TX and post them here
- ship the TX + quad for protocol analysis (preferred method). PM me on RCGroups (user hpnuts) if you are willing to do it.
