### ISSUE TITLE
Low power setting on opentx

### ISSUE THREAD

**Issue by dperry20** [pascallanger/DIY-Multiprotocol-TX-Module#51]
Does the low power setting on opentx actually change the power setting?

Also I installed the 4in 1 in taranis ex9. When I use the second module, is the first module turned off?

**Comment by sukoshi1507** [comment]
you need to shut the internal RF module in the appropriate setting

**Comment by pascallanger** [comment]
"Does the low power setting on opentx actually change the power setting?"
Why would you think that there is this option if it would not actually doing something?
Answer is yes...
