### ISSUE TITLE
On TX16S Frsky X2 D16 not binding with Frsky XM+

### ISSUE THREAD

**Issue by jdowdle** [pascallanger/DIY-Multiprotocol-TX-Module#511]
Bind does not look normal.  There is no response of leds until binding stops after several cycles, then green lite goes out.
cycle power, not bound.  Repeats on 2 new units.  Found this:  https://www.reddit.com/r/Multicopter/comments/j6nw6h/problem_binding_frsky_xm_to_radiomaster_tx16s/
which is the same problem.  It says solved, not really.  I find the X mode works, and the firmware which the author of link says is a fix, actually rolls back to X mode frsky, so X2 still does not work.
Interesting thing, I have a Horus X12S, with newest RF firmware, it works fine with X2 firmware XM+ receiver.
In my experience new Frsky receivers are received with older X firmware, and unless updated to X2, this issue will not show up.  I update to X2 because I made the mistake of updating my Horus RF module.  I will probably roll back to X until some fix is found.
I thought you might want to know.
If you need me to test any build/fix, let me know.
thanks.

**Comment by HazzaHFPV** [comment]
I have no problems binding with XM+ using FrSky X2 on my MPM in a Jumper T16.

However, I needed to increase the distance between TX and Rx a little more than was necessary with FrSky ACCST v1.7 on the same receiver.
I also found that frequency tuning is not always consistent on XM+ receivers. So I do recommend carrying out the frequency-fine-tuning procedure on the Multiprotocol-Module
