### ISSUE TITLE
change in lines to modify in instructions

### ISSUE THREAD

**Issue by tedbmoss** [pascallanger/DIY-Multiprotocol-TX-Module#52]
CompiIing and programming stm32
I find these lines instead of those in instructions to modify . sorry for my ignorance in posting.
/* void __irq_usart2(void) {
    usart_irq(&usart2_rb, &usart2_wb, USART2_BASE);
}

void __irq_usart3(void) {
    usart_irq(&usart3_rb, &usart3_wb, USART3_BASE);
}
*/

**Comment by pascallanger** [comment]
I'm not sure what you are looking for. The above is what's needed to be done...

**Comment by tedbmoss** [comment]
yes taking out these lines works but the instructions have &usart2_wb, &usart3_wb  missing so I guessed that was correct. I know little about programming, just enough to get in trouble.
