### ISSUE TITLE
Traxxas Link 2218x

### ISSUE THREAD

**Issue by buzkill420** [pascallanger/DIY-Multiprotocol-TX-Module#520]
I would like to contribute trying to reverse the protocol. Any help would be appreciated on going about creating dump files for the you.
Any resources available?  Thanks

**Comment by buzkill420** [comment]
![20210208_170222](https://user-images.githubusercontent.com/43829122/107301120-aa69ce00-6a2f-11eb-9523-f8925ce9bab3.jpg)

**Comment by buzkill420** [comment]
![16128729783612632995553126643520](https://user-images.githubusercontent.com/43829122/107362434-9a80d700-6a8d-11eb-9a9a-70934c35c9e7.jpg)
I'm guessing transmitter isimportant as well!

**Comment by pascallanger** [comment]
To make dumps, you need a logic analyzer (compatible Saleale 8CH cheap on ebay), solder it on the TX SPI bus (bus between the micro controller and the cyrf6936) to capture the signals clk, cs, mosi, and miso.
From there, we can try to understand the protocol.

**Comment by pascallanger** [comment]
Will you provide dumps or should I close?

**Comment by buzkill420** [comment]
I never got an analyzer... a bit pricey for me at the moment. You can close
and i can reopen if and when i get one.  Thanks

**Comment by pascallanger** [comment]
A logic analyzer is $6 on ebay... But I'll go ahead and close it for now.
