### ISSUE TITLE
ExpressLRS

### ISSUE THREAD

**Issue by buzkill420** [pascallanger/DIY-Multiprotocol-TX-Module#533]
is the multi-protocol module capable of running ExpressLRS or bind with LRS receivers? Assuming they are 2.4ghz receivers.

Cheers

**Comment by pascallanger** [comment]
No idea...

**Comment by buzkill420** [comment]
> No idea...
Assuming you know what I'm talking about...
https://github.com/ExpressLRS/ExpressLRS

**Comment by kilrah** [comment]
No, uses a different chip from the 4 in the MPM.
