### ISSUE TITLE
Can't bind Eachine E010 (MJXq - E010 protocol)

### ISSUE THREAD

**Issue by toyproua** [pascallanger/DIY-Multiprotocol-TX-Module#539]
Can't bind Eachine E010 (MJXq - E010 protocol)
Last correct working firmware is 1.3.0.47
TX - Jumper t12 + jp4in1 module

**Comment by benlye** [comment]
E010 working fine here with recent firmware up to and including current master.  Have you tried changing the frequency tuning?

**Comment by toyproua** [comment]
yes I've tried +-20 points. 
I've tried one more time a little more and... its working! thanks a lot!
