### ISSUE TITLE
Silkscreen issue C101/C102/C103, Multi-STM 1.0t

### ISSUE THREAD

**Issue by ExplodingLemur** [pascallanger/DIY-Multiprotocol-TX-Module#54]
The tantalum caps (C101, C102, and C103) have no polarity indicated on the silkscreen.  It's possible to determine by carefully examining the PCB to see which pads are joined to the ground plane, but some extra indication wouldn't hurt.

**Comment by pascallanger** [comment]
I've manually added the capacitor polarity indication on the silkscreen for v1.0t and v0.8t: https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/docs/BOM_DIY_STM32%20&%20Schematic.md#bom-diy-stm32-pcb-v10t---the-usb-version
Let me know if it looks ok for you.
An new PCB will get out shortly so I've asked Martin our PCB designer :-) to include it.

Thanks, Pascal

**Comment by ExplodingLemur** [comment]
Thanks!
