### ISSUE TITLE
LANSU S&T 

### ISSUE THREAD

**Issue by knoopx** [pascallanger/DIY-Multiprotocol-TX-Module#541]
Hi there, just got two new RC cars, one is a brushless touring "ZD Racing Rocket S16" and the other one brushed crawler "HBX 2098B Devastator". Just realised receivers are compatible between them. After disassembling both I found one its using one of the LT8900 variants, probably the LT8920 so I plugged in the logic analyser and captured some data via SPI. Looks like the data rate is 62.5kbps. Can we emulate using any of the existing modules?

Attaching a capture of the bind+idle.

[Logic2 Capture](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/files/6109409/lansu.sal.zip)

![image](https://user-images.githubusercontent.com/100993/110491947-063c7b00-80f2-11eb-9c46-ca971f305192.png)

![image](https://user-images.githubusercontent.com/100993/110492006-13f20080-80f2-11eb-89ab-9b2011b6e7ec.png)

![S20210223_002](https://user-images.githubusercontent.com/100993/110491801-e907ac80-80f1-11eb-81b5-f70d319eef99.jpg)

**Comment by knoopx** [comment]
I've got no SDR, but I would like to get one for further RF hacking. Does a 2.4ghz capable under 50€ SDR exist? Any recommendation?

**Comment by pascallanger** [comment]
I'm not aware of any cheapSDR which can do 2.4GHz unless you do like on this article and purchase a cheap radio SDR and put in front of it a downconverter: http://blog.cyberexplorer.me/2014/01/sniffing-and-decoding-nrf24l01-and.html
I'm using a ADALM-Pluto.

**Comment by knoopx** [comment]
Ok, got myself a hackrc (clone). Will learn and report my findings later.

**Comment by knoopx** [comment]
Just received the HackRF. After powering the RX#1, it starts sending bind requests at 2404.4Mhz. When powering TX#1 and binding, it starts to frequency hop on 7 freqs at 2404.4Mhz, 2423.4Mhz, 2433.4Mhz, 2443.4Mhz, 2453.4Mhz, 2463.4Mhz and 2473.4Mhz. TX#2 binds and hops on 5 freq only (2404.4Mhz, 2423.4Mhz, 2433.4Mhz, 2443.4Mhz and 2463.4Mhz). 

![image](https://user-images.githubusercontent.com/100993/111779336-4d76f880-88b6-11eb-83ec-c8af7d402f8e.png)

Unfortunately looks like it uses >1mhz bandwidth for transmission...

![image](https://user-images.githubusercontent.com/100993/111780770-21f50d80-88b8-11eb-841b-3c69b7031978.png)

**Comment by zakkhoyt** [comment]
Hey @knoopx . I see this thread has been closed for years, but was wondering if this ever got any traction? It sounds like ">1mhz bandwidth for transmission..." is a no. 

I've been trying to bind to what looks like the same thing (Haiboxing HBX-18859a). After disassembling my Tx, this thread is really the only info I was able to find. 

![hbx18859a](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/assets/2229408/245369c0-dff3-499e-afcf-4e228b65d48a)


Thx for putting in the effort to RE this stuff.

**Comment by knoopx** [comment]
Hey @zakkhoyt yeah, none of the built-in multiprotocol chips is able to transmit at that bandwidth.

**Comment by dogesTV** [comment]
![e303e9c8-6fa2-4721-9e30-f814b84adf47](https://github.com/user-attachments/assets/2816d9c9-b2b1-4b97-b89a-30d64a5f4817)
![98e72633-0c8d-42cb-9757-577ce5213601](https://github.com/user-attachments/assets/35960bc1-58d8-4fca-b330-1202a2c7c6fa)
I have simmular pcb but there isnt any chip only the main one (it doesnt have text the main one)
