### ISSUE TITLE
Why internal TX16S module is not able to bind AFHDS but external (iRangeX) does?

### ISSUE THREAD

**Issue by prikrylm** [pascallanger/DIY-Multiprotocol-TX-Module#544]
Tested on TX16S, with the external module iRangeX. The same radio, the same TX module firmware, the same binding process. But internal module is unable to bind AFHDS. Tried on FS-R9B and FS-GR3E.
Where am I making mistake?

**Comment by pascallanger** [comment]
It sounds really strange. Unless the A7105 is defective on the internal module?
The Flysky protocol is there since years and I'm using it frequently to fly indoor...

**Comment by prikrylm** [comment]
Yes it is strange. In addition binding AFHDS 2A works without problems on both TX modules.
Is there a way to check if the TX chip is defective? 

Otherwise, this "problem" has no priority. I use AFHDS very rarely.

**Comment by prikrylm** [comment]
Definitely some hardware problem. Another TX16S with the same TX module firmware is able to bind AFHDS receivers.
