### ISSUE TITLE
Flysky Telemetry Warning all the time

### ISSUE THREAD

**Issue by stefan73** [pascallanger/DIY-Multiprotocol-TX-Module#546]
Problem: Single/few lost packages on Flysky 2A lead to a "Telemetry lost", subsequent packages to "Telemetry recovered" messages in combination with OpenTX. This makes the radio yell practically all time, if you have a bit of distance to the model.

Where does it occur: Tried this on current release and 1.3.2.61 as well as older releases. Used a Jumper 4in1 Module as well as Jumper T-lite.

Intended behaviour: Telemetry warnings should not occur below a certain time threshold where telemetry is lost (e.g. 5sec; compare to CRSF implementation in opentx).

**Comment by pascallanger** [comment]
This alerts are in the OpenTX code. I would recommend that you open an issue on their github page.
