### ISSUE TITLE
Component labeling

### ISSUE THREAD

**Issue by ExplodingLemur** [pascallanger/DIY-Multiprotocol-TX-Module#55]
It might help a bit to label components consistently with regards to the side of the board they are located on.  Such as all components on one side be labeled 101-199 (C101, C102, C103) and all components on the other side be labeled 201-299 (C201, C202, C203, C204, etc).
I don't use Eagle but if you'd accept a pull request with KiCAD design files I can import and update.

**Comment by pascallanger** [comment]
An new PCB will get out shortly so I've asked Martin our PCB designer :-) to include your remark.

Thanks, Pascal
