### ISSUE TITLE
Can’t bind to FrSky R-XSR F.Port version

### ISSUE THREAD

**Issue by aa-calvo** [pascallanger/DIY-Multiprotocol-TX-Module#552]
Hi,

I’m not being able to bind my R-XSR receiver, running ACCST D16 v2.1.1 (F.Port firmware update only), to my Jumper T18 radio, with the module running Multiprotocol v1.3.2.61. 

I know there are some old issues about incompatible firmware versions, but I don’t know which firmware version do work and where to download it from. Also, I would prefer it the firmware supported the F.Port protocol for telemetry.

Any help is appreciated, thanks!

**Comment by aa-calvo** [comment]
It works with RXSR-FPORT_LBT_ACCST_191128.frk firmware.

It can be downloaded from FrSky download page: https://www.frsky-rc.com/r-xsr/. Where it says “ History firmware DOWNLOAD (not compatible with v2.x.x)”

**Comment by HazzaHFPV** [comment]
It also works with ACCST v2.1.0 when you choose FrSkyX2 Protocol in the Radio. There is no difference in telemetry between FPort and "normal" S.port Firmware. That ist only a difference in communication between receiver and flight Controller.

**Comment by aa-calvo** [comment]
I tried using FrSkyX2 and I was able to bind successfully, but I think there is a problem with the F.Port telemetry on version 2.X.X. 

I don’t think it’s related to the multi protocol transmitter because I observed the same problem on a Taranis Q7. It could be either Arducopter or the telemetry script.
