### ISSUE TITLE
How did you get the protocols?

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [pascallanger/DIY-Multiprotocol-TX-Module#555]
How did you get the protocols for the drones? Reverse engineering?

**Comment by pascallanger** [comment]
The potensic A20 protocol is already available: https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/Protocols_Details.md#Potensic---51
Yes reverse engineering.

**Comment by ErfolgreichCharismatisch** [comment]
Can you explain how to use it with python? so without your hardware, just a wifi module plus python.

Also, I am curious how you reverse engineered the protocol.

**Comment by pascallanger** [comment]
That's not how it works... If it was that simple... A wifi module won't be able to be used here.
You need a SDR.

**Comment by ErfolgreichCharismatisch** [comment]
In this case it is, because the drone can be controlled via smartphone app, which connects via wifi.
Who did the reverse engineering and can tell me a thing or two?

**Comment by ErfolgreichCharismatisch** [comment]
Can you help me out?

**Comment by pascallanger** [comment]
You need to understand the content of the packets. Move throttle and look in the packets what's changing, stake thing for all other channels and features. One you have identified most of the bus then you can reproduce what's being sent.

**Comment by ErfolgreichCharismatisch** [comment]
How do I convert these packets into python code?
