### ISSUE TITLE
Problem after update ...

### ISSUE THREAD

**Issue by MSchrotter** [pascallanger/DIY-Multiprotocol-TX-Module#563]
hello,

I have a irangex + and made an update (v1.3.2.61) via usb but now it is not working. I want to use it in ppm mode with jeti. the green light is permanent on and to switch the groups is not possible. Binding with the receivers is not possible animore.
How can I bring it back to work? Any idea?

thx/bg Markus

**Comment by pascallanger** [comment]
For PPM, you need to compile the code by yourself to indicate which protocols you want to assign to which position of the dial.
This is done in the _config.h file along with the number of banks, protocols needed, details of your radio (and more):
https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/34f16b0b66519dd39f261db4824c94b76af7bba6/Multiprotocol/_Config.h#L369
Here are the compilation instructions: https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/docs/Compiling_STM32.md
