### ISSUE TITLE
Multiprotocol Receiver

### ISSUE THREAD

**Issue by devanesanandrews** [pascallanger/DIY-Multiprotocol-TX-Module#577]
Its just a thought, 

Just like having an  Multi Protocol Transmitter.

it would be great to have an Multi Protocol Receiver,  so with the same hardware we can use it as a receiver.

With reduced modules, we can have single protocol reciever.

**Comment by HazzaHFPV** [comment]
It has been mentioned before #512

**Comment by devanesanandrews** [comment]
alright then, i ll close it. Thank you.
