### ISSUE TITLE
LONG SHOT: are imex receivers supported?

### ISSUE THREAD

**Issue by wx4cb** [pascallanger/DIY-Multiprotocol-TX-Module#582]
I have a couple of IMEX brushless truggys and i cannot get on with the stupid pistol grip controllers.

i was wondering if i could bind my tx16s to their receivers. unfortunately the ICs on the board are lathered in conformal coating and do not have numbers on them - it appears they're ground off :(

here are links to the receiver and the truggy itself from the local rc store.

https://www.gravesrc.com/imex-ninja-1-16-truggy-rtr-with-wheelie-bar.html
https://www.gravesrc.com/imex-shogun-ninja-brushless-esc-reciever.html

**Comment by pascallanger** [comment]
Without access the TX and RX there is nothing I can do.
