### ISSUE TITLE
RadioLink R8EF (RX) failsafe

### ISSUE THREAD

**Issue by jozefklacko** [pascallanger/DIY-Multiprotocol-TX-Module#584]
Hi,
When  I turn off RadioMaster TX16S, or when I am very close to RX - RadioLink R8EF throttle to full. And that is bad. Probably goes to failsafe. Comparing to when I am using RadioLink T8FB (TX), when turn it off, throttle is zero - failsafe OK. 
It does not matter which TX I used last. Behavior is the same TX16S+R8EF or T8FB+R8EF. There is no failsafe config in OpenTX for RadioLink. RadioLink has Android/Windows APP to configure TX and failsafe on TX.

**Comment by pascallanger** [comment]
Failsafe for CH1-CH8 is set through CH9-CH16, please read the doc: https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/Protocols_Details.md#radiolink---74
Pascal
