### ISSUE TITLE
Irx4 lite no serial input 

### ISSUE THREAD

**Issue by rayb106** [pascallanger/DIY-Multiprotocol-TX-Module#586]
Hi All I’m new to droning and just bought a tiny hawk s I also have a 5”Quad which I can connect to easily, but I’m trying to bind to my tiny hawk with the irx4 lite on my frsky xlite pro, I’ve noticed after updating the firmware I’ve lost the multi option and the irx4 has a solid green light and slow flashing red light, it seams to have no serial input now, I’ve also updated the frsky firmware too for the frsky site

**Comment by pascallanger** [comment]
The radio must be updated with OpenTX not a firmware from frsky which doesn't support the multi module. You also need to make sure that the OpenTX build you use is including multi sport when selecting it in companion TX.

**Comment by rayb106** [comment]
> The radio must be updated with OpenTX not a firmware from frsky which doesn't support the multi module. You also need to make sure that the OpenTX build you use is including multi sport when selecting it in companion TX.

Thanks for the reply, how do I know if it includes multi sport when selecting ? Also I can't remember how to get the boot loader up from start on the frsky pro, I've held all the buttons on the d-pad while turning on

**Comment by pascallanger** [comment]
Download companion TX, when selecting your radio you're there will be some choices with one of the choices being multi then power of your radio, plug it to the computer and flash it within companion TX. There are plenty of videos on the web to do this.

**Comment by kilrah** [comment]
There's no option anymore, multi support is always in.

**Comment by rayb106** [comment]
I noticed this when trying to set up a new radio, just got to find the right firmware now for my frsky xlite pro

Sent from my iPhone

On 3 Jun 2021, at 09:12, Andre Bernet ***@***.***> wrote:

﻿

There's no option anymore, multi support is always in.

**Comment by rayb106** [comment]
Thanks guys all sorted out now
