### ISSUE TITLE
file naming convention at https://www.multi-module.org/using-the-module/firmware-updates/firmware-files is wrong

### ISSUE THREAD

**Issue by cbf123** [pascallanger/DIY-Multiprotocol-TX-Module#589]
Hi...the file naming convention at https://www.multi-module.org/using-the-module/firmware-updates/firmware-files still includes the erskytx/opentx options which are no longer applicable.  I think that they should be replaced with "serial".

**Comment by benlye** [comment]
I finally got around to doing this.
