### ISSUE TITLE
Feature Request: Protocol Scanner

### ISSUE THREAD

**Issue by HippoDan** [pascallanger/DIY-Multiprotocol-TX-Module#594]
I would really love to be able to have the module sample some of the original toy transmitter and then make it's best guess on the protocol.  I have a lot of random things I'm hoping are already included on the module, but no way to tell if they are without trying every protocol.  

Even for well known protocols it would be a huge time saver.  Or, an interactive LUA script what would ask you to turn on toy transmitter, wiggle stick, bind, etc for best guess of protocol.  Don't know if it's possible, but it would be great.

Thanks!

**Comment by pascallanger** [comment]
This can be done using a LUA script on OpenTX.
Pascal
