### ISSUE TITLE
R-xsr receiver

### ISSUE THREAD

**Issue by rayb106** [pascallanger/DIY-Multiprotocol-TX-Module#599]
Hi All,

I'm trying the bind my new r-xsr mini d16 receiver with my frsky (Eu FW from frsky site)lite pro x ( has the latest open tx EU) rx1 on mamba f722 mini set up as rx port (latest fw from mamba site). 

I'm following the bind instructions,when connected to power the receiver starts up with solid blue light and red flashing light, so it's in Sbus mode and not binded with anything. When holding the f/a button and connection power through a smoke stopper it then has  the green light is solid as well as the blue and red, radio is in bind after the quad is powered and f/s is held in, once I take my radio out of bind and power down the quad, when I re connect it the red is still flashing and blue light is solid. 

I also have a ixr4 module which is set up for all other differ t type of connections 

Anybody else has this issue, need to get the Atto off the ground 😭😭

**Comment by HazzaHFPV** [comment]
What file did you flash on the R-XSR exactly?

**Comment by rayb106** [comment]
Hi Harry,

I've sort it now I had to flash the r-xsr with the older firmware, as I've seen the new r-xsr come with new firmware which stops it working the my frsky-lite x pro, but all working now thanks

**Comment by HazzaHFPV** [comment]
Awesome 👍
