### ISSUE TITLE
Runcam nano 2 racer and runcam tx200u

### ISSUE THREAD

**Issue by rayb106** [pascallanger/DIY-Multiprotocol-TX-Module#600]
Hi All,

I've got the above and have it working but I'm not seeing any think in the osd I am getting video feed and can see through the runcam on my goggles but I'm not seeing the name of craft, battery power,video channel, I have a matek F722 mini se, the tx200u vtx is connected to t4, 5v and G (to the left of T4) then the nano 2 connects into the vtx but I still have a port on the back which says menu which I've wired to the vtx port, but still get no info through my goggles. 

Please see pics attached   ![image](https://user-images.githubusercontent.com/85273394/126081604-ac17256e-6410-49de-a831-3217d8d4f332.jpeg) ![image](https://user-images.githubusercontent.com/85273394/126081630-825fbb75-7383-46ea-9f21-138b1e82e857.jpeg)

**Comment by pascallanger** [comment]
I don't want to be rude but what is the relation with multi on this issue?

**Comment by rayb106** [comment]
Ah sorry I though I was creating a new issue

**Comment by HazzaHFPV** [comment]
Yepp you created a new issue, but it has, unfortunately, nothing to do with the multi-protocol Module. I might be able to help though if you drop me a short email (email can be seen in my profile)
