### ISSUE TITLE
Channel order issue w/ TX16s & Crossover XR602T-F2 rx

### ISSUE THREAD

**Issue by Daniel366Cobra** [pascallanger/DIY-Multiprotocol-TX-Module#602]
Transitioning from Radiolink to OpenTX. The Crossover receiver is using FrSky D16 protocol. Bound without problems.

Using latest stable FW for OpenTX (2.3.14) and MM (1.3.2.86). Configured my TX to have inputs, mixers and outputs all in AETR order, the MultiModule FW is also AETR. However, the outputs come from the RX (as they have to be set in Betaflight) in ETAR order.
When reordering mixers to TAER while keeping the MM firmware at AETR, the correct order in Betaflight becomes AETR.

I tried searching the forums but haven't found a comprehensive answer,
I feel like there is a simple solution I overlooked somewhere. Please help.

**Comment by pascallanger** [comment]
Which protocol are you using? Please post a pictures of the protocol page and mixers.
If the protocol is doing a transformation between input/output you have an option to disable through the GUI using the Disable Channel map box.

**Comment by Daniel366Cobra** [comment]
I use "Frsky X D16" under internal RF. I believe it does not have the checkbox for disabling channel remapping, at least I have not seen it.
Here are the photos of my channel order and MM protocol.
 
![in](https://user-images.githubusercontent.com/4602260/128702082-16e65d9f-4049-4e3b-a019-c48191e57522.jpg)
![mix](https://user-images.githubusercontent.com/4602260/128702085-71e1bfba-4fdb-47b6-93a6-153e7a0775db.jpg)
![MMSetup](https://user-images.githubusercontent.com/4602260/128702086-9be5c184-ff0c-4ee7-81b7-2ebd35884f95.jpg)
![out](https://user-images.githubusercontent.com/4602260/128702088-af1ecb73-f7ec-4635-a910-a432b36f8b85.jpg)

**Comment by HazzaHFPV** [comment]
Have you also selected the correct "Default channel order" within the OpenTX  Radio Setup?
![20210809_150040](https://user-images.githubusercontent.com/57357647/128710358-7e3f17b5-d36b-4c23-bcd5-853f862abdc3.jpg)

**Comment by Daniel366Cobra** [comment]
> Have you also selected the correct "Default channel order" within the OpenTX Radio Setup?
> Because on mine it works just as it should when everything is selected correctly (Frsky D16 as well as all other protocols)
> ![20210809_150040](https://user-images.githubusercontent.com/57357647/128710358-7e3f17b5-d36b-4c23-bcd5-853f862abdc3.jpg)

Yes, mine is also set to AETR there.

**Comment by timtuxworth** [comment]
Don't mess with the channel order on a multi-protocol radio. The module expects the channel order (usually AETR) and you will break things if you change it. I'm not sure about FrSky but for Spectrum, the module actually translates all your AETR inputs and mixes to TAER before sending to the receiver. If you change the transmitter you mess that up.
https://youtu.be/QUcCOqLcOj0
