### ISSUE TITLE
Sanwa SD-10G and FRSky xsr 2016 binding issue

### ISSUE THREAD

**Issue by stefanofalconetti** [pascallanger/DIY-Multiprotocol-TX-Module#61]
Hi Multiprotocol Team,

I'have been trying to bind my Sanwa SD-10G with an FRSKY XSR 2016 receiver with NON EU firmware for several days now, with luck. I have a multiprotocol board from Bangood ([http://www.banggood.com/2_4G-CC2500-A7105-Flysky-Frsky-Devo-DSM2-Multiprotocol-TX-Module-With-Antenna-p-1048377.html]) that I have updated with the latest firmware via the Arduino IDE, few days ago. This RX supports the D16 protocol and the multiprotocol board is connected to my tx via PPM trainer port (slave mode, so internal RF module is turned off). This tx port is declared to be PPM8 capable. I'm getting that it has 8 channels on that PPM signal. I have set the dial to #2 on the board, as 2 is FRSKYX protocol and tried all possible bind procedure. I'm attaching my _Config.h file. Changes I made are commented with "//Sanwa SD-10G"
I have also changed channels order to EATR (#define EATR). I have also reduced max channels to 8 max (My TX has 10). What I see when I try to bind is this:

1. I power the Tx on
2. I power on the multiprotocol module while pressing the bind button (I added a switch to power it off). Green led is solid on
3. I keep the rx bind button pressed while powering the rx
4. I release the bind button on the multiprotocol board
5. Multiprotocol board red led blinks fast 
7. After some seconds red led on multiprotocol board turns solid red 
8. Green led on rx goes green, red one turns off

As I spent some time sorting this out I wanted just to share with you. 

![sanwa ppm multiprotocol](https://cloud.githubusercontent.com/assets/23737586/24325392/32b74732-1198-11e7-8785-e73682d73c00.jpg)

Changes I made in _Config.h to make the bind part are below:

```
const PPM_Parameters PPM_prot[15]=	{
//	Dial	Protocol 		Sub protocol	RX_Num	Power		Auto Bind		Option
**/*	1	*/	{MODE_SFHSS,	0		,	0	,	P_HIGH	,	NO_AUTOBIND	,	0		},
/*	2	*/	{MODE_FRSKYX,	CH_8		,	0	,	P_HIGH	,	NO_AUTOBIND	,	-40		},**
/*	3	*/	{MODE_FRSKYD,	0			,	0	,	P_HIGH	,	NO_AUTOBIND	,	40		},	// option=fine freq tuning
/*	4	*/	{MODE_HISKY	,	Hisky		,	0	,	P_HIGH	,	NO_AUTOBIND	,	0		},
/*	5	*/	{MODE_V2X2	,	0			,	0	,	P_HIGH	,	NO_AUTOBIND	,	0		},
/*	6	*/	{MODE_DSM	,	DSM2_22		,	0	,	P_HIGH	,	NO_AUTOBIND	,	6		},	// option=number of channels
/*	7	*/	{MODE_DEVO	,	0			,	0	,	P_HIGH	,	NO_AUTOBIND	,	0		},
/*	8	*/	{MODE_YD717	,	YD717		,	0	,	P_HIGH	,	NO_AUTOBIND	,	0		},
/*	9	*/	{MODE_KN	,	WLTOYS		,	0	,	P_HIGH	,	NO_AUTOBIND	,	0		},
/*	10	*/	{MODE_SYMAX	,	SYMAX		,	0	,	P_HIGH	,	NO_AUTOBIND	,	0		},
/*	11	*/	{MODE_SLT	,	0			,	0	,	P_HIGH	,	NO_AUTOBIND	,	0		},
/*	12	*/	{MODE_CX10	,	CX10_BLUE	,	0	,	P_HIGH	,	NO_AUTOBIND	,	0		},
/*	13	*/	{MODE_CG023	,	CG023		,	0	,	P_HIGH	,	NO_AUTOBIND	,	0		},
/*	14	*/	{MODE_BAYANG,	BAYANG		,	0	,	P_HIGH	,	NO_AUTOBIND	,	0		},
/*	15	*/	{MODE_SYMAX	,	SYMAX5C		,	0	,	P_HIGH	,	NO_AUTOBIND	,	0		}
};
```

According to what is mentioned here (search for D16 non EU):

[Protocol details page](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/Protocols_Details.md)

See first two lines (I'm actually looking for using Futaba and RFSky)

I'd like to know how to share this so that others will not spend the same time in getting here. Is an issue the right place to do this ?

Thanks,

Stefano Falconetti  

[_Config.h.txt](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/files/870453/_Config.h.txt)

![sanwafinallysbus](https://cloud.githubusercontent.com/assets/23737586/24333949/cb0bb008-1261-11e7-9dd9-af117916235a.jpg)

**Comment by pascallanger** [comment]
Hi, It looks like it's working for you right? (so it's not an issue)
I think the best place if you want to keep this knowledge somwhere is to submit a pull request in the section "[How to for popular models](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/docs/Models.md)".
Pascal

**Comment by stefanofalconetti** [comment]
That's correct,

if you can explain to me how I cab properly document it, I can copy-paste
in a more suitable place.

Thanks,

Stefano Falconetti.

2017-03-28 9:30 GMT+02:00 pascallanger <notifications@github.com>:
