### ISSUE TITLE
Radiomaster TX12: Status no telemetry

### ISSUE THREAD

**Issue by ssdb1980** [pascallanger/DIY-Multiprotocol-TX-Module#613]
I can't bind to my receivers.. Optima7 or Fs-iA6 receiver. Update firmware and protocols tried fine tune the frequency 
Tried every number and I still can't bind.
Any ideas that could help?

**Comment by pascallanger** [comment]
Which radio master radio?
Which version of the module firmware?
Do you see the module version nearby the protocol selection?

**Comment by ssdb1980** [comment]
Radio master tx12  firmware is 2.3.14
Receiver fs-iA6 protocol Flsky2A and I have tried all subprotocols
Receiver optima 7 protocol hitec subprotocol optima.

**Comment by pascallanger** [comment]
You are not answering my questions...

**Comment by ssdb1980** [comment]
Am sorry am new to opentx so am trying here. I have radio master tx12
module firmware is 2.3.11
This is what I see on the setup page
Internal rf
Mode muti
Type hitec
Subtype optima
No I can't bind to any receiver I only have 2

**Comment by pascallanger** [comment]
Module firmware can't be 2.3.11... The module firmware is something like v1.3.2.86...
Can you do pictures of where you set the protocol?

**Comment by HazzaHFPV** [comment]
2.3.11 is the version of OpenTX. Module firmware should be shown in the Modell-Setup page where you set the protocol under "status" as Pascal suggests.

**Comment by pascallanger** [comment]
@HazzaHFPV  And on the second post he said that his radio is running OpenTX 2.3.14 so the information provided so far are not correct.

@ssdb1980 Please provide pictures of what you are doing.
Have you tried to upgrade the multi module firmware?

**Comment by ssdb1980** [comment]
@pascallanger yes 
![Screenshot_20210822-044411_Gallery](https://user-images.githubusercontent.com/88935567/130352451-9763bf7b-6191-4d8f-8e94-ed4d9d0d6e1a.jpg)
![Screenshot_20210822-044319_Gallery](https://user-images.githubusercontent.com/88935567/130352454-69fd04f0-4fc1-4b80-aeb4-73a4d255fc3b.jpg)
![20210822_024049](https://user-images.githubusercontent.com/88935567/130352456-82ef7f0d-c3b2-4c01-85da-1e3f283e8bca.jpg)

**Comment by pascallanger** [comment]
Ok it's broken since you have flashed the firmware correct?

**Comment by ssdb1980** [comment]
@pascallanger how did I fix it?

**Comment by pascallanger** [comment]
By telling the truth and what you've really done would help...

**Comment by ssdb1980** [comment]
I donwload all the updater files. I updated the bootloader will the radio was off and plug in to my computer though opentx companion 2.3  then turn it on to write firmware 2.3.14 to the radio then updated mult module to v 1.3.2.86

**Comment by pascallanger** [comment]
But before all that was the module working?

**Comment by benlye** [comment]
Could it be a 64Kb STM32?

**Comment by pascallanger** [comment]
That's what I think too. But I would like to know if the radio was working before the updates.

**Comment by ssdb1980** [comment]
@pascallanger no that is why I was doing the updating.

**Comment by pascallanger** [comment]
When was the radio purchased? It's it brand new out of the box?

**Comment by ssdb1980** [comment]
Yes it was band new

**Comment by pascallanger** [comment]
Hummmm brand new, ok good to know.
Try and old release like this one: https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/releases/tag/v1.3.1.59
After flashing it check the status line under the protocol.

**Comment by ssdb1980** [comment]
@pascallanger tried a few v1.3.230,v1.3.2.77, v1.3.1.77 v1.3.2.6 and v1.3.2.86 and still got nothing.

**Comment by pascallanger** [comment]
Please listen, I've said and have you the link to the 1.3.1.59 version. I expect that no build would work above this version.

**Comment by pascallanger** [comment]
By the way the TX12 only has a cc2500 RF chip so Flysky is not supported on this radio.
Only the protocols shown under this section are available: https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/Protocols_Details.md#cc2500-rf-module

**Comment by ssdb1980** [comment]
@pascallanger there are 34 on the link. So am not sure which one I need to download

**Comment by pascallanger** [comment]
I said earlier chose opentx noinv after it's up to you.
Here is the aetr: https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/releases/download/v1.3.1.59/multi-stm-opentx-aetr-noinv-v1.3.1.59.bin

**Comment by ssdb1980** [comment]
@pascallanger  
![16296372290346645825666546913678](https://user-images.githubusercontent.com/88935567/130356185-d9651070-be1a-441b-81a7-8a8ff2e35721.jpg)
This came when it tried it

**Comment by pascallanger** [comment]
Reduce the file name size after downloading the bin.

**Comment by ssdb1980** [comment]
I did to 1.31.59.bin and to 1.5.9.bin
Same error messages

**Comment by Miwer** [comment]
Had this happen to my TX12 bought off Banggood. Came with a C8 (64K) chip. After flashing the latest official image, same symptoms with message "no telemetry", and when I opened my radio, i could see the TX module blinking the SOS pattern.
Had to compile the firmware myself and was able to get it working again using normal flash procedure from SD card.
Thank you for the excellent guides on this issue. ;)

**Comment by pascallanger** [comment]
https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/docs/Compiling_STM32.md
And select the 64KB board.

We will add CC2500 64KB builds soon since both the TX12 and T8 are shipped with 64KB Flash chips...

**Comment by Miwer** [comment]
@ssdb1980 before you go through the hoops of compiling the firmware, please do yourself a favor, and CHECK that you have the wrong chip in your radio - use the information here: https://www.multi-module.org/basics/module-hardware/unsupported-modules
You need to make sure you have the C8 chip and not the CB chip. 
This is how mine looked inside:
![d6b27db1-f228-457c-8b93-d40680d5d6db_arrow](https://user-images.githubusercontent.com/145515/130519976-3d4a92d5-bbd3-47f2-b4e0-7b19765b1547.jpg)

**Comment by ssdb1980** [comment]
@Miwer this is mine

**Comment by ssdb1980** [comment]
![1629755999057230608538875433648](https://user-images.githubusercontent.com/88935567/130525090-dbadb457-2d88-46f5-9975-7f36b246a911.jpg)
@Miwer this is mine

**Comment by Miwer** [comment]
This is the one I compiled for mine. See if this will work for you. Use at your own risk (extract the zip file first)
[tx12-64k-aetr-1.3.2.88.bin.zip](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/files/7035253/tx12-64k-aetr-1.3.2.88.bin.zip)
MD5 checksum: cd7af135206e63cba5aea1cdd539fd3d

**Comment by ssdb1980** [comment]
@Miwer hey what is MDS checksum

**Comment by Miwer** [comment]
@ssdb1980 did you extract the zip file first?
Don't worry about MD5, you don't need it.

**Comment by ssdb1980** [comment]
@Miwer yes

**Comment by benlye** [comment]
Try the firmware file in this zip.  Make sure you extract the bin file from the zip before you copy it to your radio.  You may have to shorten the file name of the bin file.

This file was built using our standard GitHub release process, so should work.
[mm-cc2500-64-v1.3.2.89.zip](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/files/7041362/mm-cc2500-64-v1.3.2.89.zip)

**Comment by ssdb1980** [comment]
@benlye I get these messages when I try flashing
![16298325309875529041410323555996](https://user-images.githubusercontent.com/88935567/130676285-672ac83c-5134-41ed-b665-8d3fb52cbe25.jpg)

![16298324903168515066602597172079](https://user-images.githubusercontent.com/88935567/130676202-9b8347db-0177-486c-9b63-d1c5fe4bea04.jpg)

**Comment by pascallanger** [comment]
You can't flash the module through companion... You must cut the file to the SD card and flash it to the internal module using OpenTX under the SD card explorer.

**Comment by Miwer** [comment]
@ssdb1980 that is not how you flash the multi-module. 
Have a look at this video, and try again - skip the download portion, and use the file as recommended by benlye
https://www.youtube.com/watch?v=lg9zF92mapM

**Comment by ssdb1980** [comment]
Hey still getting error message. I   Want to thank all you guys for taking the time to help.
I have put in a ticket with radio master and order the 4in external module.
@Miwer @pascallanger @benlye

**Comment by Miwer** [comment]
@ssdb1980 what is the error you get in the screen of the radio when trying to flash the firmware?

**Comment by Miwer** [comment]
Well for what it's worth, I can confirm the file posted by benlye is working on my TX12 - also binding to receiver works.
@ssdb1980 I hope it works out for you somehow.
![2](https://user-images.githubusercontent.com/145515/130789619-ae040322-b755-43ad-afca-9dd046085e89.jpg)
![3](https://user-images.githubusercontent.com/145515/130789623-66eb0f2f-de1f-4c66-9dfa-7276abe84af1.jpg)

**Comment by krisdover** [comment]
Had the same issue with my RadioMaster TX12 using the **STM32 CC2500 only** download option (i.e. `mm-stm-cc2500-aetr-v1.3.3.0.bin`) from the Multi-module selection [download page](https://downloads.multi-module.org/). Even after finding this post and switching to the **STM32 CC2500 only - 64K** download option (i.e. `mm-stm-cc2500-64-aetr-v1.3.3.0.bin`) the module still didn't work (i.e. Status: No telemetry). The only thing that fixed it was the `mm-cc2500-64-v1.3.2.89.zip` file shared here by @benlye. 😅
