### ISSUE TITLE
there are new protocol need to bind in openTX please help

### ISSUE THREAD

**Issue by fpvstyle** [pascallanger/DIY-Multiprotocol-TX-Module#614]
we have a brushed FPV drone with new protocol and only able to bind with toy remote controller, the functions are great and cheap, we looking for specialist of TX module to help to solve the problem an able to bind in openTX radio, we can provide the  necessary file for you, and of course we would like to pay for your work, please let know if anyone able to help

**Comment by fpvstyle** [comment]
forgot leave the contact: SKYPE--fpvstyle email--max@fpvstyle.com

**Comment by pascallanger** [comment]
User contacted. Closing this issue.
