### ISSUE TITLE
Jumper t18 rf power

### ISSUE THREAD

**Issue by DimiDr0l** [pascallanger/DIY-Multiprotocol-TX-Module#626]
Hi, i own jumper t18 pro, opentx 2.3.14 internal rf v1.3.3.0, why rf power max 50mw?
where the power is 300mw?

**Comment by doctormess** [comment]
Same problem. I have a Jumper T18 running OpenTX 2.3.14 and multiprotocol module status V1.3.3.7 AETR. 

I select "Internal RF" and mode is MULTI, FRSKYR9, 915MHz.

In OpenTX the "RF Power" goes from 1.6mW to 50mW. It should go up to 300mW according to the Jumper T18 specs. Why does OpenTX not give me options up to 300mW?

**Comment by pascallanger** [comment]
Are you loading the correct fw? The T18 module firmware should not allow you to select any RF Power since their module is fixed.
https://downloads.multi-module.org/?jp-t18int

**Comment by doctormess** [comment]
Yes it is:  mm-t18int-aetr-v1.3.3.7.bin
RF power can be: 1.6mW, 2.0, 2.5, 3.2, 4.0, 5.0, 6.3, 7.9, 10, 13, 16, 20, 25, 32, 40, 50
Under the RF Power setting I have not ticked the boxes for: Bind on channel, Disable Telemetry, Low power mode
It does bind and operate an R9 Slim Plus ACCST receiver on work bench. Have not flown with it yet.

**Comment by pascallanger** [comment]
I'll check what I'm sending to OpenTX but it shouldn't propose that list. Anyway it won't do anything...

**Comment by doctormess** [comment]
Thanks I emailed Jumper and they were quick to respond and said, "The multiprotocol module doesn't support power settings. Please ignore this function on the radio."

OpenTX here on github said, "That power is returned by the multimodule, nothing to do with OpenTX"

**Comment by Ostay** [comment]
The SX1276 transmitter module built into the Jumper T18 Radio can get up to 100mw, but the latest update to the 5IN1 firmware is limited to 17dbm(50mw). I want to know why? Look forward to adding 20dbm(100mw) option in later versions, thanks!
