### ISSUE TITLE
New Module Version with ARM Cortex M

### ISSUE THREAD

**Issue by Alveran81** [pascallanger/DIY-Multiprotocol-TX-Module#638]
Chinese change Modul Version from STM32 MCU to ARM, firmware is ARM CORTEX-M !!!

https://www.banggood.com/IRangeX-IRX4-Plus-2_4G-CC2500-NRF24L01-A7105-CYRF6936-4-IN-1-Multiprotocol-ARM-TX-Module-With-Case-p-1225080.html?rmmds=myorder&cur_warehouse=CN

How can I Update my new Module? The Standard Version will destroy the module?

**Comment by pascallanger** [comment]
There is no difference... A STM32 has a ARM core... Just upgrade...

**Comment by Alveran81** [comment]
Upgrade Successfully. Thank you very much.
