### ISSUE TITLE
Range test mode in Flysky AFHDS2A

### ISSUE THREAD

**Issue by jmpblackfoot** [pascallanger/DIY-Multiprotocol-TX-Module#64]
I am running a Taranis X7 with OpenTx 2.2.0N365 and the Banggood 4 in 1 module with V.1.1.6.20.
Range test mode works with all protocols I have tried (including Flysky standard), except the FlySky AFHDS2A.
(Tested with Ebay "1-8000MHz-AD8318-RF-logarithmic-detector-70dB-RSSI-measurement-power-meter")

**Comment by pascallanger** [comment]
I don't see how it could not work with AFHDS2A in particular since the power settings (bind, range, low and high) are fully independent from the protocols.

**Comment by pascallanger** [comment]
Found an issue... Please test the latest version and report if it doesn't work.

**Comment by jmpblackfoot** [comment]
I just managed to try out the new version 1.1.6.21.
It works fine, thank you very much.

Jean-Marie Piednoir
