### ISSUE TITLE
Hott: enable mapping of channels to physical RX outputs

### ISSUE THREAD

**Issue by wimalopaan** [pascallanger/DIY-Multiprotocol-TX-Module#641]
The GR/SJ MC32 radio can enable a mapping on the RX side, so that a Hott-RX outputs the channles 8-16 to physical outputs 1-8.

So, when binding two receivers to the same MPM, one RX1 could outputs ch 1-8 on outputs 1-8 and RX2 could output ch 9-16 on outputs 1-8.

**Comment by pascallanger** [comment]
No idea how it could work. If you have access to a MC32 then try to capture the bind packet to see what's different.

**Comment by pascallanger** [comment]
No answer, closing the issue.
