### ISSUE TITLE
Trying to reduce number of protocols - no luck

### ISSUE THREAD

**Issue by nostromo123** [pascallanger/DIY-Multiprotocol-TX-Module#648]
Radio FrSky X10 Express 
OTX 2.3.14
Multi FW 1.3.3.0
Arduino IDE 1.8.18 under Debian Bullseye
flash-multi-0.6.1 under WIN 10

MPM module used

![RADIOBOSS JP4in1](https://user-images.githubusercontent.com/17964433/147408882-b3eecb8c-5c45-460d-b120-618a22dba57d.jpg)
![Jumper_clone 1](https://user-images.githubusercontent.com/17964433/147408900-d16a6c84-fde5-445e-b64c-52069763ffef.jpg)
![Jumper_clone 2](https://user-images.githubusercontent.com/17964433/147408902-c557ddb3-2224-4537-82a0-e6e15e49eabb.jpg)

In -Config.h changed AETR to TAER and disabled all protocols but MLINK and FRSKYx.
[_Config.h.txt](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/files/7777011/_Config.h.txt)

The Arduino IDE upload protocol tells me 'wrote and verified' for bootloader and firmware. 
[Neue Datei.txt](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/files/7777014/Neue.Datei.txt)

But I still got all 'disabled' protocols on the radio!?

I tried with 'usb support' enabled and disabled
![Bildschirmfoto_2021-12-26_13-54-13](https://user-images.githubusercontent.com/17964433/147409163-7e508ee7-35fc-48ca-9609-380bef49cdc8.png)
I tried with/without a jumper on boot-3.3V
I copied 'Multi4in1/StmMulti4in1.bin' and flashed with flash-multi under WIN 10, then erased before flashing, then activated debug and could still see all protocols in terminal window.

I am stuck!

br KH

**Comment by nostromo123** [comment]
This MPM ships with an CKS32, but is recognized as STM32 here
![STM1](https://user-images.githubusercontent.com/17964433/147409430-f054797a-26ea-42a8-952c-2b9bbefcf915.JPG)
![STM2](https://user-images.githubusercontent.com/17964433/147409436-dedbebcf-0cfa-4887-a388-c739af9bc85f.JPG)

**Comment by pascallanger** [comment]
Which software is running on your radio and version?

**Comment by nostromo123** [comment]
![Bildschirmfoto_2021-12-26_15-43-36](https://user-images.githubusercontent.com/17964433/147411559-4af69126-b5f8-4350-a84e-ae4875f1abc2.png)

**Comment by pascallanger** [comment]
can you take a picture of the protocol section on opentx?
does the module fw version appears there?

**Comment by nostromo123** [comment]
I have here two *.bin files generated under Arduino IDE with USB support set in IDE  disabled (-usb) and enabled (+usb)
With **reduced protocols** (only FrSky and M-Link) 34k and 39k size.
![1](https://user-images.githubusercontent.com/17964433/147418864-67b38923-fea6-4568-abe9-7d4dfe11db32.JPG)

Under WIN 10:
**- read the module (-usb)**
![2](https://user-images.githubusercontent.com/17964433/147418888-dcf54b8f-6f93-46a3-ab81-72f314233e43.JPG)
**- erase the module**
![3](https://user-images.githubusercontent.com/17964433/147418901-f47c1882-38c3-4db7-bba2-b6193dfe580f.JPG)
**- write (+usb)**
![4](https://user-images.githubusercontent.com/17964433/147418932-ffada88c-cc77-4197-a8d3-429627c5a823.JPG)
**- read module (+usb)**
![5](https://user-images.githubusercontent.com/17964433/147418952-cc703264-cd7b-4803-9a68-149b05995a99.JPG)

**Now pics from the radio (no rx bound!)**

switching between those two displays

![20211226_204252](https://user-images.githubusercontent.com/17964433/147418997-37c42abe-cf85-4f54-9ae7-295fdb2643db.jpg)


![20211226_204254](https://user-images.githubusercontent.com/17964433/147419006-5f692ab4-0e8f-44de-a039-a28c8afd96e5.jpg)

No module Info, but I think this is issue 
https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/issues/621
Flashing from X10 Express also not possible!

![20211226_204334](https://user-images.githubusercontent.com/17964433/147419026-7c0626c4-5fc2-4d04-bbeb-94cae2186352.jpg)


My aim here was by disabling **all** protocols but FrSky and Mlink in -Config.h to reduce the scrolling between protocols on the radio, but I still seem to have **al**l protocols visible??? 

/****************************/
/*** PROTOCOLS TO INCLUDE ***/
/****************************/
//In this section select the protocols you want to be accessible when using the module.
//All the protocols will not fit in the Atmega328p module so you need to pick and choose.
//Comment the protocols you are not using with "//" to save Flash space.

I interpreted that comment, that by disabling, the protocols don't show up, but I might be wrong!?

PS. Cold you comment please on 'Arduino IDE with USB support set in IDE', as I did not find any information in the documentation.

**Comment by nostromo123** [comment]
Sorry, I at least found the answer for my add. question in RCG post ;-)

> Cold you comment please on 'Arduino IDE with USB support set in IDE', as I did not find any information in the documentation.

https://www.rcgroups.com/forums/showpost.php?p=45466633&postcount=19826

**But back to my basic question, I disabled most protocols in _Config.h, reduced the *.bin file to 34k and still those disabled protocols show up, when scrolling the protocols on the radio.**

Is that behavior supposed to be like that?

br
