### ISSUE TITLE
Bind with Turnigy Ia6c (Flysky2A) fails

### ISSUE THREAD

**Issue by tchleb** [pascallanger/DIY-Multiprotocol-TX-Module#649]
Hi,
I have tried to bind to wo different Turnigy Ia6c RXs. Unfortunately the TX want bind. 

I use Radiomaster TX16s with internal 4 in 1 with the latest Firmware V1.3.3.0

Is there a solution for binding to Turnigy receivers?

**Comment by pascallanger** [comment]
These RXs bind without an issue. You need to follow the std process:
 1. put the bind strap on the RX
 2. power on the RX
 3. launch a bind from the TX

https://youtu.be/7uroYR77cgs
 
Notes:
 - the TX and RX needs to hear each others so try either really close or at a distance.
 - you must select a uniq RX number by RX

**Comment by tchleb** [comment]
Thank you for your fast reply.

I already tried this steps.
1. Press the bind button on RX
2. Power on the Ia6c
3. On my remote I selected Flysky2A, PWM_ibus, 50Hz and choosed a unique receiver ID and pressed the bind button.

The remote does not bind with the ia6c. I tested to different ia6c. 

I tested successfull a uz65 with building Flysky2A receiver.
