### ISSUE TITLE
avr8-burn-o-mat software does not appear to work in Linux Ubuntu 16.04

### ISSUE THREAD

**Issue by j-keiter** [pascallanger/DIY-Multiprotocol-TX-Module#65]
The current Java Run Time Environment is not compatible and when the program runs it looks for the avrdude.conf file in a users home directory named /home/jenkins.  Not sure it that is a bug or I did not install correctly.  Not sure how to notify the developer.  .de is part of url location.

**Comment by pascallanger** [comment]
No idea how to reach the developper, I've checked his web site but I don't seee anything obvious : http://avr8-burn-o-mat.aaabbb.de/avr8_burn_o_mat_avrdude_gui_en.php
For avrdude.conf, it's like on windows and never configured by default. You should point to an already existing avrdude location like the Arduino environment.
