### ISSUE TITLE
RADIOMASTER TX 16 S SE BINDING FAILED

### ISSUE THREAD

**Issue by PARKHCOY** [pascallanger/DIY-Multiprotocol-TX-Module#650]
Help.. i have same problem. my remote is Radiomaster TX 16 S SE, but this remote does not bind with Flysky iA6B.
when i choose mode multi with flysky, module statuse indicate protocole invalid.

do you have solution for this problem? thanks

**Comment by benlye** [comment]
There is no solution - the TX16**SE** only has the CC2500 RF module, not the full 4-in-1, so Flysky is not supported.
