### ISSUE TITLE
Tx 12 kann meine Hott nicht binden

### ISSUE THREAD

**Issue by Gunhallo** [pascallanger/DIY-Multiprotocol-TX-Module#656]
Alle neue Software auf gespielt auf der tx 12 aber es ist kein binden mit hott grauper Empfänger möglich---
Habe jetzt tage damit verbracht aber kein Erfolg zu bekommen , Neuen Sender tx erworben bin fast so weit die anlage in die tonne zu tretten.....

**Comment by mha1** [comment]
Which firmware versions for MPM and OpenTX?

**Comment by mha1** [comment]
... and which Graupner receiver and which RX firmware version?

**Comment by HazzaHFPV** [comment]
Bevor du sie in die Tonne tritts, nehme ich sie lieber ;)
Ich besitze diverse HoTT Empfänger die ich mit mehreren 4in1 Modulen betreibe. Um welche Empfänger geht es denn?
Auf Anhieb fällt mir nur die Frage ein: Mal das Frequenz-Tuning durchgeführt?
Beste Grüße
Harry

**Comment by Gunhallo** [comment]
Hey

Ja es geht um den GR12 neu erworben ,,, Intern und extern und Frequenz-Tuning von 129 bis -129 keine bindung ....weiss mir kein Rad mehr ....

Bootloder neusten und Multi neuster aufgespielt und nix machter ,,,,man kann auch nicht erkenne warum nicht ....

Soviel nachgelesen aber maches verstehe ich auch nicht Bekriflichkeitn .....

 

Danke für deine Antwort

 

gruss

gunther

 
 

Gesendet: Sonntag, 30. Januar 2022 um 18:24 Uhr
Von: "Harry" ***@***.***>
An: "pascallanger/DIY-Multiprotocol-TX-Module" ***@***.***>
Cc: "Gunhallo" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [pascallanger/DIY-Multiprotocol-TX-Module] Tx 12 kann meine Hott nicht binden (Issue #656)


 

Bevor du sie in die Tonne tritts, nehme ich sie lieber ;)
Ich besitze diverse HoTT Empfänger die ich mit mehreren 4in1 Modulen betreibe. Um welche Empfänger geht es denn?
Auf Anhieb fällt mir nur die Frage ein: Mal das Frequenz-Tuning durchgeführt?
Beste Grüße
Harry

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Gunhallo** [comment]
Hey es geht um einen neuen Gr 12 .....

 

grusss 

gunther

 

Gesendet: Sonntag, 30. Januar 2022 um 16:22 Uhr
Von: "Michael" ***@***.***>
An: "pascallanger/DIY-Multiprotocol-TX-Module" ***@***.***>
Cc: "Gunhallo" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [pascallanger/DIY-Multiprotocol-TX-Module] Tx 12 kann meine Hott nicht binden (Issue #656)


 

... and which Graupner receiver and which RX firmware version?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
