### ISSUE TITLE
Got trouble with Windows 10 and a LC technologies V2.0 USBAsp

### ISSUE THREAD

**Issue by Turnabite** [pascallanger/DIY-Multiprotocol-TX-Module#67]
Hello,
try ro update my BG 4in1 Vers 1.2
load usbasp driver you recomendet copy paste the Textfile with Notepad++ as Admin, slashed out al Protocols in config.h and got after checkingan Error ??##############################.... is invalid in Adruino/...............board.txt
Tried it with Minimac OS Sierra same USBAsp same Board checking and compiling runing fine but cant write it on board cause seriel port is not found try to install somme drivers but no resolve of problem

hope someone with same issues and help for me

Andreas

**Comment by pascallanger** [comment]
I'm running on windows 10 and this works fine. You've wrongly modified your board.txt like the IDE is stating. You should paste the text at the bottom of the file and do not change anything else. Don't use notepad but a tool like wordpad which is bundled with windows 10.
