### ISSUE TITLE
Add FX601

### ISSUE THREAD

**Issue by albatorsssx** [pascallanger/DIY-Multiprotocol-TX-Module#673]
Hello,
Can you add the FX 601 model?
Here is a link to the product:
https://www.banggood.com/FX601-2_4Ghz-2CH-235mm-Wingspan-Delta-Wing-EPP-RC-Airplane-RTF-with-3-Axis-Gyro-System-p-1687052.html?rmmds=myorder&cur_warehouse=ES&ID=531270
And attached is a picture of the radio.
![20220324_182102](https://user-images.githubusercontent.com/3882582/160090109-f9911c65-9b25-45b2-a852-874e97a6bffd.jpg)

I've try the FX816 protocol but it seems not to work. No binding.

Thank you in advance.

**Comment by pascallanger** [comment]
You can try the new FX 620 subprotocol using the latest test version.
Please report if it works.

**Comment by albatorsssx** [comment]
Hello,

Thank you very much for the implementation. I put the latest test version but I don't see the new protocol.

Is there a problem ?

Thanks,

Jean Louis

**Comment by albatorsssx** [comment]
Yes I have access but it's not for my module, I have a iRangeX IRX4 (mm-stm-serial-aetr). Sorry.

**Comment by pascallanger** [comment]
Test builds are now available. Please try and report.

**Comment by albatorsssx** [comment]
Yes He is present. Thanks. Unfortunately no binding. Should I configure the channels in a certain way?

**Comment by pascallanger** [comment]
Have you tried other protocols like kf606 and such since looking at the pictures the board seems to be similar.

**Comment by albatorsssx** [comment]
Sorry for the late response. I was on vacation. I tested but it doesn't work. No bind. It doesn't matter if it doesn't work, the device is just a toy. Thank you anyway for the time spent on this.

**Comment by pascallanger** [comment]
Yeah without the hardware there is nothing I can do. And frankly, FX "toys" airplanes are quite bad since they have no proportionality on ailerons just throttle.
