### ISSUE TITLE
setting FORCE_GLOBAL_ID doenst break bind (FrSkyX2)

### ISSUE THREAD

**Issue by jasc76** [pascallanger/DIY-Multiprotocol-TX-Module#677]
I set FORCE_GLOBAL_ID and compiled 1.3.3.11.
After setting this option an existing bind was not broken, is this correct?

**Comment by pascallanger** [comment]
That's more than strange.
What happens when you use the LUA app which is made for changing the ID called MultiConfig: https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/tree/master/Lua_scripts#multiconfig

**Comment by jasc76** [comment]
I also tried with 1.3.3.7 (standard release from site) and MultiConfig says the same "No Config Telemetry"

**Comment by jasc76** [comment]
@pascallanger  
Hi
Any hint on this?

**Comment by pascallanger** [comment]
I'm thinking you are not using the latest lua script...
With the old one, just create a blank model and select multi on the module you want to configure.

**Comment by jasc76** [comment]
I used the scripts provided in the 1.3.3.7 Release on github. I even coped them again to be sure..

Ok, then I will copy the luas directly from master branch and try again and report back

**Comment by pascallanger** [comment]
The script as been modified since 1.3.3.7. This is why I pointed you to the page in a message above.

**Comment by jasc76** [comment]
Ah, ok
but then the script versions from the releases page are not up to date.
https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/releases

**Comment by pascallanger** [comment]
No since this is a release. They will be in the next one...

**Comment by jasc76** [comment]
Ok, not using the release version it works

but the ID is not changed although I set it in the build config.h and of course delete the comment

**Comment by pascallanger** [comment]
You must be doing something wrong. I'm using FORCE_GLOBAL_ID on all my modules.
Copy and paste the line you've changed here to see.

**Comment by jasc76** [comment]
#define FORCE_GLOBAL_ID	0xAFFE1234

**Comment by jasc76** [comment]
In config.h

Should it be named _config.h ?

**Comment by pascallanger** [comment]
The config file is called _config.h

**Comment by jasc76** [comment]
Ok, I tried again. fresh clone and this time I did it in the _MyConfig.h 
but no luck .... I effing dont know what I'm doing wrong. 
for compile do I need to open the myconfig or the config ?

I guess I'm too dumb for this :-(

**Comment by pascallanger** [comment]
If you do it in _MyConfig.h then you have to enable myconfig in _config.h

**Comment by jasc76** [comment]
Ok, with myconfig it works ! 
thnks !
