### ISSUE TITLE
DSM Forward Programming V0.2 For AR636B Has No Menu Options

### ISSUE THREAD

**Issue by KenImhof** [pascallanger/DIY-Multiprotocol-TX-Module#679]
DSM Forward Programming LUA scripts on AR636B V4.40.0 has no menu options.  This receiver came in my Blade 230 V2 Helicopter.

![SpektrumFWFeedLua](https://user-images.githubusercontent.com/29838195/163881919-4cced330-e341-4e96-9350-46af2979465a.jpg)

**Comment by pascallanger** [comment]
Use the latest DSM LUA script: https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/tree/master/Lua_scripts

**Comment by KenImhof** [comment]
Thanks, it is now working!!!!
