### ISSUE TITLE
DSM Bound but channels outputs are all jumbled

### ISSUE THREAD

**Issue by ValiMdx** [pascallanger/DIY-Multiprotocol-TX-Module#681]
Hello.

Thanks Pascal for matining this! all the info you've put online over the years has helped me solve all my issues just by lurking around.
I have hit a wall now though:

i have a th9x with er9x and the last version of the mpm firmware. I have managed to bind on my small eachine evo board, and can see the receiver working in cleanflight, but all channels are meaning:

if i move the right stick (ELE) which is mapped on CH2, when 
i pull down it moves  AUX1 from 1900 to 1360, 
I push up it moves AUX2 from 1000 to  1540

The only one that is correctly mapped is the throttle, but also only responds when the stick is in the lower half.

other things that i've noticed is that if i configure the pots to the other channels, they are impacting in some way or another, like somehow the signal gets mixed.

Hope you can point me if this might be a board hardware or software issue or some kind of extra fine tuning that i need to do to the MPM ( Similar to the SFHSS debug mode which allowed me to stabilize the connection on another board)

Thanks!

**Comment by ValiMdx** [comment]
Yes it's running the serial between radio and protocole.
I don't think i have telemetry as i didn't try using it until now.

I've tried binding with different protocols, and now it seems it bound correctly to DSM2-22 and it's working correctly! 

Thanks a lot!

**Comment by pascallanger** [comment]
When telemetry is available the multi module will request the radio to switch to the subprotocol the RX has asked for. Without telemetry, you need to know what the RX expects or scan through the subprotocols (no need to rebind).
