### ISSUE TITLE
Support for CF922

### ISSUE THREAD

**Issue by marph43** [pascallanger/DIY-Multiprotocol-TX-Module#687]
Dear devs
Can you please add support for the [CF922](https://www.aliexpress.com/item/4000555929547.html?spm=a2g0o.order_list.0.0.21ef1802GAwdbV)?
Thanks for your great work, by the way!

**Comment by pascallanger** [comment]
Without access to the hardware (TX+RX), there is nothing I can do.
You can send it to my attention or donate to purchase it.
