### ISSUE TITLE
Hott Telemetry 

### ISSUE THREAD

**Issue by Networker-001** [pascallanger/DIY-Multiprotocol-TX-Module#689]
On EdgeTX  2.71 and Multiprot 1.3.3.7 some HOTT telemetry items have to be checked

-temperatur EAT1 and EAT2 
     always displaying -20 degrees celsius

-RSSI and TSSI 
     values are negativ  ( fix in telemetry window with offset 120 works)
     naming is not correct for Model Locator Rssi have to be changed into RSSI ( fix in telemetry window

-Lua getrssi() does not work

**Comment by pascallanger** [comment]
Hi, This is not something to fix in Multi but EdgeTX instead. Multi sends the telemetry feed assembled but untouched to the radio to be decoded there.
- Pascal
