### ISSUE TITLE
how to set E010 as high rates?

### ISSUE THREAD

**Issue by qdog2012** [pascallanger/DIY-Multiprotocol-TX-Module#69]
how to set E010 as high rates?

**Comment by Dutchy-79** [comment]
It's already in the highest possible rates, you can set it to lower rates in the transmitter.

**Comment by qdog2012** [comment]
which aux to set lower rates?

**Comment by Dutchy-79** [comment]
None, you can adjust rates in the transmitter menu.

**Comment by qdog2012** [comment]
noted, thanks.
