### ISSUE TITLE
Missing USB serial support for stable versions?

### ISSUE THREAD

**Issue by SJLPHI** [pascallanger/DIY-Multiprotocol-TX-Module#690]
Hello,

I am trying to update the firmware for my IRX4 Lite and during an update with USB, I realized that [mm-stm-serial-aetr-v1.3.3.7.bin](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/releases/download/v1.3.3.7/mm-stm-serial-aetr-v1.3.3.7.bin) 
has no USB support, and the debug firmwares are too glitchy.

Could you re-compile the main stable build with USB serial enabled please? Both IRX4 and IRX4 Lite need USB support.

**Comment by benlye** [comment]
You do not need USB serial to update the firmware on either of those modules. The stable releases include USB DFU support, which is all that is required.

USB serial support wasted a lot of flash space unnecessarily so was removed from the builds.

You can find more information here:
https://github.com/benlye/flash-multi/blob/master/doc/New_Bootloader.md
