### ISSUE TITLE
Documentation is out of sync, what modules are supported?

### ISSUE THREAD

**Issue by Hoeby** [pascallanger/DIY-Multiprotocol-TX-Module#698]
I am starting with the multiprotocol.
Having a frsky xlite, i wanted a lite module.

I purchased the vantac mpm
Looking on this page, the vanctac mpm looks supported
(https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/docs/Hardware.md)

But looking at this page, it looks unsupported, because of the 64K memory.
(https://www.multi-module.org/basics/module-hardware/unsupported-modules)

I was happy to find a module in europe, but now i looks like i got the wrong one
I uploaded the version  "multi-stm-opentx-taer-inv-v1.3.1.9.bin", it is 117kb, so i am in troubles?
I uploaded an old version, because i need the **inv**, i am not that good to compile my own with the 1.3.3.7 version
With the older version i can bind a receiver, but now i don't know if i am safe, or don't use it to fly planes.

Please help, what to do.
Am i good if it works, or have i bought something which is not good enough to use anymore?
Also please update the documentation, that they are insync

**Comment by pascallanger** [comment]
They are not unsupported. What you need to do is to [compile the firmware](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/docs/Compiling_STM32.md) by yourself and select in the _config.h file only the protocols you need.
Check this issue which is the first one and highlighted on the issue page: https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/issues/393
