### ISSUE TITLE
WL F959S latest version (as of 07/2022) protocol change

### ISSUE THREAD

**Issue by ChristianWeckmann** [pascallanger/DIY-Multiprotocol-TX-Module#702]
I am writing this since the documentation includes the WL F959S but there seems to have been an update to it which might lead to lots of frustration. I have no idea if this is the correct place to put this, but since I spent half the day trying to find make this work, I'll put this here in hopes of someone putting it where it belongs if it isn't here:

The WL Toys F959S I received today had a little additional sheet of paper in the box titled "Special reminder", which informs about changes to the flight controller board due to chip shortages. The board now includes SBUS connectors for external receivers and they have changed the protocol for the internal RX. As far as I found out 

- the original F959 was working with MT99XX / A180, 
- the first F959S used KN / WLtoys and
- this newest version of the F959S uses V911S / E119

This FC board has markings for more models on it, which suggests it is used in them as well. (And the documentation already mentions the newer XK A800 using this protocol, which was how I found out about the correct protocol.

Thanks in advance :)
![FC](https://user-images.githubusercontent.com/65950265/177864661-9c70f876-2c85-42e5-b9a6-b21cdfeee262.jpg)

**Comment by pascallanger** [comment]
I've updated the protocols list to reflect your findings.
