### ISSUE TITLE
power limitation for jumper t18

### ISSUE THREAD

**Issue by amysticool** [pascallanger/DIY-Multiprotocol-TX-Module#710]
Hi, 
I notice that the rf power for 868/91MHz has change from latest update for jumper t18 and r9 frsky long rang receiver. This is limited to 50mW but the radio can go up to 300mW so why this is restricted ?? can it be corrected for future release ?

Thanks

**Comment by Ostay** [comment]
The SX1276 transmitter module built into the Jumper T18's 5IN1 Radio can power up to 100mw, but the latest update to the 5IN1's firmware is limited to 17dbm(50mw). I want to know why? Look forward to adding 20dbm(100mw) option in later versions, thanks!

**Comment by pascallanger** [comment]
It's simply how Jumper have designed the RF board. They've used the output where no power adjustment can be done and added a fixed gain of 50mW at the output stage.

**Comment by Ostay** [comment]
Thank you for your reply. I have understood the problem. Thank you very much!
