### ISSUE TITLE
Huina / Amwei Construction equipment models 

### ISSUE THREAD

**Issue by khaledaborisha** [pascallanger/DIY-Multiprotocol-TX-Module#712]
Hi, 

I wonder if someone managed to use the multiprotocol module to control Huina / Amwei Excavators ... 

I've opened the TX and it has RW1608P chip 

Thanks 

Khaled

**Comment by pascallanger** [comment]
Never had one in my ends. So I don't think it's supported.
I can have a look but I would need the TX and model to be sent to my attention.

**Comment by arthurson** [comment]
huina 573 truck tx use rf2520a chip
huina 593 exvacator tx use rw1608p chip

**Comment by pascallanger** [comment]
Unless I have a TX+RX there is nothing I can do...
