### ISSUE TITLE
Install multiprotocol module internally 

### ISSUE THREAD

**Issue by ramezquitao** [pascallanger/DIY-Multiprotocol-TX-Module#729]
Does any one know if it is possible to install the multiprotocol module internally (as a replacement of the XJT module) in a Horus X10S

Thanks

**Comment by richardclli** [comment]
If you know how to build firmware, you can 100% make it works.  You better ask in EdgeTX's discord group for more support.  

https://discord.gg/wF9wUKnZ6H
