### ISSUE TITLE
Adapting code for TX12 CC2500 internal module

### ISSUE THREAD

**Issue by SergVP70** [pascallanger/DIY-Multiprotocol-TX-Module#742]
Trying to compile code for Radiomaster TX12. It is due to breaking of firmware updating followed by bricked module at "rebooting" state...
TX12 internal multi-module have only cc2500 installed. Controller is STM32 64k.
I'm edit _Config.h file for comment all unused chip. But unfortunately "Sketch too big" issue apear. Description is "Sketch uses 56276 bytes (101%) of program storage space. Maximum is 55272 bytes."
Can anyone help me?
Many thanks in adwance!

[_Config.h.txt](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/files/9846997/_Config.h.txt)

**Comment by benlye** [comment]
You need to comment out some of the CC2500 protocols to reduce the compilation size until it fits.
