### ISSUE TITLE
in DSM FwdPrg.lua, flight mode label is wrong

### ISSUE THREAD

**Issue by Dweinbach** [pascallanger/DIY-Multiprotocol-TX-Module#749]
the "Flight Mode" string displayed in Gyro Settings/Flight Mode Setup is incorrect, and always displays "1" before the actual flight mode.

correction is simple and tested, but MAY adversely affect rx models other than AR637T (doubtful):

Change:
Line 749:   Text[0x8001]="Flight Mode 1"
To:
Line 749:   Text[0x8001]="Flight  #Mode"

**Comment by frankiearzu** [comment]
Dave, 
This is fixes in the new v0.5 of the code that i provided.
