### ISSUE TITLE
JJRC H20H not Binding on CG023_NRF24L01 H8-3D

### ISSUE THREAD

**Issue by Turnabite** [pascallanger/DIY-Multiprotocol-TX-Module#75]
Compiled and flashed new Multiprotocol on my BG 
(After some solved issues with correct Transfer of board TXT insert)

But my JJRC H20H will not bind on recomended Protocol H8-3D
any help?

thx a lot

**Comment by pascallanger** [comment]
JJRC H20 is protocol CG023 and subprotocol H8_3D.
If I remember correctly once the bind is donce the LED changes then you still need to arm it by playing with the sticks.
