### ISSUE TITLE
PL18 specific MPM module

### ISSUE THREAD

**Issue by richardclli** [pascallanger/DIY-Multiprotocol-TX-Module#752]
I have designed a MPM module for Flysky PL18 and looking forward to opensouce the design.  Please advice if I can make a PR to put my design in this project and how should I file the hardware design. @pascallanger

**Comment by pascallanger** [comment]
What about putting your files under master/STM32 PCB/Flysky PL18 and make a PR ?

**Comment by richardclli** [comment]
Alright, thank you.

**Comment by richardclli** [comment]
I did the PR:

https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/pull/754

**Comment by pascallanger** [comment]
Merged, Thanks!
