### ISSUE TITLE
SMT32 Board V1.1

### ISSUE THREAD

**Issue by Turnabite** [pascallanger/DIY-Multiprotocol-TX-Module#76]
hello there, Question,
i ordered 3 weeks ago the 1.0 Version for SMT Multi,
waiting for SMDs, but you release 1.1. now,
Is it posiible to give a Workarround to "cratively" change the New Sketch as i see only a Diode is adiitional come on Board

KR
A

**Comment by pascallanger** [comment]
There is no real need for this mod unless you are developping on the module updating it all the time like me. I even don't have it and not planning to implement it...
Pascal

**Comment by Turnabite** [comment]
Thx 4 fast answer

Andreas
