### ISSUE TITLE
RLINK issue on Arduino

### ISSUE THREAD

**Issue by tew2012** [pascallanger/DIY-Multiprotocol-TX-Module#767]
are the rlink protocols supported for the Arduino target (latest MULTI)? 

I can bind to all three sub protocols (surface, air, dumborc), but the servo behavies like there is a bad connection (delay, jumps). It's ok with the STM target. RF tuning works and just for testing I removed all other protocols in case it's a lack of memory issue. And I tried different cc2500 rf chips. The R6FG rx LED is blinking sometimes when bound (Arduino), always solid on STM.

Other protocols like D8 or esky work without a problem, D8 with telemetry. I don't get telemetry with surface and air (Arduino). there is no telemetry for dumborc on both targets.

**Comment by pascallanger** [comment]
I have to say that I'm not spending time on the atmega anymore. I've looked quickly at the code, there should not be a reason for it to work but I don't have the hw anymore to test anything.
