### ISSUE TITLE
DSM2 surface 

### ISSUE THREAD

**Issue by Guden79** [pascallanger/DIY-Multiprotocol-TX-Module#769]
Hello :-)

Is it possible, to ad DSM2 for surface (16,5 ms)?

Would be great to use my Mini-Z :-)

Greets

**Comment by pascallanger** [comment]
I need to have access to a RX first to try things out and if I can't get it to work I would need a TX.
If you are ok to send it to France let me know.

**Comment by Guden79** [comment]
Is it ok if I send you the money for such a recipient? They are not expensive. I would send the money to them via PayPal friends and then they can keep the receiver. I think otherwise the shipping is more expensive than the RX ;-)

 

Here is a link to the Reciever: https://campaign.aliexpress.com/wow/gcp/tesla-pc-new/index?UTABTest=aliabtest344316_486351&_randl_currency=EUR&_randl_shipto=DE&src=google&src=google&albch=shopping&acnt=494-037-6276&slnk=&plac=&mtctp=&albbt=Google_7_shopping&albagn=888888&isSmbAutoCall=false&needSmbHouyi=false&albcp=8632818872&albag=89514576449&trgt=295204014427&crea=de1005003607189968&netw=u&device=c&albpg=295204014427&albpd=de1005003607189968&gclid=Cj0KCQiA1ZGcBhCoARIsAGQ0kkrGO1kQ4pSVjaKK427gTSIPW4ptK67eJb02CrN6lULINnKqPqsmzRwaAmtNEALw_wcB&gclsrc=aw.ds&aff_fcid=3a66352ca1f94f7eb21ee0198936e15e-1669675410477-06003-UneMJZVf&aff_fsk=UneMJZVf&aff_platform=aaf&sk=UneMJZVf&aff_trace_key=3a66352ca1f94f7eb21ee0198936e15e-1669675410477-06003-UneMJZVf&terminal_id=785307d784a94138941d93a47e197581&wh_weex=true&wx_navbar_hidden=true&wx_navbar_transparent=true&ignoreNavigationBar=true&wx_statusbar_hidden=true&bt_src=ppc_direct_lp&scenario=pcBridgePPC&productId=1005003607189968&OLP=1084300508_f_group2&o_s_id=1084300508

 

Greets Sascha
 

 

Gesendet: Montag, 28. November 2022 um 19:15 Uhr
Von: "pascallanger" ***@***.***>
An: "pascallanger/DIY-Multiprotocol-TX-Module" ***@***.***>
Cc: "Guden79" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [pascallanger/DIY-Multiprotocol-TX-Module] DSM2 surface (Issue #769)


 

I need to have access to a RX first to try things out and if I can't get it to work I would need a TX.
If you are ok to send it to France let me know.

**Comment by Guden79** [comment]
Hey :-)

 

So it seems not to be ok for you?

Maybe, you could explain how it works to sniff a protocoll?

Or is there a thread where i can read about this?

Looking forward to hear from you :-)

 

Greets Sascha

 

Gesendet: Montag, 28. November 2022 um 19:15 Uhr
Von: "pascallanger" ***@***.***>
An: "pascallanger/DIY-Multiprotocol-TX-Module" ***@***.***>
Cc: "Guden79" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [pascallanger/DIY-Multiprotocol-TX-Module] DSM2 surface (Issue #769)


 

I need to have access to a RX first to try things out and if I can't get it to work I would need a TX.
If you are ok to send it to France let me know.

**Comment by pascallanger** [comment]
Sorry I forgot to answer your email. Sure send me a paypal at pascal _ langer @ yahoo . fr and I'll place the order right away. Just looked at your link, it's 16€ delivery included.

**Comment by Guden79** [comment]
Send it :-)

Hope, you are succesfull :-)

 

But, you would not tell me how it works?

I know, i need a "sniffer", did read this at RC-Groups, but are not able to find the thread anymore :-(

 

Then, in future, i could make my own protocolls, specialy for Cars and boats :-)

 

 

Greets Sascha

 
 

Gesendet: Donnerstag, 01. Dezember 2022 um 17:51 Uhr
Von: "pascallanger" ***@***.***>
An: "pascallanger/DIY-Multiprotocol-TX-Module" ***@***.***>
Cc: "Guden79" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [pascallanger/DIY-Multiprotocol-TX-Module] DSM2 surface (Issue #769)


 

Sorry I forgot to answer your email. Sure send me a paypal at pascal _ langer @ yahoo . fr and I'll place the order right away. Just looked at your link, it's 16€ delivery included.

**Comment by pascallanger** [comment]
Order placed.
In that case there is nothing to sniff since I don't have the Spektrum TX. I'm thinking they haven't made huge changes to their DSM2 protocol so I'm willing to try to play around with timing of the frames mostly. That will be a lot of trial and errors which is why it's difficult to do remotely.
If you want to participate, purchase a cheap 8 channels logic analyzer and solder it to the RF part of you Spektrum TX. We will see what's being sent and may be the timing.
Pascal

**Comment by Guden79** [comment]
The Problem is: I have no more DSM2 TX :-(

So i need it for my multimodule.

 

I tried to bind the multi to dsm2-surface, it was binding, but functionally not correct. Maybe, it's because DSM2-surface uses 16,5 ms?

 

 

 

Gesendet: Freitag, 02. Dezember 2022 um 11:58 Uhr
Von: "pascallanger" ***@***.***>
An: "pascallanger/DIY-Multiprotocol-TX-Module" ***@***.***>
Cc: "Guden79" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [pascallanger/DIY-Multiprotocol-TX-Module] DSM2 surface (Issue #769)


 

Order placed.
In that case there is nothing to sniff since I don't have the Spektrum TX. I'm thinking they haven't made huge changes to their DSM2 protocol so I'm willing to try to play around with timing of the frames mostly. That will be a lot of trial and errors which is why it's difficult to do remotely.
If you want to participate, purchase a cheap 8 channels logic analyzer and solder it to the RF part of you Spektrum TX. We will see what's being sent and may be the timing.
Pascal

**Comment by pascallanger** [comment]
So you see you have nothing to sniff since you don't have a TX... So you can do same as I'm planning to do, open the DSM code and modify the timings to see if it will work. If I remember well I already started the implementation of 16.5ms, it started to give something if I recall but the person asking for it and testing disappeared...

**Comment by Guden79** [comment]
Unfortunately I am not able to edit these codes. I therefore hope that you will make it, but I believe in you ;-)

 

Gesendet: Samstag, 03. Dezember 2022 um 10:45 Uhr
Von: "pascallanger" ***@***.***>
An: "pascallanger/DIY-Multiprotocol-TX-Module" ***@***.***>
Cc: "Guden79" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [pascallanger/DIY-Multiprotocol-TX-Module] DSM2 surface (Issue #769)


 

So you see you have nothing to sniff since you don't have a TX... So you can do same as I'm planning to do, open the DSM code and modify the timings to see if it will work. If I remember well I already started the implementation of 16.5ms, it started to give something if I recall but the person asking for it and testing disappeared...

**Comment by OpenUAS** [comment]
@pascallanger a Spektrum TX (original) will be soon on your doorstep.

**Comment by OpenUAS** [comment]
@pascallanger a Spektrum TX (original) will be soon on your doorstep.

**Comment by Guden79** [comment]
Hello...

 

Are there news about sniffing out?

 

Greets :-)

 
 

Gesendet: Samstag, 03. Dezember 2022 um 10:45 Uhr
Von: "pascallanger" ***@***.***>
An: "pascallanger/DIY-Multiprotocol-TX-Module" ***@***.***>
Cc: "Guden79" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [pascallanger/DIY-Multiprotocol-TX-Module] DSM2 surface (Issue #769)


 

So you see you have nothing to sniff since you don't have a TX... So you can do same as I'm planning to do, open the DSM code and modify the timings to see if it will work. If I remember well I already started the implementation of 16.5ms, it started to give something if I recall but the person asking for it and testing disappeared...

**Comment by frankiearzu** [comment]
@Guden,
I have to do the sniffing to work on the Forward programming.. is not trivial.
You have to get a Multi-Channel digital analizer, and then solder wires to an original Spektrum module to do the capture.
After you have the raw frames, you have to filter on a lot of numbers to try to understand what they mean.

**Comment by Guden79** [comment]
Ok, definitely nice to hear that something is happening :-)


LG


 
 

Gesendet: Samstag, 18. März 2023 um 16:50 Uhr
Von: "Frankie Arzu" ***@***.***>
An: "pascallanger/DIY-Multiprotocol-TX-Module" ***@***.***>
Cc: "Guden79" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [pascallanger/DIY-Multiprotocol-TX-Module] DSM2 surface (Issue #769)


 

@guden,
I have to do the sniffing to work on the Forward programming.. is not trivial.
You have to get a Multi-Channel digital analizer, and then solder wires to an original Spektrum module to do the capture.
After you have the raw frames, you have to filter on a lot of numbers to try to understand what they mean.

**Comment by Guden79** [comment]
Hello, is there any news? I saw that you can now bind the TRX-4m... Greetings
 

 

Gesendet: Samstag, 03. Dezember 2022 um 10:45 Uhr
Von: "pascallanger" ***@***.***>
An: "pascallanger/DIY-Multiprotocol-TX-Module" ***@***.***>
Cc: "Guden79" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [pascallanger/DIY-Multiprotocol-TX-Module] DSM2 surface (Issue #769)


 

So you see you have nothing to sniff since you don't have a TX... So you can do same as I'm planning to do, open the DSM code and modify the timings to see if it will work. If I remember well I already started the implementation of 16.5ms, it started to give something if I recall but the person asking for it and testing disappeared...

**Comment by idkLogic** [comment]
Can you tell me if this looks SPI trace looks correct? 

The SR3100 rx works with latest test build but having trouble with the ORX GR300.

In the snapshot its a Spektrum DX3R (DSM2 and DSM, 2009 era) tx connected to a ORX GR300 rx.

From what I've traced, CS1 is connected to TX module and CS0 is connected to the ADC chip for input.

![image](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/assets/20591469/fb6c3d4c-a6d6-402c-9872-4e734fa2fd7f)

**Comment by idkLogic** [comment]
@pascallanger: is this a bind packet?

```
SPI	result	0.84624725	0.00017375	0x05230FD32FC34FE3
SPI	result	0.85174225	0.00017375	0x05230FD32FC34FE5
SPI	result	0.8572375	0.00017375	0x05230FD32FC34FE5
SPI	result	0.8627325	0.00017375	0x05230FD12FC34FE5
SPI	result	0.86822775	0.00017375	0x05230FD12FC34FE5
SPI	result	0.873723	0.00017375	0x8523A7A76B6B4FE5 <------
SPI	result	0.879218	0.00017375	0x05230FD32FC34FE5
SPI	result	0.884713	0.00017375	0x05230FD12FC34FE5
SPI	result	0.890208	0.00017375	0x05230FD12FC34FE5
	
```

**Comment by pascallanger** [comment]
I have no idea of what I'm looking at.
If I look at what you have highlighted compared to other lines, it looks like the starting 8523 can be removed at the beginning and 4FE5 at the end which are the same as the other lines, leaving only A7 A7 6B 6B which doesn't look like bind.
We would need to compare what the radio is sending compared to what the module is receiving to understand what's going on.

**Comment by pascallanger** [comment]
Scrap the paint on the traces as indicated and solder the 4 wires. Don't forget to connect GND too.
![1](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/assets/6367598/7f27f3c4-55c6-4382-9eb7-a24c58bb460a)
![2](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/assets/6367598/6a7e5170-5515-4357-94dc-610dbf539832)

**Comment by pascallanger** [comment]
Please use logic 1.2.14 for the dumps
 1. Original TX powered on, start recording and power on RX
 2. Original TX in bind mode, start recording and power on RX in bind mode

**Comment by idkLogic** [comment]
@pascallanger well that was the smallest traces I've ever soldered. 

Using logic 1.2.14 as requested. The binding took 3 goes so its at the end of the capture.

[ORX GR300 rx SPI capture using DX3R tx.zip](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/files/14746154/ORX.GR300.rx.SPI.capture.using.DX3R.tx.zip)

Let me know if you want something else.

**Comment by pascallanger** [comment]
I've been spending a few hours on the files but it's hard to get things correct due to read errors.
- you've done your recording with a too low sample rate which is causing a lot of SPI read errors, at least double it
- the TX and RX might have been a little too close since the RX is getting a lot of garbage (which explains the difficulty to bind)
I can find some of the data I'm looking for but not others.
I would like to add another dump to the existing list which is to do TX off, record, RX on, TX on.

**Comment by pascallanger** [comment]
Setting CHPA=0 solves some of the issues... But still the RX is getting a lot of garbage...

**Comment by pascallanger** [comment]
@idkLogic Could you do a dump but with this time Multi as the TX?

**Comment by idkLogic** [comment]
> @idkLogic Could you do a dump but with this time Multi as the TX?

@pascallanger here are more SPIs dumps from the ORX GR300 at 16MS/s with various setups as requested. 

[16 Mhz SPI ORX GR300 DX3R and Multi 1.3.4.4 - 1.zip](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/files/14752576/16.Mhz.SPI.ORX.GR300.DX3R.and.Multi.1.3.4.4.-.1.zip)
[16 Mhz SPI ORX GR300 DX3R and Multi 1.3.4.4 - 2.zip](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/files/14752578/16.Mhz.SPI.ORX.GR300.DX3R.and.Multi.1.3.4.4.-.2.zip)

I wonder if it is only DSM surface and not DSM2, that was my initial hunch. Maybe this could be a new sub protocol to add?

The binding process is to have the RX already in bind mode before activating the TX bind. Doing it the other way like you asked for, TX first, never works on the first or second attempts.

**Comment by pascallanger** [comment]
The RX simply crashes after the bind with multi. It doesn't even try to receive anything, just a simple crash... I've updated the code to use the bind code 0x23 of the DX3R which I think will solve the issue.

The RX might also care about the number of channels. You can set it on the GUI. The DX3R advertises 3 channels but I think I've seen RXs which goes up to 5 channels so I'm allowing anything between 3 and 5 to be advertised during bind and sent over the air. Let me know if I'm wrong here.

I still only see one frequency being used by the RX. It never switches to an alternate RF channel making it actually DSM1 and not DSM2. On my side, I'm keeping the DSM2 implementation (with telemetry) since it will work with 16.5ms and 11ms. You can switch on the fly between 16.5ms and 11ms by changing the "Servo refresh rate" between 22ms and 11ms, not sure if it affects the servo refresh rate or just the transmission. Documentation updated here: https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/Protocols_Details.md#sub_protocol-dsm2sfc---6

Please test v1.3.4.6 which integrates all these changes. If it still doesn't work do a bind dump so I can see what's going on.

**Comment by idkLogic** [comment]
OK, the bind light stays on using v1.3.4.6. The model matching seems to work too. I bound one ORX GR300 on 17 and the test bed on 18. Changing model IDs activates the correct RX led.

Still no servo control.  Steering servo seems to be active and trying to stay centred. The THR channel is off and servo can move freely.  AUX channel nothing too. 

Two SPI dumps in the zip file. One is binding and other is some triggering of the ch0 (steering) servo when you toggle the channel range from 1-**4** to 1-**5**. Swings a Futaba S3003 old analog servo about 45 degrees. I couldn't change the upper range down to 3 either.

[16 Mhz Multi 1.3.4.6 - ORX GR300 SPI.zip](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/files/14759960/16.Mhz.Multi.1.3.4.6.-.ORX.GR300.SPI.zip)

**Comment by idkLogic** [comment]
_re v1.3.4.7._ Seems to be working on both the GR300 and SR3100.

Range on the SR3100 and GR300 using the multi seems normal (for track racing) like before with the DX3R.

Here are 2 dumps of binding and normal operation using the GR300 for reference. 
[16 Mhz Multi 1.3.4.7 - ORX GR300 SPI now working.zip](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/files/14765721/16.Mhz.Multi.1.3.4.7.-.ORX.GR300.SPI.now.working.zip)

Thanks Pascal :)

--- 
As an aside, I tried binding the DSM1 [SR3300T](https://www.spektrumrc.com/ProdInfo/Files/SPMSR3300T-Instructions.pdf) receiver, some flickering of the LED but then nothing. I'm not particularly worried as I don't use them, more to see if DSM1 worked. I remember it had poor range, 30 to 40 metres if I recall.

**Comment by idkLogic** [comment]
Also are you thinking of supporting the 5.5ms frame rate? I presume the DSMR users would like that too.

When I had the DX3R on the logic analyser, I noticed the timing of the frames coming from the Atmel MCU to the Spektrum TX module were clocked at 5.5ms the whole time. Is the TX module doing some averaging or windowing after receiving to get 11ms and 16.5ms before broadcasting? (guessing)

![image](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/assets/20591469/d1de636b-9bab-475f-a839-e3faae1ec236)

**Comment by pascallanger** [comment]
You most likely want to send the last position of the sticks, so they send what ever the last packet in: 5.5ms/5.5+5.5=11ms/5.5+5.5+5.5=16.5ms
What I've seen is that in 5.5ms your DX3R only sends 2 channels instead of the 3 in 11/16.5ms. Is this expected?
Going to 5.5ms also means that you lose telemetry...

**Comment by idkLogic** [comment]
DX3R: I mixed the AUX channel with the THR to get some output variances.

16.5 ms 
![image](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/assets/20591469/bcc8a994-c7a3-409d-a54c-ec7e4d629753)

5.5 ms
![image](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/assets/20591469/69adcd83-44b0-483f-9364-79ba067bd8fa)

_Curious, where I can find how to read the SPI data and their positional meaning? Is it in the code somewhere?_

The DX3R has no telemetry. 

From the SR6110AT manual:
![image](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/assets/20591469/c46db6b8-0617-485a-a488-202e8b7690a6)

**Comment by pascallanger** [comment]
You are back on the radio module. I have no idea what's being sent to it and as far as I'm concerned I don't think there is useful information there...
But if you want to understand what's going on, you need to move only steering and observe which values are changing in the dump, then do the same with throttle, ch3. After that you should start to have a good idea.

**Comment by idkLogic** [comment]
No worries. I had a read of this guys page: [http://www.cgsy.com.au/archives/215?](http://www.cgsy.com.au/archives/215?) and the data from the TX makes more sense. 
On max throws:
name	type	start_time	duration	mosi	miso
dx3r	result	1.615273063	0.000037687	0b 0 0000000000**10001**	0b1111111111111111  <-- Model 18
dx3r	result	1.615318312	0.000037688	0b 0 **0001** 1 **0101010010**	0b1111111111111111  <-- CH0 1362
dx3r	result	1.615363625	0.000037687	0b 0 **0011** 1 **0101010011**	0b1111111111111111  <-- CH1 1363
dx3r	result	1.615408938	0.000037687	0b 0  **0101** 1 **0101010010**	0b1111111111111111  <-- CH0 1362

All good. 

Thanks again for getting the DSM2 and GR300 working.

**Comment by pascallanger** [comment]
I'm closing this issue since things work on this latest release.
