### ISSUE TITLE
sfhss  with RX2104 problem

### ISSUE THREAD

**Issue by jamedavid2017** [pascallanger/DIY-Multiprotocol-TX-Module#77]
hi pascan and midelic 

i bind protocol SFHSS  with rx orginal Futaba R2104GF , it can bind and work . However , about 8 second, RX lost signal one time and then get back.  I change from -40 to 40 but  same a problem . 
I test with devo 7e protocol SFHSS , it work normal .
Any idea for this or change whats in code SFHSS ?

thanks

**Comment by pascallanger** [comment]
Please test the latest version.
Pascal
