### ISSUE TITLE
In DSM FwdPrg_05_Color.lua Unable to access Flight Mode 1

### ISSUE THREAD

**Issue by charbaugh1** [pascallanger/DIY-Multiprotocol-TX-Module#778]
TX16S MK2 tx
EdgeTX 2.8.0
AR630 rx

During first time setup of AS3X, I assigned the channel for the flight modes to a 3-position switch that was preconfigured in model setup.  In the AS3X setup, when changing the state of the switch to adjust parameters, it only changes from FM2 to FM3.  When moving the switch to the position for FM1, the display shows FM2.  I have tried reassigning to other available switches to confirm it is not a hardware issue.

**Comment by frankiearzu** [comment]
Tried to duplicate the issue but could not reproduce.
Only if i set my servo output channel to less than -100,  i only get FM1,FM2.   if i have (-100,0,+100) for the switch, all 3 flight mode works.  Check your output settings.

**Comment by charbaugh1** [comment]
I’ve definitely checked and double checked the output values, and in the output monitor it confirms -100, 0, +100.  Strange is that I get FM2 and FM3, but I cannot get FM1.  Otherwise, it works perfectly.

 

Clark Harbaugh

**Comment by frankiearzu** [comment]
Clark,
We can check what the RX are sending to the tool to see if it is a tool problem of something else.
the /LOGS/dsm_log.txt contains the last conversation between the tool and the RX.

For example, if you go to forward programming, and go to "Gyro Settings->F Mode setup" you can use the switch to switch the 3 positions. then Exit the script (pressing the RETR button). 
The last part of the log will have the actions when you flipped the switch.

NOTE the  "Val=0", "Val=1","Var=2" etc. those are the raw values coming from the RX in the Flight mode line. The display adds +1, so Var=0 is "Flight Mode 1", Var=1 is "Flight Mode 2", etc..  My TX switch and output gets "-100,0,+100).

This is how my log looks (end of the file) after going to that page and moving the switch the 3 different positions: 
```
19.170 WAIT_CMD: RESPONSE MenuValue: UPDATED: L[#0 T=V_nc VId=0x1000 Text="Flight Mode"[0x8001] Val=0 [0->10,0] MId=0x1021 ]
19.310 MENU_VALUES: SEND DSM_getNextMenuValue(MenuId=0x1021, LastValueId=0x1000) Extra: Text="Flight Mode"
21.190 MENU_VALUES: RESPONSE MenuValue: UPDATED: L[#0 T=V_nc VId=0x1000 Text="Flight Mode"[0x8001] Val=1 [0->10,0] MId=0x1021 ]
21.320 MENU_VALUES: SEND DSM_getNextMenuValue(MenuId=0x1021, LastValueId=0x1000) Extra: Text="Flight Mode"
22.220 MENU_VALUES: RESPONSE MenuValue: UPDATED: L[#0 T=V_nc VId=0x1000 Text="Flight Mode"[0x8001] Val=2 [0->10,0] MId=0x1021 ]
22.340 MENU_VALUES: SEND DSM_getNextMenuValue(MenuId=0x1021, LastValueId=0x1000) Extra: Text="Flight Mode"
```

**Comment by charbaugh1** [comment]
My log looks different than yours.  I tried the test and got the following.  I highlighted the FM info.  Physically, when I went into forward programming, the switch was in the FM1 position.  I moved it to FM2, FM3, FM2, FM1, FM2.  You can see, it never sees the move to FM1.  I ran a couple more tests, changing the minimum value of the output to different values, but saw no change in behavior.  For reference, I have included screenshots of the output screen with the switch in all 3 positions.  I have also tried moving to another physical switch and a different output channel to test with no change.  The last thing I tried was resetting the receiver to factory default and reprogramming from scratch.

 

Radio Info:    tx16s EdgeTX  2.8.0

Date      :    2022-12-19   13:9

DsmLib Version :    0.5

DSM_StartConnection()

0.000 RX_VERSION: SEND DSM_getRxVersion()

0.100 RX_VERSION: RESPONSE Receiver=AR630 Version 2.38.5

0.150 MENU_TITLE: SEND DSM_getMainMenu()

0.220 MENU_TITLE: RESPONSE Menu: M[Id=0x1000 P=0x0 N=0x0 B=0x0 Text="Main Menu"[0x4B]]

0.270 MENU_LINES: SEND DSM_getFirstMenuLine(MenuId=0x1000)

0.360 MENU_LINES: RESPONSE ReqTXInfo(LineNum=0 DataType=0x1  DATA=RX: 09 05 00 01 00 00 00 07 00 00 00 00 00 00 00 00)

0.490 MENU_REQ_TX_INFO: CALL DSM_SendTxInfo_20(#0 DATA=TX: 0x20 0x06 00 00 00 40)

0.550 MENU_REQ_TX_INFO: RESPONSE ReqTXInfo(LineNum=1 DataType=0x1  DATA=RX: 09 05 01 01 00 00 00 07 00 00 00 00 00 00 00 00)

0.590 MENU_REQ_TX_INFO: CALL DSM_SendTxInfo_20(#1 DATA=TX: 0x20 0x06 01 01 00 01)

0.700 MENU_REQ_TX_INFO: RESPONSE ReqTXInfo(LineNum=2 DataType=0x1  DATA=RX: 09 05 02 01 00 00 00 07 00 00 00 00 00 00 00 00)

0.750 MENU_REQ_TX_INFO: CALL DSM_SendTxInfo_20(#2 DATA=TX: 0x20 0x06 02 02 00 02)

0.850 MENU_REQ_TX_INFO: RESPONSE ReqTXInfo(LineNum=3 DataType=0x1  DATA=RX: 09 05 03 01 00 00 00 07 00 00 00 00 00 00 00 00)

0.890 MENU_REQ_TX_INFO: CALL DSM_SendTxInfo_20(#3 DATA=TX: 0x20 0x06 03 03 00 04)

0.940 MENU_REQ_TX_INFO: RESPONSE ReqTXInfo(LineNum=4 DataType=0x1  DATA=RX: 09 05 04 01 00 00 00 07 00 00 00 00 00 00 00 00)

1.000 MENU_REQ_TX_INFO: CALL DSM_SendTxInfo_20(#4 DATA=TX: 0x20 0x06 04 04 00 00)

1.100 MENU_REQ_TX_INFO: RESPONSE ReqTXInfo(LineNum=5 DataType=0x1  DATA=RX: 09 05 05 01 00 00 00 07 00 00 00 00 00 00 00 00)

1.150 MENU_REQ_TX_INFO: CALL DSM_SendTxInfo_20(#5 DATA=TX: 0x20 0x06 05 05 00 00)

1.210 MENU_REQ_TX_INFO: RESPONSE MenuLine: L[#0 T=M VId=0x1010 Text="Gyro settings"[0xF9]   MId=0x1000 ]

1.250 MENU_LINES: SEND DSM_getNextLine(MenuId=0x1000,LastLine=0)

1.360 MENU_LINES: RESPONSE MenuLine: L[#1 T=M VId=0x105E Text="Other settings"[0x227]   MId=0x1000 ]

1.400 MENU_LINES: SEND DSM_getNextLine(MenuId=0x1000,LastLine=1)

MENU_LINES: EVT_TOUCH_TAP 263,71

MENU_LINES: EVT_TOUCH_TAP 263,71

MENU_LINES: EVT_VIRTUAL_ENTER,  SelLine=0

2.610 MENU_LINES: DSM_GotoMenu(0x1010,LastSelectedLine=0)

2.620 MENU_TITLE: SEND DSM_getMenu(MenuId=0x1010 LastSelectedLine=0)

2.720 MENU_TITLE: RESPONSE Menu: M[Id=0x1010 P=0x0 N=0x0 B=0x1000 Text="Gyro settings"[0xF9]]

2.760 MENU_LINES: SEND DSM_getFirstMenuLine(MenuId=0x1010)

2.810 MENU_LINES: RESPONSE MenuLine: L[#0 T=M VId=0x1011 Text="AS3X Settings"[0x1DD]   MId=0x1010 ]

2.870 MENU_LINES: SEND DSM_getNextLine(MenuId=0x1010,LastLine=0)

2.980 MENU_LINES: RESPONSE MenuLine: L[#1 T=M VId=0x1019 Text="SAFE Settings"[0x1E2]   MId=0x1010 ]

3.040 MENU_LINES: SEND DSM_getNextLine(MenuId=0x1010,LastLine=1)

3.130 MENU_LINES: RESPONSE MenuLine: L[#2 T=M VId=0x1021 Text="F-Mode Setup"[0x87]   MId=0x1010 ]

3.190 MENU_LINES: SEND DSM_getNextLine(MenuId=0x1010,LastLine=2)

3.300 MENU_LINES: RESPONSE MenuLine: L[#3 T=M VId=0x1022 Text="System Setup"[0x86]   MId=0x1010 ]

3.340 MENU_LINES: SEND DSM_getNextLine(MenuId=0x1010,LastLine=3)

5.360 MENU_LINES: INACTIVITY TIMEOUT

5.420 WAIT_CMD: SEND DSM_sendHeartbeat()

WAIT_CMD: EVT_TOUCH_TAP 306,125

WAIT_CMD: EVT_TOUCH_TAP 306,125

WAIT_CMD: EVT_VIRTUAL_ENTER,  SelLine=2

5.690 WAIT_CMD: DSM_GotoMenu(0x1021,LastSelectedLine=2)

5.690 MENU_TITLE: SEND DSM_getMenu(MenuId=0x1021 LastSelectedLine=2)

5.780 MENU_TITLE: RESPONSE Menu: M[Id=0x1021 P=0x0 N=0x0 B=0x1010 Text="F-Mode Setup"[0x87]]

5.830 MENU_LINES: SEND DSM_getFirstMenuLine(MenuId=0x1021)

5.930 MENU_LINES: RESPONSE MenuLine: L[#0 T=V_nc VId=0x1000 Text="Flight Mode"[0x8001] Val=nil [0->10,0] MId=0x1021 ]

5.980 MENU_LINES: SEND DSM_getNextLine(MenuId=0x1021,LastLine=0)

6.080 MENU_LINES: RESPONSE MenuLine: L[#1 T=M VId=0x7CA6 Text="FM Channel"[0x78]   MId=0x1021 ]

6.140 MENU_LINES: SEND DSM_getNextLine(MenuId=0x1021,LastLine=1)

6.230 MENU_LINES: RESPONSE MenuLine: L[#2 T=LM VId=0x1002 Text="AS3X"[0x1DC] Val=nil NL=(0->1,0,S=3) [3->4,3] MId=0x1021 ]

6.290 MENU_LINES: SEND DSM_getNextLine(MenuId=0x1021,LastLine=2)

6.400 MENU_LINES: RESPONSE MenuLine: L[#3 T=LM VId=0x1003 Text="Safe Mode"[0x1F8] Val=nil NL=(0->244,3,S=0) [0->244,3] MId=0x1021 ]

6.460 MENU_LINES: SEND DSM_getNextLine(MenuId=0x1021,LastLine=3)

6.550 MENU_LINES: RESPONSE MenuLine: L[#4 T=LM VId=0x1004 Text="Panic"[0x8B] Val=nil NL=(0->1,0,S=3) [3->4,3] MId=0x1021 ]

6.610 MENU_LINES: SEND DSM_getNextLine(MenuId=0x1021,LastLine=4)

6.660 MENU_LINES: RESPONSE MenuLine: L[#5 T=LM VId=0x1005 Text="High Thr to Pitch"[0x1F0] Val=nil NL=(0->1,0,S=3) [3->4,3] MId=0x1021 ]

6.700 MENU_LINES: SEND DSM_getNextLine(MenuId=0x1021,LastLine=5)

6.810 MENU_LINES: RESPONSE MenuLine: L[#6 T=LM VId=0x1006 Text="Low Thr to Pitch"[0x1EF] Val=nil NL=(0->1,0,S=3) [3->4,3] MId=0x1021 ]

6.870 MENU_LINES: SEND DSM_getNextLine(MenuId=0x1021,LastLine=6)

6.970 MENU_LINES: RESPONSE MenuValue: UPDATED: L[#0 T=V_nc VId=0x1000 Text="Flight Mode"[0x8001] Val=1 [0->10,0] MId=0x1021 ]

7.000 MENU_VALUES: SEND DSM_getNextMenuValue(MenuId=0x1021, LastValueId=0x1000) Extra: Text="Flight Mode"

7.060 MENU_VALUES: RESPONSE MenuValue: UPDATED: L[#2 T=LM VId=0x1002 Text="AS3X"[0x1DC] Val=1|"Act" NL=(0->1,0,S=3) [3->4,3] MId=0x1021 ]

7.120 MENU_VALUES: SEND DSM_getNextMenuValue(MenuId=0x1021, LastValueId=0x1002) Extra: Text="AS3X"

7.170 MENU_VALUES: RESPONSE MenuValue: UPDATED: L[#3 T=LM VId=0x1003 Text="Safe Mode"[0x1F8] Val=176|"Self-Level/Angle Dem" NL=(0->244,3,S=0) [0->244,3] MId=0x1021 ]

7.230 MENU_VALUES: SEND DSM_getNextMenuValue(MenuId=0x1021, LastValueId=0x1003) Extra: Text="Safe Mode"

7.330 MENU_VALUES: RESPONSE MenuValue: UPDATED: L[#4 T=LM VId=0x1004 Text="Panic"[0x8B] Val=1|"Act" NL=(0->1,0,S=3) [3->4,3] MId=0x1021 ]

7.380 MENU_VALUES: SEND DSM_getNextMenuValue(MenuId=0x1021, LastValueId=0x1004) Extra: Text="Panic"

7.470 MENU_VALUES: RESPONSE MenuValue: UPDATED: L[#5 T=LM VId=0x1005 Text="High Thr to Pitch"[0x1F0] Val=0|"Inh" NL=(0->1,0,S=3) [3->4,3] MId=0x1021 ]

7.610 MENU_VALUES: SEND DSM_getNextMenuValue(MenuId=0x1021, LastValueId=0x1005) Extra: Text="High Thr to Pitch"

7.700 MENU_VALUES: RESPONSE MenuValue: UPDATED: L[#6 T=LM VId=0x1006 Text="Low Thr to Pitch"[0x1EF] Val=0|"Inh" NL=(0->1,0,S=3) [3->4,3] MId=0x1021 ]

7.760 MENU_VALUES: SEND DSM_getNextMenuValue(MenuId=0x1021, LastValueId=0x1006) Extra: Text="Low Thr to Pitch"

9.780 MENU_VALUES: INACTIVITY TIMEOUT

9.910 WAIT_CMD: SEND DSM_sendHeartbeat()

11.960 WAIT_CMD: INACTIVITY TIMEOUT

12.020 WAIT_CMD: SEND DSM_sendHeartbeat()

13.310 WAIT_CMD: RESPONSE MenuValue: UPDATED: L[#0 T=V_nc VId=0x1000 Text="Flight Mode"[0x8001] Val=2 [0->10,0] MId=0x1021 ]

13.440 MENU_VALUES: SEND DSM_getNextMenuValue(MenuId=0x1021, LastValueId=0x1000) Extra: Text="Flight Mode"

13.530 MENU_VALUES: RESPONSE MenuValue: UPDATED: L[#3 T=LM VId=0x1003 Text="Safe Mode"[0x1F8] Val=3|"Inh" NL=(0->244,3,S=0) [0->244,3] MId=0x1021 ]

13.590 MENU_VALUES: SEND DSM_getNextMenuValue(MenuId=0x1021, LastValueId=0x1003) Extra: Text="Safe Mode"

15.610 MENU_VALUES: INACTIVITY TIMEOUT

15.680 WAIT_CMD: SEND DSM_sendHeartbeat()

15.890 WAIT_CMD: RESPONSE MenuValue: UPDATED: L[#0 T=V_nc VId=0x1000 Text="Flight Mode"[0x8001] Val=1 [0->10,0] MId=0x1021 ]

15.930 MENU_VALUES: SEND DSM_getNextMenuValue(MenuId=0x1021, LastValueId=0x1000) Extra: Text="Flight Mode"

16.120 MENU_VALUES: RESPONSE MenuValue: UPDATED: L[#3 T=LM VId=0x1003 Text="Safe Mode"[0x1F8] Val=176|"Self-Level/Angle Dem" NL=(0->244,3,S=0) [0->244,3] MId=0x1021 ]

16.150 MENU_VALUES: SEND DSM_getNextMenuValue(MenuId=0x1021, LastValueId=0x1003) Extra: Text="Safe Mode"

18.190 MENU_VALUES: INACTIVITY TIMEOUT

 

 

 

 

 



 

 

 

Clark Harbaugh

**Comment by frankiearzu** [comment]
Charles,
The important lines are the ones with UPDATED value for the Flight Mode line.. I filter only those lines below:
```
6.970 MENU_LINES: RESPONSE MenuValue: UPDATED: L[#0 T=V_nc VId=0x1000 Text="Flight Mode"[0x8001] Val=1 [0->10,0] MId=0x1021 ]
13.310 WAIT_CMD: RESPONSE MenuValue: UPDATED: L[#0 T=V_nc VId=0x1000 Text="Flight Mode"[0x8001] Val=2 [0->10,0] MId=0x1021 ]
15.890 WAIT_CMD: RESPONSE MenuValue: UPDATED: L[#0 T=V_nc VId=0x1000 Text="Flight Mode"[0x8001] Val=1 [0->10,0] MId=0x1021 ]
15.890 WAIT_CMD: RESPONSE MenuValue: UPDATED: L[#0 T=V_nc VId=0x1000 Text="Flight Mode"[0x8001] Val=1 [0->10,0] MId=0x1021 ]
```
That means that the RX is only using 2 flight modes.  (Val=1:Flight Mode 2, and Val=2:Flight Mode 3, what is missing is the Val=0: Flight Mode 1).

This is information that the RX is sending the TX script to display.. so the problem is outside the script.
the Flight Mode 1 (Val=0) is usually done when your switch is in the -100 range  (or +100 if reversed).

Did a little experiment, change the ch to transmit the THR for the flight mode.
what i saw:   (-100 -90) Flight Mode 1, (-89 -6) Flight Mode 3,  (-5 +5) Flight Mode 2, (+6 +89) Flight Mode 3, (+90 +100) Flight Mode 3.

What i see is that unless the switch output is within 10% of the intended end, it defaults to FM3 (Val=2).
I think one of your ends (either +100, or +100) is not reaching the intended output expected by the RX.

Check that your output for the switch channel is sending 988us for -100, 1500us for 0, and 2012us for +100. (or close to it);
You can go to model setup->output page, edit the channel for your output switch, and you should see something like this the next image.
At the end, the RX behaves bases on the duration of the pulse that is receiving, the value with "us" (micro seconds). 

![image](https://user-images.githubusercontent.com/32604366/208542150-797dc950-60be-4eed-9bec-52c9d7be00d1.png)

**Comment by charbaugh1** [comment]
I appreciate all of your help on this.  I’ll continue to chase it on my own, since it appears to be either a TX or RX hardware issue.  I’m betting it’s an RX issue, since all of my settings and parameters on the TX match yours (confirmed the 988, 1500, and 2012us for each position). By the fact there are two “Val=1” entries in a row shows where I physically switched to FM1, but the receiver didn’t receive/respond appropriately.    

 

And thank you so much for doing the work and programming of the script!

 

Clark Harbaugh
