### ISSUE TITLE
TX12 mkii "no telemetry" after bad flash

### ISSUE THREAD

**Issue by Mr-Meaty** [pascallanger/DIY-Multiprotocol-TX-Module#788]
Hello,  I am posting in here because there was an older thread on the older TX12 that was solved here, and I am having the same issue with the new TX12 mkii.  I was attempting to flash the internal cc2500 MPM module from 1.3.3.7 to 1.3.3.20 but wasn't sure if I needed the 64kb version or not.  Someone said if one doesn't work, flash the other, so I tried both.  Both said complete but module still said 1.3.3.7, so I tried the version that was downloaded in EdgeTX Companion but I think that was actually for the 4in1 module.  Now my module simply says "no telemetry" and when trying to flash any of the .bin I have from original or found here it says "FW update error device not responding".
Any help would be appreciated.

**Comment by aragor88** [comment]
I have same problem with "FW update error device not responding"
Firstly open transmitter and find out version of MCU => if is C8 or CB https://www.multi-module.org/basics/module-hardware/unsupported-modules
