### ISSUE TITLE
Serial Mode: 258 bad protocol

### ISSUE THREAD

**Issue by hdlbq** [pascallanger/DIY-Multiprotocol-TX-Module#811]
Hi,
Thanks for your great job.
I experienced the following problem:
I use the Serial Mode in my RadioMaster TX12 MkII.
I use the "MULTI" mode
When I try to choose the right protocol, I got the 258 value, that can't be changed.
One solution to get another value is to put the module OFF, then select "MULTI" again.
The module choose the "Flysky" protocol, but if I try to have another value, it goes often to the 258 invalid protocol value.
Thanks for your help.
Firmware versions:
IrangeX IRx4 Plus: V1.2.0.22 (associted to the Flysky protocol chosen by default when the Module is turned on)
TX12 : edgetx-tx12mk2 vers 2.8.0-selfbuild, GIT#d982f5fc, CFGV 221

**Comment by pascallanger** [comment]
v1.2.0.22 really ? This is so old that most likely edgetx doesn't know how to use it properly... Upgrade your module to the latest v13.3.3.20 https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/releases .
