### ISSUE TITLE
BUG: SX1276_INSTALLED define in line 361 of Validate.h incorrect

### ISSUE THREAD

**Issue by OpenUAS** [pascallanger/DIY-Multiprotocol-TX-Module#812]
in line 361 of Validate.h

`#ifndef SX1276_INSTALLED || defined MULTI_EU `

likely should be:

```
#if not defined(SX1276_INSTALLED) || defined(MULTI_EU)
	#undef FRSKYR9_SX1276_INO
#endif
```

But even then if syntactic correct an it was the code writers intention that way with OR, I do not see the logic. I do have an 868(EU) FrSkyR9 module so the reason for the #undef is unclear to me.

 but must amid did not read through all the code, just since the error came up while compiling

**Comment by pascallanger** [comment]
I'll correct that, thanks

**Comment by pascallanger** [comment]
Done
