### ISSUE TITLE
Zorro, ETX 2.8.0, KX: invalid protocol

### ISSUE THREAD

**Issue by bernd25** [pascallanger/DIY-Multiprotocol-TX-Module#827]
Hello,
 since the ETX 2.8.0 update for Zorro, I can no longer use my VTOL from Wtoys. Under KX it now says 'invalid protocol'. When I flash to the older ETX version, I don't have the problem. The behavior is independent of the MMP version.
What is the reason?

**Comment by bernd25** [comment]
Sorry, I meant protocol "XK" , subtype X450.

**Comment by pascallanger** [comment]
As you say it's independent of the MPM version so the issue is in EdgeTX. Please open an issue on their github.
