### ISSUE TITLE
Zorro- While selecting Protocol Type, Unable to scroll in reverse from Config.

### ISSUE THREAD

**Issue by KC748** [pascallanger/DIY-Multiprotocol-TX-Module#832]
Greetings.
I initially posted the following issue with EdgeTx, but 3djc suggested the issue may be on the Multi side. So please have a look.

In EdgeTx v2.8.1, Model Setup, it is possible to scroll past the last protocol, (XK currently) to the beginning of the list, Config. However, from Config, it is not possible to scroll in reverse, back to the last protocol.

Over shooting the last protocol is quite easy and it's a little annoying having to scroll all the way back to the end of the list from the beginning.

![ProtocolConfig](https://user-images.githubusercontent.com/39738927/225456743-10465f04-d0d2-46d9-8fff-98a9719aa77f.jpg)

Would it be possible to allow scrolling in reverse from Config to the end of the protocol list?
Or. a hard stop at the end of the list. A haptic and/or beep at the stop would be nice.

Thanks.

**Comment by pascallanger** [comment]
Hummm, I'm pretty sure I'm doing a roll over on both sides. I'll check tomorrow on opentx to check the behavior there.

**Comment by pascallanger** [comment]
Old EdgeTX issue.
