### ISSUE TITLE
No 64K option for Zorro CC2500 at downloads.multi-module.org/. 

### ISSUE THREAD

**Issue by KC748** [pascallanger/DIY-Multiprotocol-TX-Module#841]
TX12 has 64K firmware option at downloads.multi, but Zorro internal CC2500 does not.

A [member on RCG](https://www.rcgroups.com/forums/showthread.php?4027391-RadioMaster-ZORRO-is-here&postid=50729743) reported only the 64K version worked on his Zorro CC2500.

> I've succeeded binding the Zorro to the Rx.
…Then I upgraded to 1.3.3.20 and found that only the 64KB version did work.
>

**Comment by benlye** [comment]
64K option is available for the Zorro now.  

<img width="344" alt="image" src="https://user-images.githubusercontent.com/23322579/227545571-57d26fcd-ebd7-425c-a06a-3d48b8a22bf9.png">

I've asked RadioMaster to confirm if all Zorro CC2500 radios are 64KB (I suspect that they are).  Once they let me know I'll remove the non-64KB option for the Zorro CC2500.

**Comment by KC748** [comment]
That's terrific! Thank you.
