### ISSUE TITLE
Can MPM configured to use a single S.Port line for half duplex communication?

### ISSUE THREAD

**Issue by richardclli** [pascallanger/DIY-Multiprotocol-TX-Module#847]

**Comment by richardclli** [comment]
@pascallanger Any ideas?

**Comment by pascallanger** [comment]
Yes it can.
Some modules at the beginning where not correctly manufactured using a nand instead of a xor but other than that it's just code based.

**Comment by richardclli** [comment]
> Yes it can. Some modules at the beginning where not correctly manufactured using a nand instead of a xor but other than that it's just code based.

So need code modification?  Can you point out which file start with?

**Comment by pascallanger** [comment]
It's in the main and telemetry.

**Comment by richardclli** [comment]
Currently the serial protocol uses USART2 for receiving and USART3 for transmitting (with receiving disabled).  So try to configure USART3 for receiving instead of USART2 can make this works, right?  You use interrupt to handle receiving?

**Comment by pascallanger** [comment]
Sorry Richard, Do you still need help ?

**Comment by richardclli** [comment]
Abandoned this thought, no need anymore.
