### ISSUE TITLE
Bug: it's not working for WFly, bind WFR09S, only works several seconds then disconnected

### ISSUE THREAD

**Issue by ganggangdede** [pascallanger/DIY-Multiprotocol-TX-Module#851]

**Comment by ganggangdede** [comment]
Jumper T-Pro Internal Multi-Module, firewire: mm-stm-serial-aetr-v1.3.3.20.bin
TX firewire: opentx-T-Pro-2.3.15.bin
RX: WFly WFR09S
I tried other receivers such as FlySky Std and FrSky D8, it works well

**Comment by ganggangdede** [comment]
> Jumper T-Pro Internal Multi-Module, firewire: mm-stm-serial-aetr-v1.3.3.20.bin
> TX firewire: opentx-T-Pro-2.3.15.bin
> RX: WFly WFR09S
> I tried other receivers such as FlySky Std and FrSky D8, it works well



> Which module type? Which firmware version on the module? What's the global ID of the module? What's the RX number? Have you tried different RX numbers?

Jumper T-Pro Internal Multi-Module, firewire: mm-stm-serial-aetr-v1.3.3.20.bin
TX firewire: opentx-T-Pro-2.3.15.bin
RX: WFly WFR09S
I tried other receivers such as FlySky Std and FrSky D8, it works well

**Comment by ganggangdede** [comment]
> I suspect it could be a frequency issue, but the firmwire mm-stm-serial-aetr-v1.3.3.20.bin is disable the frequency tuning by default, can you please do me a fever to build the firewire with the frequency tuning enabled, so I can do a test

**Comment by pascallanger** [comment]
Can you try first different RX numbers before playing around with freq tuning?

**Comment by pascallanger** [comment]
No answer to my request for details, closing...
