### ISSUE TITLE
Since the last update, the message “need file” has come up

### ISSUE THREAD

**Issue by TheIsotopes** [pascallanger/DIY-Multiprotocol-TX-Module#862]
Would testing v1.3.3.27 but can not install on Zorro and TX16 with latest EdgeTX from master-branch.
The Message NEED FILE comes up:
![screen-2023-06-14-095759](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/assets/29702171/95e7969c-f2fd-4412-82ea-9bc0a40b37e3)

With v1.3.3.25 is all ok. @pascallanger pls can you check whats wrong.

**Comment by TheIsotopes** [comment]
thx @benlye for fixing this. 👍

**Comment by Talha909** [comment]
how to get the version V1.3.3.27. Do you have link for download.

**Comment by TheIsotopes** [comment]
look here -> https://github.com/pascallanger/DIY-Multiprotocol-TX-Module#development-status
