### ISSUE TITLE
betaflight-tx-lua-scripts do not work with v1.3.3.27

### ISSUE THREAD

**Issue by TheIsotopes** [pascallanger/DIY-Multiprotocol-TX-Module#866]
Since v1.3.3.27 the betaflight-tx-lua-scripts don't work anymore. The message "Waiting for API version" appears and the script must be terminated by pressing RTN for a long time. back to v1.3.3.25 and it works again.

@pascallanger pls can you check whats wrong.

**Comment by pascallanger** [comment]
Have you try to rebind your RX? Have you tried to redo the frequency tuning ?

**Comment by TheIsotopes** [comment]
I forgot to write that this affects FrSkyX2 EU. Here some screenshot:

![screen-2023-06-17-193404](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/assets/29702171/cdba6101-6b80-46fa-a906-dbebdcb60468)

![screen-2023-06-17-193424](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/assets/29702171/df9c5eb8-a437-426a-9032-0f98d45e1c99)

When flying there's no problems and telemetry also works.

> Have you try to rebind your RX? Have you tried to redo the frequency tuning ?

@pascallanger I can try and get back to you later.

**Comment by TheIsotopes** [comment]
@pascallanger Newly bound and frequency tuned, unfortunately the problem still exists.

**Comment by TheIsotopes** [comment]
@pascallanger found the problem, it's https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/commit/cefe69a692f07d4621a2cd8a2ed972f4ace501d6. if I undo this, betaflight-tx-lua-scripts works again.

**Comment by MRC3742** [comment]
This problem also effects using any of the UNI-RX scripts.
All telemetry is working but will not populate any fields in the scripts.
MPM version 1.3.3.27 and Protocol is FrSkyX2 D16 FCC

The linked PR listed above cures the problem with these scripts also.

Rich

**Comment by Talha909** [comment]
what is the link of this MPM version 1.3.3.27. i cant able to found this.
