### ISSUE TITLE
Telemetry protocol (DIY radio module) on 9XR PRO

### ISSUE THREAD

**Issue by Kozma04** [pascallanger/DIY-Multiprotocol-TX-Module#874]
As the title says, I am working on a custom RF module for my Turnigy 9XR Pro with OpenTX. I have been looking for the specific packet protocol format for OpenTX telemetry sensor reporting (between 9XR PRO and its attached RF module) with no success. 

Until now, I was programming my module to work with the Multiprotocol TX protocol setting, under the External RF menu. I managed to have my module properly receive the channel input values and send valid telemetry status packets to the 9XR PRO (it displays the custom module version in the menu), but that's about it. I can't figure out how to send telemetry packets, for various sensors too.

Please, can somebody help me find a proper starting point for the OpenTX telemetry protocol (preferably the exact packet frame format)? I have been trying to use the S.PORT sensor telemetry implementation from the Multiprotocol TX module source code, but my RC does not recognize anything.

**Comment by pascallanger** [comment]
You you should use ERSKYTX instead which supports the 9XR PRO and fully the Multi module.
