### ISSUE TITLE
Horus X12S with Radiomaster RM4in1

### ISSUE THREAD

**Issue by jimmy6616** [pascallanger/DIY-Multiprotocol-TX-Module#880]
Running edge 2.8.3 on an X12S which i purchased second hand to upgrade from my aging Jumper

I purchased a Radiomaster RM4in1 Multi to use with my Frsky , Jumper and SFHSS Rx's

The module works fine im my Jumper, binds, shows RSSI and all telemetry.

In the X12S, different story. Seems to bind okay, No RSSI or any telemetry and the staus in info says 'No MULTI_TELEMETRY detected'
Maybe a Edge config issue or script on the X12 missing. When i connect to a Frsky X6R using the internal module everything is fine

Any help would be appreciated

**Comment by pascallanger** [comment]
Solution in issue https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/issues/621

**Comment by jimmy6616** [comment]
Try these photos if it help please
![RM_2](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/assets/58522146/3015e2ed-6f46-438e-8833-e5d017e07a46)
![RM_1](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/assets/58522146/11712002-9b59-4b81-88d9-14660e2c49e4)

**Comment by pascallanger** [comment]
Sorry these pictures are too fuzzy. Take sharp pictures so I can see the traces.

**Comment by jimmy6616** [comment]
Are these better? Jim
![IMG_8117](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/assets/58522146/2d177634-e979-483e-a22a-057558b75d3b)
![IMG_8115](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/assets/58522146/3ddf8c90-3226-4aa3-814e-38295a42e06f)

**Comment by Merga189** [comment]
Same issue here. RADIOMASTER RM 4IN1 NOT working with FrSky X10 S Express. But as Pascal closed this one here, I'll shift over to #621
