### ISSUE TITLE
Radiomaster RM4in1

### ISSUE THREAD

**Issue by jimmy6616** [pascallanger/DIY-Multiprotocol-TX-Module#881]
Sorry to mention again as original closed. The links in the photos for the wire jumper  don’t match the RM4in1

these are the photos, if you would be so kind and advise 
![IMG_8096](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/assets/58522146/31874d46-c2ce-4fb4-8ead-1323f5491ee2)
![IMG_8095](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/assets/58522146/ab515670-b89d-4c52-93ec-e97b529baca7)

**Comment by sloped-soarer** [comment]
Sorry, I personally cannot help. But what ARM chip is fitted on that Radiomaster 4in1 module ?.
Was the mobule from a TX16S or Boxer ?.
