### ISSUE TITLE
Request : MM LUA scripts for Ethos radios

### ISSUE THREAD

**Issue by J-charles-C** [pascallanger/DIY-Multiprotocol-TX-Module#882]
Good morning,

Are you thinking of making LUA scripts compatible with Ethos radios?

Thanks

**Comment by pascallanger** [comment]
I thought Ethos was not even recognizing the multi module and that you have to use it in PPM mode. Has it changed ?

**Comment by J-charles-C** [comment]
I,
Multi module was added a while ago.

https://github.com/FrSkyRC/ETHOS-Feedback-Community/releases/tag/1.3.0

A future version 1.5.0, currently in beta, will also add telemetry.

I don't know if it's serial or PPM.

Thanks

**Comment by pascallanger** [comment]
Anyway, I don't have any radio supporting ETHOS. If someone wants to give it a go, I'll just file them here.
