### ISSUE TITLE
Compilation problem: no more space

### ISSUE THREAD

**Issue by robustini** [pascallanger/DIY-Multiprotocol-TX-Module#893]
Hi Pascal, I am trying to compile the master but I think something will have to be given up:

The sketch uses 121708 bytes (100%) of the space available for programs. The maximum is 120808 bytes.

Regards,

Marco

**Comment by pascallanger** [comment]
Yes I know, it's from my latest commit yesterday evening. You can check here: https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/actions

**Comment by robustini** [comment]
Thanks mate.
