### ISSUE TITLE
Flip for the c129 v2

### ISSUE THREAD

**Issue by Ciolouse** [pascallanger/DIY-Multiprotocol-TX-Module#899]
Greetings,

It is not really a Issue, but can you add the Flip to the RC ERA c129 v2, please ?

Like explained by roger_1994 in this tread :
https://www.rcgroups.com/forums/showthread.php?4260387-Rc-era-c129-v2

Merci d'avance :)

**Comment by pascallanger** [comment]
Available in v1.3.3.35
