### ISSUE TITLE
Bind SFHSS failed！

### ISSUE THREAD

**Issue by zyren** [pascallanger/DIY-Multiprotocol-TX-Module#9]
Hi Pascal,

I use the last code and I don't bind, with anithing futaba receivers, and WL_TOYS XK110 failed too.
Expect improvement,thanks.

regards.

**Comment by zyren** [comment]
_config.h:

/*1*/	{MODE_SFHSS,	0,	0,	P_HIGH	,	NO_AUTOBIND,	0},

**Comment by pascallanger** [comment]
Hi Zyren,
I've already tried to check a lot of things but I can't see what's going wrong.
I don't have any SFHSS RX to test myself... So unless someone sends me something to work on, I don't see how to solve this issue.
- Pascal

**Comment by anshengchang** [comment]
I have the same issue.
Who could help me!!!
pascallanger, Where do you live???

**Comment by pascallanger** [comment]
I leave in France.
- Pascal

**Comment by zyren** [comment]
Hi Pascallanger,
I saw someone say deviationTx, the options set between +25 to +95, perfect binding XK110 and XK120 ,, I will try tomorrow, then come back to report the results.
regards,
zyren.

**Comment by qdog2012** [comment]
hi zyren, how is your test result? i have this issue too.

**Comment by qdog2012** [comment]
Multiprotocol code version：2.1.8 mult 0803
TX type: x9d plus
Using PPM or Serial: serial
Explanation of the behavior and reproduction steps: can not bind xk120 with sfhss protocol. using 4in1 module.

**Comment by qdog2012** [comment]
Multiprotocol code is latest version

**Comment by pascallanger** [comment]
Have you tried to shift the frequency using the option value? You need to try all the values...But anyway if there is an issue I don't have any RX to test the code on.
- Pascal

**Comment by qdog2012** [comment]
i have tried to shift the frequency using the all option values, still no work.
i have a D10 tx, using deviation, it work for me.

**Comment by pascallanger** [comment]
I'll check once again but I have little hope without a RX...

**Comment by pascallanger** [comment]
I've just posted a new source version. Try to compile and test.

**Comment by qdog2012** [comment]
thank you, but i can't see the new commit or new code in the github? 
Latest commit 9e902a5  8 days ago

**Comment by pascallanger** [comment]
I'm on my mobile connection so syncing is slow, retry.

**Comment by qdog2012** [comment]
okay, i got the new code. i'll try it later and post my test result. thanks again.

**Comment by qdog2012** [comment]
hi pascallanger, i have tested the new code, still no work.
i realize when i using the ppm mode and s-fhss protocol, press and hold the bind button, the red light is turn off, unless release the bind button, is that mean the tx not going start to bind?

**Comment by qdog2012** [comment]
is any thing i can do for help?

**Comment by pascallanger** [comment]
Hold on. The TX does not enter bind mode, it's only the RX which binds with any TX around it.
Pressing the bind button will always turn off the LED since you shortcut it, this is not the program doing it but you are.
Have you really tried all the option values from -127 to +127 and try to bind the RX each time you are making a change???

**Comment by qdog2012** [comment]
yes, i tried all the option values from -127 to +127 bind the RX each time making a change with SPI mode. my RX is XK120.

**Comment by pascallanger** [comment]
On the Devo, have you changed fine or coarse to get it to work?

**Comment by qdog2012** [comment]
on the Devo, my version is no fine or coarse option, only bind button in the GUI.

**Comment by pascallanger** [comment]
I've just published a new version, please compile, try with different option values and report.
Thanks, Pascal

**Comment by qdog2012** [comment]
ok, i'll report test result when i tried all option values.

**Comment by pascallanger** [comment]
I've just published a new version (again), please compile, try with different option values and report.
Thanks, Pascal

**Comment by qdog2012** [comment]
bad news, the latest code is no work.
i have order a new single cc2500 module, may be only the 4in1 module do not work.

**Comment by pascallanger** [comment]
Really... Couple of questions:
 - Have you tested the latest version posted 2 hours ago?
 - Have you tested your CC2500 with another protocol to make sure it works? FrSky or FrSkyX?
 - Could you try to increase the delay line 104 : delayMicroseconds(6);  try to change the 6 by 100, 200,...

**Comment by pascallanger** [comment]
FYI, people on the RCG forum have reported it to at least bind so it should do the same for you. But it's still unstable. I would like to test changing the delay...

**Comment by qdog2012** [comment]
yeah, i can bind with RX, looks bind needs the RX so close. after RX bind ok. i have no any action, the red light is blink and irregular, since always getting TX signal. my option values is 18 to 95.
when i control the TX, the RX is slow reaction and not smooth.

**Comment by pascallanger** [comment]
It should be solved on the latest version please confirm.
