### ISSUE TITLE
Binding problem to devo protocol.

### ISSUE THREAD

**Issue by Sunnyjalaf** [pascallanger/DIY-Multiprotocol-TX-Module#90]
I have been trying to connect to devo protocol with my 4 in 1 module but no luck, i have walkera runner 250 with RX710 receiver, i flashed 4 in 1 module to latest firmware and selected CYRF6936 chip protocols and i also followed instructions on github page for binding to devo receiver but no luck, any help will be appreciated. Thanks

**Comment by pascallanger** [comment]
You really need to look at the LEDs status of both the 4in1 module and the RX. The Devo protocol is not easy to bind. Follow the instructions at the letter or it will fail.
