### ISSUE TITLE
Traxxas #6533 TQi

### ISSUE THREAD

**Issue by inventor7777** [pascallanger/DIY-Multiprotocol-TX-Module#927]
I know support for Traxxas vehicles has been requested in other threads. But I don't know about the TQi 6533 receiver.

Is it possible to add support for this receiver as well? This binds to any current Traxxas transmitter, but it doesn't seem to work with my Multimodule RadioMaster MT12 (under the 6519 Traxxas mode)

Attached are photos of the circuits on the 6533 TQi 5 channel receiver with telemetry.

If you need more info I will be happy to send it!

Thank you very much for the amazing Multi-module project and hoping to see even more support in future! :)

![tempImageKtPqGe](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/assets/142270525/3961bd3a-8a87-4654-8f2b-7f1d35ef05fd)
![tempImagesW1n53](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/assets/142270525/5ac95d1a-a607-47e7-81d6-79f2fba741eb)
![tempImagesUZuEo](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/assets/142270525/2db641c2-535d-46bc-b16e-e97a1736c4e5)
![tempImageKNIh4e](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/assets/142270525/75cd459a-18c6-4a4c-aa36-61fcf19d19ef)
![tempImageKcF8VD](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/assets/142270525/99e33b67-3772-496e-ac6d-c7d79739b627)

**Comment by SomeBdyElse** [comment]
This seems related to #913
