### ISSUE TITLE
Support Eachine E017

### ISSUE THREAD

**Issue by patman13** [pascallanger/DIY-Multiprotocol-TX-Module#931]
Hello,
I used the E010 a lot with multiprotocol.
New I use the E017 but can't find a proper Protocol in multi protocol.
Would it be possible to support that?

**Comment by pascallanger** [comment]
May be if I have access to the TX + RX

**Comment by pascallanger** [comment]
Interesting. The protocol was never tested so this is great.
It is locked with only 1 ID right now. Are you able to test if I enable a different ID?

**Comment by pascallanger** [comment]
Please test the latest version available here which includes multi IDs for this protocol: https://downloads.multi-module.org/latest-test/

**Comment by pascallanger** [comment]
Completed
