### ISSUE TITLE
Eazyrc new protocol request 

### ISSUE THREAD

**Issue by vladovg** [pascallanger/DIY-Multiprotocol-TX-Module#941]
Hy Pascal i have one of these 1/18 crawlers and decided to dump it.

XN297LBW  3 wire SPI

![71vav9NbDJL _AC_SL1358_1346x1358](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/assets/19390563/01335204-fdd0-417b-b9b1-010c3eaf33ec)
![20240206_223821](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/assets/19390563/5a87cc62-eea8-4816-b8fc-e09b928eb790)
![20240206_223731](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/assets/19390563/d1722397-678d-47c1-826c-c664ed379dc7)
![20240206_223657](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/assets/19390563/62cfafda-af10-41e1-b9a5-2074b21973c6)

[Eazyrc.zip](https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/files/14201923/Eazyrc.zip)

Hope you can make something with it.

**Comment by pascallanger** [comment]
Do you have any buttons/features for example lights?

**Comment by pascallanger** [comment]
Do you have to put the car in bind mode?

**Comment by pascallanger** [comment]
I'm starting the implementation. There are quite some unknowns so let's see how it will work out.
I do not plan to store the car RX ID. The radio will stay on bind waiting for the car to be powered on. If you power cycle the car then you'll need to launch a new bind on the radio (which I don't think you need to do right now).

**Comment by pascallanger** [comment]
I've added the protocol under SFC (surface). As I said there are a lot of unknowns and I can't really test it... It's currently using your original TX ID and hopping frequencies, we will have to do further tests.
Please test and report, test builds are located here: https://downloads.multi-module.org/latest-test/
Documentation: https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/Protocols_Details.md#eazyrc---61

**Comment by vladovg** [comment]
Unfortunately it's not binding.

**Comment by pascallanger** [comment]
Does the bind stop?

**Comment by pascallanger** [comment]
Grrr I have an idea, hold on a few minutes

**Comment by pascallanger** [comment]
Test again

**Comment by vladovg** [comment]
It's working:) great job tank you.  
Buy the way new file names are too long for edgetx MT12.

**Comment by pascallanger** [comment]
Name too long: that's a known issue....
Ok we need to do more tests to enable multiple IDs frequency dump.
Do you know how to compile by yourself?

**Comment by vladovg** [comment]
You want me to change TX ID and see if it works?

**Comment by pascallanger** [comment]
Try to comment (add // before):
https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/af47462ba79eb86e19d8bc6c4685717bd81bd7bf/Multiprotocol/EazyRC_nrf24l01.ino#L19

**Comment by vladovg** [comment]
It works thank you again :)

**Comment by pascallanger** [comment]
Great, before we can it done and with the modification above, can you try on the radio a couple of RX numbers? That will create different IDs and hopping frequencies.

**Comment by vladovg** [comment]
IDs are working:)

**Comment by pascallanger** [comment]
I've pushed a final version. Please test a few rx numbers as shown above. Then we call it done.

**Comment by vladovg** [comment]
Everything works as described 👌 great job thank you.
