### ISSUE TITLE
FrSky X D16 and Futaba SFHSS Failsafe Issue

### ISSUE THREAD

**Issue by qsiguy** [pascallanger/DIY-Multiprotocol-TX-Module#945]
Radiomaster R88 V2 receiver.  MPM firmware 1.3.3.33 in use.  Confirmed issue with Radiomaster TX16S EdgeTX 2.9.4 and Radiomaster Zorro EdgeTX 2.9.4.  When connected to the receiver via FrSky X D16 Ch1-8 with telemetry or Futaba SFHSS, no failsafe modes or settings are being sent to the receiver from the transmitter 4in1 module menu for hold, custom, etc.  The only way I've been able to set failsafe settings is to power on the RX, wait 6 seconds, hold the sticks in the desired position, and press the RX bind button for a couple seconds (within 10 seconds).  This will store failsafe settings and does function.

1. Am I missing a step to "write" the failsafe settings from the radio?
2. Is it a bug in the MPM 1.3.3.33 firmware?
3. Is it a bug with EdgeTX?
4. Is it a limitation of the Radiomaster R88 V2?

Can anyone duplicate my issue or test with an FrSky branded receiver to see if it perhaps is a Radiomaster R88 V2 limitation?

**Comment by pascallanger** [comment]
From a multi perspective, FrSkyX (X and X2 supports falsafe, not D or V) and SFHSS protocols are sending failsafe all the time when it is configured on the radio.
The fact that you have a way to set failsafe from the RX itself seems to indicate that it doesn't support failsafe to be set from the radio...
I can confirm that it works on a genuine FrSky RX.
