### ISSUE TITLE
Kyosho Protocol invalid subtype

### ISSUE THREAD

**Issue by Jangyyie** [pascallanger/DIY-Multiprotocol-TX-Module#958]
I have a Jumper external 4in1 external module upgrade to 1.3.4.0 and the Kyosho Protocol subtype come up with invalid protocol, to fix the problem downgraded to 1.3.3.14 and now has FHSS as a subtype.

**Comment by pascallanger** [comment]
Kyosho FHSS is a surface protocol so available in the SFC build but not in AIR. Which build have you used?
If you need a mix of both you need to compile the code by yourself as there is not enough flash space to store all the protocols.

**Comment by Jangyyie** [comment]
Thanks for your help
