### ISSUE TITLE
AFHDS2A nfr24l01+

### ISSUE THREAD

**Issue by Didr0** [pascallanger/DIY-Multiprotocol-TX-Module#959]
hello, I noticed that among the files you created there are many codes .ino and one of these is AFHDS2A_a7105.ino, I’m trying to build a receiver for a flysky transmitter, I was wondering if it was possible to implement the AFHDS2A protocol with nrf24l01+ module and how to receive data after pairing the transmitter to nrf24l01+. (I have already read the documentation and you have not inserted flysky in the transmitters supported by nrf24l01+ but I thought it was only for better communication since on flysky radio there is a module a7105)

edit:
I’m very interested in understanding how it works, I prefer to learn instead of having a ready code but I usually use libraries while I see that you directly use the addresses of the registers of the modules you integrate. If there is a way to do it with the RF24.h library I just need to know what I have to do, if I have to act on the registers I will need much more help

**Comment by pascallanger** [comment]
Afhds2a is using an a7105 which can't be related with a nrf24l01+. You need to select a nrf or xn297 protocol

**Comment by pascallanger** [comment]
Since it's not an issue but rather a discussion, please use the discussion thread instead.
