### ISSUE TITLE
Multi module not selectable in Ethos 1.5.6

### ISSUE THREAD

**Issue by davidr00001** [pascallanger/DIY-Multiprotocol-TX-Module#968]
Twxlite running ethos 1.5.6.  Trying to setup i-range 4in1 multi module. Created the scripts folder /scripts/multi/main.lua (with multi lua file). When going to model/RF system/external module/Type, the Multi module is not there to select.
I then added Crossfire and ERS just to see if they would show up.  They show in Type menu, but Multi still does not show up.  Finally put the Multi lua (as main.lua) file into Crossfire folder.  Mutimodule now works, but Multi still does not show up in Type select menu.

**Comment by geofrancis** [comment]
frsky don't want to support anything but frsky, this is why they have stopped using opentx and changed to archer firmware, so you need to buy their receivers.
