### ISSUE TITLE
HI.

### ISSUE THREAD

**Issue by sloped-soarer** [pascallanger/DIY-Multiprotocol-TX-Module#97]

**Comment by sloped-soarer** [comment]
HI.
What is the recommended frame rate from the transmitter to the module when using serial protocol ?.
Please advise.

**Comment by schwabe** [comment]
OpenTX uses 9 ms, ersky9x uses 7ms.

**Comment by sloped-soarer** [comment]
Okay. Thanks for the information.
OpenAVRC will use 9ms.
The issue can be closed.
Sorry about the title of the issue .... finger trouble.
