### ISSUE TITLE
MT12 sub-protocol missing (DSM2SFC)

### ISSUE THREAD

**Issue by Guden79** [pascallanger/DIY-Multiprotocol-TX-Module#975]
Hello

I would like to use DSM2 surface. But on my Radiomaster MT12 the sub-protocol isn't listed at all? DSM2SFC is missing, I can't select it... Greetings Sascha

**Comment by pascallanger** [comment]
Install the test firmware https://downloads.multi-module.org/latest-test/

**Comment by Guden79** [comment]
THX a lot, that works great :-)
So happy now :-D
