### ISSUE TITLE
DSM2SFC - internal MultiModule inactiv after restart (Radiomaster MT12 with internal multimodule)

### ISSUE THREAD

**Issue by Guden79** [pascallanger/DIY-Multiprotocol-TX-Module#976]
Hello :-) 
The new DSM2 protocol now works with the test software 1.3.4.8. 
However, every time I restart the remote control I have to switch on the internal MultiModule again because it is then deactivated every time. This only happens (so far) with this protocol, DSM2SFC. 
After switching it on again and setting it to DSM2SFC, everything works wonderfully again, till the next restart...

Greetings Sascha

**Comment by pascallanger** [comment]
This is a bug in EdgeTX, Use the latest version or a nightly nuild.
