### ISSUE TITLE
Using the DIY V1.2 in the EU

### ISSUE THREAD

**Issue by dklueh79** [pascallanger/DIY-Multiprotocol-TX-Module#99]
Do you have some infos about the maximum performance in (watt) the diy transmitter module has? It's important for using it in the EU. 

https://www.banggood.com/2_4G-CC2500...p-1048377.html

**Comment by schwabe** [comment]
Your link is broken. But the maximum output is controlled by the software. But it should around 100 mW.

**Comment by dklueh79** [comment]
Ohh, sorry. This link is right:
https://m.banggood.com/2_4G-CC2500-A7105-Flysky-Frsky-Devo-DSM2-Multiprotocol-TX-Module-With-Antenna-p-1048377.html

Hmm, ok. 100mW would be ok. I'll will search for the option within the scetch.

**Comment by pascallanger** [comment]
The power settings for each RF component are set in Multiprotocol.h (middle of the file). They can be changed to whatever you want.
